### ISSUE TITLE
Cannot start game on arch linux (i5 3320m hd4000 mesa)

### ISSUE THREAD

**Issue by ShFil119** [JACoders/OpenJK#1000]
**Operating system and version:**
fresh Arch linux

**Is this for single player or multiplayer?**
Both.

**Description of the bug (and if possible, steps to reproduce the bug):**
```
./openjk.x86_64 
OpenJK-MP: v1.0.1.0 linux-x86_64 Mar  3 2019
----- FS_Startup -----
Current search path:
/home/filip/.local/share/openjk/base
./base/assets3.pk3 (16 files)
./base/assets2.pk3 (62 files)
./base/assets1.pk3 (8320 files)
./base/assets0.pk3 (15346 files)
./base
    
----------------------
23744 files in pk3 files
execing mpdefault.cfg
couldn't exec openjk.cfg
couldn't exec autoexec.cfg
----- Initializing Renderer ----
Trying to load "rd-vanilla_x86_64.so" from "."...
Sys_LoadDll(./rd-vanilla_x86_64.so) failed: "Failed loading ./rd-vanilla_x86_64.so: ./rd-vanilla_x86_64.so: cannot open shared object file: No such file or directory"
Trying to load "rd-vanilla_x86_64.so" from "."...
Sys_LoadDll(./rd-vanilla_x86_64.so) failed: "Failed loading ./rd-vanilla_x86_64.so: ./rd-vanilla_x86_64.so: cannot open shared object file: No such file or directory"
Failed to load renderer
Automatically freeing 685 blocks making up 1724103 bytes
```

**What did you expect to happen instead?**
Game should start.

**Comment by ensiform** [comment]
Is the file in question (`rd-vanilla_x86_64.so`) sitting next to openjk.x86_64 ?

**Comment by ShFil119** [comment]
Nope, I've tried to enable each available target of cmake.

Weird is that I've tried openjk-git from aur and it works (only needed to tweak paths).
https://aur.archlinux.org/packages/openjk-git/
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openjk-git

**Comment by ensiform** [comment]
Then you need to make sure you have that file. It is required build output.

**Comment by ShFil119** [comment]
My bad. I was forgetting about needed "install". (To close?)
