### ISSUE TITLE
Remove Limitation for Cinematic GLA Loading...

### ISSUE THREAD

**Issue by Archangel35757** [JACoders/OpenJK#1005]
Game: Single Player (Enhancement)
File:  tr_ghoul2.cpp
Lines:  3577-3589

Currently, the code limits/restricts cinematic gla loading to _humanoid models that use _humanpid.gla.  Recoding this to check for a cinematic gla for any model is straightforward, and would be an enhancement.  E.g. Recreating the Hoth ice cave events as a conematic between Luke and the Wampa-- would allow for future creature cinematics with requiring any recompile of their baseline GLA file.

**Comment by xycaleth** [comment]
Resolved by #1008
