### ISSUE TITLE
 The music is interrupted at the time of the save game.

### ISSUE THREAD

**Issue by Ivan19830111** [JACoders/OpenJK#1014]
**Operating system and version:**
Windows 7 64-bit SP1 / openjk-2019-05-13 (openjk_sp.x86 v.1.0.1.1)

**Is this for single player or multiplayer?**
Single Player

**Description of the bug (and if possible, steps to reproduce the bug):**
At the time of saving the game music is interrupted for a moment. Then after saving it is restored. It looks like a lag and the music that was playing is skipped for about 0.5-1 seconds.

**What did you expect to happen instead?**
In the original game and early builds before openjk-2015-02-02-8f553ca5 inclusive there is no such thing. Music is not interrupted during the save

**Comment by ensiform** [comment]
Saving is a disk hit so that is kind of expected?

**Comment by xycaleth** [comment]
Not if it didn’t happen before though

**Comment by Ivan19830111** [comment]
There was no such lag in the early builds

Maybe someone saved the source of these versions?
openjk-2015-02-02-8f553ca5
openjk-2015-02-09-366933d5

Because the lag starts with openjk-2015-02-09-366933d5 and is in all subsequent

**Comment by ensiform** [comment]
@Ivan19830111 is that when we switched to SDL?

**Comment by Ivan19830111** [comment]
ensiform
I also thought at first that the problem was in SDL, but it turned out that it was not. There are no SDL libraries in the above build.

**Comment by Ivan19830111** [comment]
All figured out. This is caused by the call to the S_ClearSoundBuffer () function.

**Comment by ensiform** [comment]
That function is by design. But it does not do anything with music.

**Comment by Ivan19830111** [comment]
Yes, you are right. I have a bug with a delay to reach the hard disk. But for myself, I removed in a couple of places (commented out) this function and the problem was solved. In fact, I left it only where it was in the original game.
