### ISSUE TITLE
64bit macOS version

### ISSUE THREAD

**Issue by leszek-s** [JACoders/OpenJK#1029]
Please make macOS builds 64 bit as 32 bit apps no longer work on newest macOS Catalina and latest macOS build is quite old now.

**Comment by ensiform** [comment]
Even if/when that happens, any existing mods which have support and released will cease to function as they are only PPC/x86 only. FYI

**Comment by xycaleth** [comment]
> Please make macOS builds 64 bit as 32 bit apps no longer work on newest macOS Catalina and latest macOS build is quite old now.

The macOS builds are already 64-bit. What problems are you having with running them?

**Comment by leszek-s** [comment]
OK it works. It was showing a system error on start previously and I thought it was because it was not 64 bit but it turned out that the problem was it did not detect libsdl2 which I installed with macports. I copied it into a different directory and that solved it.
