### ISSUE TITLE
Segfaults when trying to start new single player game.

### ISSUE THREAD

**Issue by mahavishvarupa** [JACoders/OpenJK#1032]
If you go to start a new single player game on JA it goes to the loading screen which has the three images of the Jedi with the sabre staff and promptly segfaults.

OS: Archlinux x86-64.

**Comment by vilhelmgray** [comment]
This might be a duplicate of https://github.com/JACoders/OpenJK/issues/1021

**Comment by mahavishvarupa** [comment]
I've had a look and it is.  I'll close the ticket.
