### ISSUE TITLE
JK2 SP crash on startup on Windows 7

### ISSUE THREAD

**Issue by B-Keeper** [JACoders/OpenJK#1041]
Source snapshot from 05/28/2020 (latest commit 5203023) built with mingw-w64, GCC version 10.1.0.

OS: Windows 7 Home Premium SP1
CPU: AMD Phenom II 64-bit
GPU: AMD Mobility Radeon HD4200

OpenJK Jedi Outcast singleplayer crashes on startup, yields the following Windows error report:

  Problem Event Name:	BEX64
  Application Name:	openjo_sp.x86_64.exe
  Application Version:	1.0.1.1
  Application Timestamp:	5ecf9eb1
  Fault Module Name:	openjo_sp.x86_64.exe
  Fault Module Version:	1.0.1.1
  Fault Module Timestamp:	5ecf9eb1
  Exception Offset:	00000000011c34d4
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	7e5f
  Additional Information 2:	7e5f7362f44594a815398758a2ce1035
  Additional Information 3:	aa7d
  Additional Information 4:	aa7d87dea5d70b3876d7283133ebe601

No additional information or log files. Happens even if there's no game data present, the application doesn't seem to be able to even initialize itself. Last time I built OpenJK on the same machine was about a year ago (I have no record of the revision/commit number or GCC version at the time), and everything was working fine.

**Comment by ensiform** [comment]
Try compiling a debug version to get real information. Nothing here helps determine the cause. Also it is entirely possible that you might even have external software trying to hook in and interfere such as overlays.

**Comment by B-Keeper** [comment]
Okay, I made a debug build, and ran it through GDB. Here's the result:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000015ee4f4 in memoryPool ()
```

As for overlays, I'm not aware of having anything installed on my system that could potentially interfere (such as a GPU control app).

**Comment by Calinou** [comment]
Isn't Jedi Outcast singleplayer not in a working state?

**Comment by B-Keeper** [comment]
@Calinou 
Certainly not. As I mentioned in my original post, I did compile and play it in the past.
