### ISSUE TITLE
openjk_sp.x86_64: Couldn't load default.cfg

### ISSUE THREAD

**Issue by TheOneWhoseUsernameWasTaken** [JACoders/OpenJK#1052]
I'm trying to run Jedi Academy under Linux Mint 20. Since the most recent Linux build is over two years old now, I had to build the current version myself. Which seems to have worked fine. But I cannot start the game. Whenever I run openjk_sp.x86_64, I get the error that it couldn't find the file "default.cfg". Which does not surprise me, because that file really does not exist.

I tried running it from the JA install dir, from the GameData dir, and from the GameData/JediAcademy dir. Always with the same result.

My Jedi Academy version is from GOG.com which I installed using WINE. I double-checked by running the installer in a Windows VM, and it seems to match the WINE installation.

```
$ cat ~/.local/share/openjk/crashlog-2020-10-02_20-23-47.txt 
OpenJK: v1.0.1.1 linux-x86_64 Oct  2 2020
Initialising zone memory .....
----- FS_Startup -----
Current search path:
/home/user/.local/share/openjk/base
./JediAcademy/base

----------------------
0 files in pk3 files
Couldn't load default.cfg

$ find -iname '*.cfg'
./GameData/base/jaconfig.cfg

$ uname -a
Linux triton 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ensiform** [comment]
You need the game files.

**Comment by TheOneWhoseUsernameWasTaken** [comment]
That's why installed the game and then put OpenJK into the GameData directory.

```
$ find -iname '*.pk3'
./base/assets3.pk3
./base/assets0.pk3
./base/assets1.pk3
./base/assets2.pk3
```

What else do I need?

**Comment by TheOneWhoseUsernameWasTaken** [comment]
Ah, I think I found the issue. The game files from the original game are located under GamaData/base. But when you install OpenJK into the GameData directory (as documented), then it creates the directory GameData/JediAcademy/base. And that is then where it looks for those files.

After running the command:
```
cd GameData/JediAcademy/base
for f in ../../base/*; do ln -s "$f"; done
```

to create some symlinks to the actual files, the game actually launches.

I suggest to either add this step to the documentation or make OpenJK look in the correct directory.

**Comment by ensiform** [comment]
The jedi academy folder should not be extracted as such. The extra step to link is unnecessary. It should just be GameData/base

**Comment by TheOneWhoseUsernameWasTaken** [comment]
I did not extract any folders. Your 'make install' script created them within my game's vanilla installation. And if I do not create the links, then OpenJK  won't start (see original issue).

**Comment by ensiform** [comment]
Did you correctly setup cmake install prefix before running make install?

The directions here https://github.com/JACoders/OpenJK/wiki/Compilation-guide say that's a key step.

**Comment by TheOneWhoseUsernameWasTaken** [comment]
I followed the guide, and did set the CMAKE_INSTALL_PREFIX (which, according to the guide, is only recommended, not necessary). Had I not done so, how could OpenJK have installed itself into my GameData directory in the first place?

**Comment by ensiform** [comment]
Just move the contents of JediAcademy into root and delete it. More correct than using hasty symlinks. The point of that is when you try to build both academy and outcast you can then ship in archive together but still have to extract the contents of each game folder to the correct game directory it seems.

**Comment by TheOneWhoseUsernameWasTaken** [comment]
In that case, I come back to my comment above (702948207). This runs counter to the documentation. Because the compilation guide states basically the opposite.

Quote:

> We highly recommend setting CMAKE_INSTALL_PREFIX to JKA's GameData folder [...]
> [...]
> If you have set CMAKE_INSTALL_PREFIX correctly, running make install will copy all the built files into their correct places
> in your GameData folder, ready to run and test.

To me, this seems to clearly be inaccurate. I **did** set the CMAKE_INSTALL_PREFIX as recommended, and now you're telling me the files were in fact **not** put in their correct places, and are **not** read to run.

Speaking for all dumb people like me, I humbly submit that you should either change the install procedure to reflect the guide, or change the guide to reflect the install procedure. The former would probably be preferable (as it requires fewer steps from the user and is thus less likely to create problems), but in the end, either one is fine. But the documentation should be accurate. Just saying.

**Comment by xycaleth** [comment]
It looks like the wiki documentation is out of date and/or incorrect. Since anybody can change the wiki we don't generally get to look over every change so there might be mistakes.

To get this to work, the file/directory structure you want should be this (without the GameData directory).
```
base/
|- assets0.pk3
|- assets1.pk3
|- assets2.pk3
|- cgamex86_64.so
|- jampgamex86_64.so
+- uix86_64.so
openjk_sp.x86_64
openjk.x86_64
```

Unfortunately because of the way CMake installs packages, you will find you have an extra JediAcademy folder if you try using the `make install` target. Since we have a Jedi Academy and a Jedi Outcast package, you end up with a JediAcademy folder and a JediOutcast (if it was built).

The easiest solution is to manually move the files into their correct place.

**Comment by TheOneWhoseUsernameWasTaken** [comment]
> The easiest solution is to manually move the files into their correct place.

On the other hand, if you symlink the entire "base" directory, you can easily update your OpenJK without having to manually copy the files _every_. _single_. _time_. Might be easier in the long run.

From within the GameData/JediAcademy directory:

```
mv base/* ../base/
rmdir base
ln -s ../base
```

Next time I run "make install" from the source, the files should be put in the correct location immediately, thanks to the magic of symlinks. ¯\\_(ツ)_/¯
