### ISSUE TITLE
No version (or tag) available at Dockerhub

### ISSUE THREAD

**Issue by alexaugustobr** [JACoders/OpenJK#1068]
Hello I see you guys have a dockerhub profile, but there is no version (or tag) available on it, https://hub.docker.com/r/jacoders/openjk

Can you guys enable autobuild, based on push of this repository?

**Comment by xycaleth** [comment]
Odd, we never created a dockerhub account. It must be someone else who created it 🤔

**Comment by alexaugustobr** [comment]
@xycaleth Anyone on the team can't create a dockerhub profile?
