### ISSUE TITLE
no videos intro when using + set r_noborder 1 option

### ISSUE THREAD

**Issue by legluondunet** [JACoders/OpenJK#1074]
Hello,

when I launch openjk with this command:

`./openjo_sp.x86_64 +set r_mode -2 +set r_noborder 1`

openkj skipped all videos intro and you come directly to menu.

Could you reproduce this issue?

**Comment by ensiform** [comment]
If typed exactly as is, there might be an issue with the space between the + and set as that is malformed,

**Comment by legluondunet** [comment]
thank you for your help.
