### ISSUE TITLE
Can't join most servers on Linux

### ISSUE THREAD

**Issue by githubstar1234** [JACoders/OpenJK#1086]
**Operating system and version:**
Debian GNU/Linux 10

**Is this for single player or multiplayer?**
Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
I just started using Linux and it seems that OpenJK compiled on Linux can't connect to some servers for some reason. It's just stuck on 'Awaiting challenge' screen forever and nothing happen. I have tried OpenJK/EJK on Windows and there is no issues connecting to same servers from same network and IP address.

Servers that I cant connect:

135.148.31.103:29070
135.125.140.165:29070
135.148.37.154:29070
51.195.79.85:29070
135.125.145.49:29070

Those are most popular and populated servers currently existing in JKA multiplayer

**What did you expect to happen instead?**
Join and play on my favourite servers

**Comment by Reelo21x** [comment]
Exact same issue :(

**Comment by ensiform** [comment]
It's not an OpenJK issue. The server/host is filtering clients out it seems.

**Comment by Asulynn** [comment]
Yeah, hi, I'm hosting those servers. That's a network issue on my side and not OpenJK related. It's not intentional. I'll look into it shortly.

**Comment by Reelo21x** [comment]
> 
> 
> Yeah, hi, I'm hosting those servers. That's a network issue on my side and not OpenJK related. It's not intentional. I'll look into it shortly.

Hopefully gets fixed soon. This has been an issue for weeks. wasnt until I noticed other linux friends having the same issue that we saw it only happened on your servers.

**Comment by Asulynn** [comment]
Righto, I setup a test machine and was able to - I think - reproduce this. You should be good now.

As this isn't OpenJK related, I'll let them close this. If you still have a problem you can toss me an email instead: mail (at) asutech.io
