### ISSUE TITLE
Support for custom velocity and kata trails

### ISSUE THREAD

**Issue by Automa-C3PO** [JACoders/OpenJK#1092]
_I don't well where to post this request, so here is it:_

could you implement two variables to increase weapons' primary and secondary fires velocity? I've been using a patch by Dusty modder on JKHub for that, it'd start to make sense if blasters weren't that slow and could be tweaked. I don't know if OpenJK has this already planned. Dusty's patch had the new variables: **g_weaponVelocity** and **g_weaponAltVelocity**, the value is a _multiplier_ of default velocity, you could port those from his project.

Also we could use another command to disable kata trails for all sabers. The old **cg_sabertrail** works only for multiplayer and disables every trail, it would need instead something as in _MD_ or _SWGL_ mods where only kata ones are disabled for singleplayer.

**Comment by ensiform** [comment]
Both of these requests are out of scope of OpenJK.

**Comment by Automa-C3PO** [comment]
Why? You mean all _three_? OpenJK must be an improvement on open source of JKA. Some modders made their own features for their mods from OpenJK, and I don't see a reason why you shouldn't implement these commands as standard, to overwrite the parameters that too often had been perused. I didn't ask a mod, I asked about more control on hardcoded stuff. Dusty was one of the best modders, and left the source code on _sourceforge_ that possibly I can't link here...

**Comment by ensiform** [comment]
OpenJK isn't interested in adding tons of customization and cvars at will. Not to mention, the lack of people working on the project regularly now. That is for mods to do and make as they see fit. I don't see any reason why we should. My mod from years ago had high customizable weapon fields and this was long before OpenJK existed. Saber trail changes I don't really see the reason behind why it would be something we would need to have in general.

**Comment by Automa-C3PO** [comment]
Look it's not that many of customizations, those are simple variables to control important parameters such as blaster speed and kata trails, not to mention, that one of them was already incepted by developers and would just need to be hooked to singleplayer, for kata only.
> My mod from years ago had high customizable weapon fields and this was long before OpenJK existed.
What was your mod, so everyone can check it out? OpenJK has existed for many years, and I don't think hardcoded entries like weapons' fields were customizable before. Is that compatible with latest releases?
> Saber trail changes I don't really see the reason behind why it would be something we would need to have in general.
I think you're paraphrasing too much, don't see it? Why not, it's one of the most discussed aspects of this game, see on _JKHub_ how many asked about it, not everyone is ready to pick _Visual C++_ at whim...

**Comment by ensiform** [comment]
Saber trails should probably always be visible in MP, otherwise you risk having some players with an advantage over players that do not have the option to turn them off.

Further, the remainder is not in the spirit of the aim of this project as defined in the readme on the main project page.

I don't think I have a copy of the mod source anymore unfortunately but making such changes isn't very difficult for those who are making mods. The original sdk even shows how to customize rocket speed for example.

**Comment by Automa-C3PO** [comment]
I think developers left them for servers not clients, however I meant for singleplayer...SWGL is a perfect example.
> as defined in the readme on the main project page.

I've read it
> The original sdk even shows how to customize rocket speed for example.

Yes it shows some examples well appended about several things, modders are settled but newcomers must prepare their computer for C++ and I won't do that yet.
> I don't think I have a copy of the mod source anymore _unfortunately_

I didn't ask you the open source I asked what was your mod, if I wanted your source code I wouldn't be here committing these
features, wouldn't I...guess I have to set a serious C++ environment in my PC once for all, therewith it ends.

**Comment by ensiform** [comment]
I have no idea what SWGL is.

Alternatively you could make a public mod request on the JKC Discord coding channel or on JKHub to other people who may be willing to make a mod for your needs.

As it stands myself and many of the other original OpenJK devs are not super active on JKHub or on JK dev still.

**Comment by Automa-C3PO** [comment]
Done. I'll make it myself.
> I have no idea what SWGL is.

Honestly you should, it's just among the most known JKA mods ever..._Star Wars Galactic Legacy_.
>  other people who may be willing to make a mod for your needs.

eh sounds demanding...I kinda remember having sent you a monetized request..usually that make'em clock. 
> As it stands myself and many of the other original OpenJK devs are not super active on JKHub or on JK dev still.

yea they slowed down, long time passed and must have moved to other things...still I think this ageless game as deserving a better community, regardless of better game engines got released in the meantime.  I'll see...
