### ISSUE TITLE
HandHeld  Arm version OpenJO  Need ...

### ISSUE THREAD

**Issue by wgarnett** [JACoders/OpenJK#1101]
**Operating system and version:**

RGB10 HandHeld , RK3326 CPU , Arm , OS : ArkOS  

**Is this for single player or multiplayer?**

I need arm version (best armv7l , armv7)  OpenJO (not OpenJK , I already have this arm verision )

**Description of the bug (and if possible, steps to reproduce the bug):**

I use arm OpenJK or add +set jk2 1 , JK2 has no text on menu , but JA is work fine on OpenJK , so , I need OpenJO arm version for JK2 

**What did you expect to happen instead?**

plz help to build one arm version OpenJO and share , thanks .......

**Comment by ensiform** [comment]
I moved your other to a discussion and you open a new issue. Please use the discussion instead.

ARM support is not handled on OpenJK. Where did you find OpenJK arm version? Contact whomever made that for you to also build OpenJO. There is no switch to run both from main directory. Issues are not for this type of discussion.
