### ISSUE TITLE
Assertion `bone.startFrame<=numFramesInFile' failed

### ISSUE THREAD

**Issue by nandlab** [JACoders/OpenJK#1117]
**Operating system and version:**
Linux Mint 20.3

**Is this for single player or multiplayer?**
Movie Battles 2 Multiplayer Mod (requires the 32 bit OpenJK build)

**Description of the bug (and if possible, steps to reproduce the bug):**
Movie Battles 2 launches normally and I can watch a game. But after I choose a class and a new round starts, the game crashes with the following error:
```
openjk.i386: /home/dan/git/OpenJK/codemp/rd-vanilla/tr_ghoul2.cpp:1091: void G2_TimingModel(boneInfo_t&, int, int, int&, int&, float&): Assertion `bone.startFrame<=numFramesInFile' failed.
^3Tutorial data info saved
Closing SDL audio device...
SDL audio device shut down.
Automatically freeing 3050 blocks making up 44234444 bytes
```
exit code: 2

**What did you expect to happen instead?**
Start playing the round with the selected class.

**Comment by ensiform** [comment]
Looks like a bug in the assets you're using maybe a custom model.

**Comment by nandlab** [comment]
I did a release build and now it works. Maybe the assertion is just optimized out.
