### ISSUE TITLE
RE_BeginFrame: Stereo is enabled, but stereoFrame was 0

### ISSUE THREAD

**Issue by Rugaliz** [JACoders/OpenJK#1120]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Fedora 36 Linux 64-bit 

**Is this for single player or multiplayer?**
Single player

**Description of the bug (and if possible, steps to reproduce the bug):**
Got "RE_BeginFrame: Stereo is enabled, but stereoFrame was 0" error

This is the log saved

`tty console mode disabled
OpenJK: v1.0.1.1 linux-x86_64-debug Jun 21 2022
Initialising zone memory .....
----- FS_Startup -----
Current search path:
/home/rugaliz/.local/share/openjk/base
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/zzzMovieSabers.pk3 (171 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/VaderEp3.pk3 (78 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/saber_tano.pk3 (15 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/hs_rots-kenobi_SP.pk3 (22 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/hs_rots-kenobi.pk3 (88 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/HS_rots-dooku.pk3 (76 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/hs_kenobi3-saber_SP.pk3 (5 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/hs_dooku-saber_SP.pk3 (5 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/Episode3blades.pk3 (17 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/CTF_battlefrontyavin.pk3 (25 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/Bloody_Dismemberment!.pk3 (113 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/assets3.pk3 (16 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/assets2.pk3 (62 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/assets1.pk3 (8320 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/assets0.pk3 (15346 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base/Ahsoka Tano.pk3 (73 files)
/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData/base

----------------------
24432 files in pk3 files
execing default.cfg
execing openjk_sp.cfg
couldn't exec autoexec_sp.cfg
Running Jedi Academy Mode
----- Client Initialization -----
----- Initializing Renderer ----
Trying to load "rdsp-vanilla_x86_64.so" from "/mnt/de0a322a-8faa-4b1d-92c7-2ef43a5e9235/Games/Jedi Academy/GameData"...
-------------------------------
----- Client Initialization Complete -----
--- Common Initialization Complete ---
SDL Version Compiled: 2.0.22
SDL Version Linked: 2.0.22
SDL using driver "wayland"
Initializing display
Display aspect: 1.778
...setting mode 9: 1600 1200
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '864x486 1280x720 1600x900 1920x1080 2048x1152 2560x1440 1368x768 1280x800 1440x900 1680x1050 1920x1200 720x480 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1440x1080 1600x1200 1920x1440 1280x1024'
Initializing OpenGL extensions
...GL_S3_s3tc available
...GL_EXT_texture_compression_s3tc available
...no tc preference specified
.....using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_env_add
...GL_EXT_texture_filter_anisotropic available
...using GL_EXT_texture_filter_anisotropic
...using GL_EXT_texture_edge_clamp
...using GL_ARB_multitexture
...using GL_EXT_compiled_vertex_array
...GL_NV_register_combiners not found

GL_VENDOR: AMD
GL_RENDERER: AMD Radeon RX 5600 XT (NAVI10, DRM 3.46.0, 5.18.5-100.fc35.x86_64, LLVM 13.0.0)
GL_VERSION: 4.6 (Compatibility Profile) Mesa 21.3.8
GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_depth_bounds_test GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_meminfo GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_direct_state_access GL_EXT_shader_image_load_store GL_EXT_vertex_attrib_64bit GL_NV_vdpau_interop GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_AMD_pinned_memory GL_ARB_bindless_texture GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_NVX_gpu_memory_info GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_sparse_buffer GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_EXT_shader_image_load_formatted GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_NV_shader_atomic_int64 GL_ARB_ES3_2_compatibility GL_ARB_gpu_shader_int64 GL_ARB_parallel_shader_compile GL_ARB_post_depth_coverage GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_EXT_shader_samples_identical GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_ARB_gl_spirv GL_ARB_spirv_extensions GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_parallel_shader_compile GL_NV_alpha_to_coverage_dither_control GL_AMD_framebuffer_multisample_advanced GL_EXT_EGL_image_storage GL_EXT_texture_shadow_lod GL_INTEL_blackhole_render GL_MESA_framebuffer_flip_y GL_NV_compute_shader_derivatives GL_EXT_EGL_sync GL_EXT_demote_to_helper_invocation 
GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_ACTIVE_TEXTURES_ARB: 8

PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
MODE: 9, 1600 x 1200 fullscreen hz:N/A
GAMMA: software w/ 0 overbright bits
rendering primitives: single glDrawElements
texturemode: GL_LINEAR_MIPMAP_LINEAR
picmip: 0
texture bits: 32
multitexture: enabled
compiled vertex arrays: enabled
texenv add: enabled
compressed textures: enabled
compressed lightmaps: disabled
texture compression method: GL_EXT_texture_compression_s3tc
anisotropic filtering: enabled  (16 of 16)
Dynamic Glow: disabled

------- sound initialization -------
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "pulseaudio".
SDL_AudioSpec:
  Format:   AUDIO_S16LSB
  Freq:     44100
  Samples:  1024
  Channels: 2
Starting SDL audio callback...
SDL audio initialized.
Extended sound quality field to contain very high option.
Disabling eax field because current platform does not support EAX.
Hiding eax_icon object because current platform does not support EAX.
Extended subtitles field to contain all voiceovers option.
UI menu load time = 265 milli seconds
----- CL_Shutdown -----
Closing SDL audio device...
SDL audio device shut down.
-----------------------
RE_BeginFrame: Stereo is enabled, but stereoFrame was 0`

**Comment by Rugaliz** [comment]
Well how do I disable it so the game doesn't crash?

**Comment by ensiform** [comment]
You've turned it on somehow in your config.

Look for cg_stereo related and r_stereo related to make sure they are 0.

**Comment by Rugaliz** [comment]
It wasn't my config as I cloned a clean version. It's probably wayland then. But shouldn't wayland support be a priority at this point? its the future and also present of mainstream Linux distros.

**Comment by ensiform** [comment]
Wayland is still alpha quality software in my opinion when it comes to gaming and especially Nvidia. Regardless if distros are using it. SDL support (required by this project and many games today) is also barely there, especially if you don't use bleeding edge SDL builds, which Ubuntu and debian based never do.

The cvar is not on by default, and the only way to get the error message you see is if it is nonzero.

Your logs would look better inside code blocks on here btw.

**Comment by xycaleth** [comment]
The error isn't dependent on the windowing system. @Rugaliz Do you still get the error after ensuring `r_stereo` is set to 0? I don't think the stereo (stereoscopic) rendering was ever completed or supported in the JKA code which is why you were seeing that error (assuming r_stereo was set to 1 at the time).

**Comment by Rugaliz** [comment]
in shared/sdl/sdl_window.cpp:
`	r_stereo			= Cvar_Get( "r_stereo",				"0",		CVAR_ARCHIVE_ND|CVAR_LATCH );`
in codemp/rd-dedicated/tr_init.cpp:
`r_stereo							= ri.Cvar_Get( "r_stereo",							"0",						CVAR_ARCHIVE_ND|CVAR_LATCH, "" );`

Anywhere else I should look?

This is the output from a grep search 
![image](https://user-images.githubusercontent.com/37263443/175776396-fdc5c366-0e79-48cb-bc46-0c8211a3cd13.png)

**Comment by ensiform** [comment]
In your `openjk_sp.cfg` file it must be > 0. It is not anything but zero in the code as you just showed.

**Comment by Rugaliz** [comment]
hmm I don't any an openjk_sp.cfg or any cfg files in my source folder...or the game folder.

**Comment by ensiform** [comment]
Yes in fact it is located in `/home/rugaliz/.local/share/openjk/base`

**Comment by Rugaliz** [comment]
I could not find any "r_stereo" in any of the files in that directory. So I just deleted everything to make openjk write new files and it seamed to work.
I still don't know exactly what caused the issue but it seams to be fixed doing it the dirty way.
