### ISSUE TITLE
point  jospgamearm.so to look for different game/DIR

### ISSUE THREAD

**Issue by Exarkuniv** [JACoders/OpenJK#1123]
**Operating system and version:**
Pi4 buster/RetroPie

**Is this for single player or multiplayer?**
SP

**Description of the bug (and if possible, steps to reproduce the bug):**
the game will start and work fine in menu, but will fail when trying to start the game due to `jospgamearm.so` not sitting in the base folder

i added `-CMAKE_INSTALL_PREFIX=/home/pi/RetroPie/roms/ports/jedioutcast/base` to `cmake` command when i build it and it is still looking for the game data in the wrong place. 

can it be told where to look or does `jospgamearm.so` need to be in the base folder

here is my whole command im useing
```
cmake -DBuildJK2SPEngine=ON -CMAKE_INSTALL_PREFIX=/home/pi/RetroPie/roms/ports/jedioutcast/base -DBuildJK2SPGame=ON -DBuildJK2SPRdVanilla=ON -DCMAKE_BUILD_TYPE=Release ..
```

im sure i have something wrong

thx

**Comment by ensiform** [comment]
It will always still append /JediOutcast to whatever prefix you use. So you need to manually move this

**Comment by Exarkuniv** [comment]
ok so having `-CMAKE_INSTALL_PREFIX=/home/pi/RetroPie/roms/ports/jedioutcast/base` is not needed now, correct

**Comment by ensiform** [comment]
You should be installing it into the `/home/pi/RetroPie/roms/ports/jedioutcast/` folder. As the binary executable will be there. and jospgame should be placed within /base and /OpenJO but it does append /JediOutcast no matter what CMAKE_INSTALL_PREFIX you provide. And it is case sensitive if ext4.

**Comment by Exarkuniv** [comment]
Yes once i move 'jospgamearm.so' in the the base folder, it works fine. im just working on a install script for RetroPie. the old one did not have it moved into the base folder. 

and i was seeing if there was a way to have it look for what it needs so we dont have to have the binary in the roms folder

(we try to keep from people being dumb and deleting stuff they need for it to work.)
if thats where is needs to go, i will make it do just that. 

thanks again for your help

**Comment by ensiform** [comment]
It really should be changed but because there's two games from one main CMake file I don't know if there's any easy way to go around it. Though I do wish we could.

**Comment by Exarkuniv** [comment]
maybe at some point someone will think of something, but im good with this, if someone deletes it, then maybe they should not be trying to play it, 

have a good one
