### ISSUE TITLE
Cvars are locked in multiplayer

### ISSUE THREAD

**Issue by hereticguy** [JACoders/OpenJK#1126]
First of all, thanks for the great source port!
I have an issue; I want to change the third person camera height  with "cg_thirdpersonvertoffset" command. But I can't use that command in Multiplayer mode; because it counts as a cheat and can't modify "sv_cheats" value. 
When I use "EternalJK" fork; i can use that third person camera commands. Is it possible to use them with OpenJK?
Thanks in advanced!

**Comment by ensiform** [comment]
It's marked as a cheat in the mod that is running. And I don't see it changing. Because it's an advantage.
