### ISSUE TITLE
SP Quest Objective Updates and Switch Functionality Broken

### ISSUE THREAD

**Issue by Sync-67** [JACoders/OpenJK#1144]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Windows 10 v10.0.19045 Build 19045
OpenJK 2023-04-17-f3fbe80b and latest build on GitHub (2023-04-21-f1148bc), both x86 and x64

**Is this for single player or multiplayer?**
Single Player (Jedi Academy)

**Description of the bug (and if possible, steps to reproduce the bug):**
Using a switch does not change the state of the connected object. For example, activating an elevator, diffusing explosives, or turning off the tractor beams in Mos Eisley. When using the switch is required for a quest, the required state is not achieved and the quest objectives in the data pad do not update. This often breaks game progression.

To reproduce, use the attached save file ("Mercenary Activity- Tatooine" level), walk into the elevator, then go to use one, or either, of the switches controlling the tractor beams holding the Raven's Claw and Millennium Falcon. Using the switches does not activate the dialogue, release the tractor beams, or update the objectives in the data pad. 

**What did you expect to happen instead?**
Using the switch should update the state of the connected object. In this case, turning off the tractor beams, thereby activating the pertinent dialogue, and updating the quest objectives.

The last build I could get the expected switch behaviour from was "openjk-2023-04-10-d3e8c8d7-windows" from the builds.openjk.org site. Please let me know if there's any other information I can provide. Thanks for maintaining this awesome resource!

[OpenJK Switch Bug Test Save.zip](https://github.com/JACoders/OpenJK/files/11297770/OpenJK.Switch.Bug.Test.Save.zip)

**Comment by ensiform** [comment]
Ongoing issue or recent only

**Comment by Sync-67** [comment]
@ensiform I've just run into it in the past couple days, but when I figured out what was happening I went through the older builds until I found one that worked (ie. the 2023-04-10-d3e8c8d7 build).

**Comment by ensiform** [comment]
I can't see anything that changed which would trigger differences with scripting and map functions or saves. It seems more like existing known possible glitches.

Can it be reproduced regardless of save or was this save existing before?

**Comment by NinjaSpectre** [comment]
I believe I am encountering the same issue.  I think it is related to when a cut scene would be triggered by level scripting.  On a new game I am not able to progress to the second door during the introduction to force powers on Yavin.  The cut scene for Kyle doesn't trigger. I too am on Windows 10, and the last binary that works is from the d3e8c8d7 commit.

**Comment by ensiform** [comment]
Pretty sure there's all kinds of brokenness. Even in jk2 something isn't right on kejim_base

**Comment by NinjaSpectre** [comment]
Commit 6f5c5788 works.  Commit c55d81a2 does not trigger the cut scenes.

**Comment by NinjaSpectre** [comment]
@ensiform Changing these conditionals back to the way they were before commit c55d81a fixes the problems I have encountered.

https://github.com/JACoders/OpenJK/blob/f1448bc2c04d13f259a88dd2a22d6b3c6fa68772/code/game/Q3_Interface.cpp#L10571
https://github.com/JACoders/OpenJK/blob/f1448bc2c04d13f259a88dd2a22d6b3c6fa68772/codeJK2/game/Q3_Interface.cpp#L8600
```c++
if( strlen(name) > 5 && !Q_stricmpn(name, "cvar_", 5) )
```
I do not know if this negates what you were trying to achieve with the commit.

**Comment by ensiform** [comment]
Huh, wrong boolean state I guess got switched possibly in merge
