### ISSUE TITLE
Application unable to start correctly.

### ISSUE THREAD

**Issue by oGennyo** [JACoders/OpenJK#1145]
**Operating system and version:**
Windows 10

**Is this for single player or multiplayer?**
Singleplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
I'm following the instructions to compile the source code, but when I rename the executables after building under release, I get an error that states the application was unable to start correctly. They're in the GameData folder and I've deleted the necessary files.

**What did you expect to happen instead?**
Singleplayer to launch.

**Comment by ensiform** [comment]
There's no instructions to rename or delete files, what are you following

**Comment by oGennyo** [comment]
> following

I'm following the compilation guide linked on the GitHub page for OpenJK under developers.

The installation subsection says this: ![Screenshot_20230423_090038_Chrome.jpg](https://user-images.githubusercontent.com/42878284/233841316-25ef1e6e-5598-4324-8ffb-08d02ad3136b.jpg)

**Comment by ensiform** [comment]
Yeah I guess, someone added that to the wiki. But I don't recommend it at all. You're likely missing other files not copied to the folder such as SDL2.dll

**Comment by oGennyo** [comment]
> Yeah I guess, someone added that to the wiki. But I don't recommend it at all. You're likely missing other files not copied to the folder such as SDL2.dll
> 
> This wiki was updated by a non member FYI 

I've got that file in my game data folder. Is there a better guide to compiling?

**Comment by ensiform** [comment]
Are you compiling because you made changes?  Because the regular build should run fine

**Comment by oGennyo** [comment]
> Are you compiling because you made changes?  Because the regular build should run fine.
> 
> 
> I mean the guide should not ever suggest deleting or rename files. Steam will just overwrite if it wants to. Just run openjk without renaming, but needs to be with the assets. Do you really need to show playing on steam?

Yeah, I was planning on making some mods and wanted to go through a trial run on compiling the game.

I'm completely new to this so forgive my ignorance, haha. 

I'll attempt another go without deleting the files. The guide attached to the GitHub should definitely be changed or removed, however.

**Comment by ensiform** [comment]
> > Are you compiling because you made changes?  Because the regular build should run fine.
> > 
> > 
> > I mean the guide should not ever suggest deleting or rename files. Steam will just overwrite if it wants to. Just run openjk without renaming, but needs to be with the assets. Do you really need to show playing on steam?
> 
> Yeah, I was planning on making some mods and wanted to go through a trial run on compiling the game.
> 
> I'm completely new to this so forgive my ignorance, haha. 
> 
> I'll attempt another go without deleting the files. The guide attached to the GitHub should definitely be changed or removed, however.

Just follow putting the files in the steam folder as download regular builds. It's not as simple to just replace files in steam and have it work inside of steam showing you playing as the original game.
