### ISSUE TITLE
Question: no template "X" in namespace 'gsl::std'

### ISSUE THREAD

**Issue by JoshuaPettus** [JACoders/OpenJK#1148]
I'm certain this is a me issue as it use to compile not too long ago.   Maybe it's a fedora 38 issue as I recently upgraded
 I keep getting various errors like this when trying to compile:

>openjk/lib/gsl-lite/include/gsl/gsl-lite.h:479:13: error: no template named 'reverse_iterator' in namespace 'gsl::std'; did you mean '::std::reverse_iterator'?

> openjk/lib/gsl-lite/include/gsl/gsl-lite.h:483:22: error: no template named 'iterator_traits' in namespace 'gsl::std'; did you mean '::std::iterator_traits'?

> openjk/lib/gsl-lite/include/gsl/gsl-lite.h:493:33: error: no type named 'nullptr_t' in namespace 'gsl::std'; did you mean '::std::nullptr_t'?

> openjk/lib/gsl-lite/include/gsl/gsl-lite.h:765:46: error: no template named 'array' in namespace 'gsl::std'; did you mean '::std::array'?

> openjk/lib/gsl-lite/include/gsl/gsl-lite.h:818:17: error: no member named 'wstring' in namespace 'gsl::std'

There are like 20 of these errors of various std libraries..all stemming from gsl-lite.h     It's all very odd.  I've tried clang and gcc and they both complain at the same point.  Any ideas what maybe wrong with my environment now?

**Comment by Fixmetal** [comment]
+1, also faced this using a Fedora 38 container after installing all the dev dependencies and following the guidelines for building.

How reproducible:
```
$ podman run -it --rm --entrypoint bash -v "${PWD}":/Games:Z fedora:38

# dnf install cmake3 make gcc gcc-c++ glibc-devel libstdc++-devel libjpeg-turbo-devel libpng-devel zlib-devel  libglvnd-devel SDL2-devel -y
# dnf groupinstall "Development tools" -y
# git clone https://github.com/JACoders/OpenJK.git <-- using master branch, no tags are being used for releasing here...
# cd OpenJK
# mkdir build
# <EDIT CMakeLists.txt to enable JK2 build>
# cd build
# cmake -DCMAKE_INSTALL_PREFIX=/Games/ja/GameData/ ..
# make
```

It works using a `fedora:37` container image. Seems likely no issues have been yet raised at https://github.com/microsoft/GSL about it

**Comment by karabaja4** [comment]
Same issue trying to build on Arch via https://aur.archlinux.org/packages/openjk-git

**Comment by ensiform** [comment]
unfortunately upgraded gsl-lite seems to have removed string views entirely and string span is marked for deprecation.

**Comment by JoshuaPettus** [comment]
so can there be a solution?  Your linux compile release doesn't work on fedora38 because if differing dependency versions.

**Comment by smcv** [comment]
This was probably fixed when #1154 was merged.

**Comment by Razish** [comment]
Good call, will close this one.

Please re-open if you're still having issues with gsl(-lite).

**Comment by JoshuaPettus** [comment]
Nope I'm good, JO and JK compiled fine on the last release!  Thanks everyone!
