### ISSUE TITLE
[Just a warning] OpenJO - "Where to find?!"

### ISSUE THREAD

**Issue by SilentMRG** [JACoders/OpenJK#1156]
Hello everybody!

I just want to leave a warning for those who come here looking for the OpenJO source port. It's here: https://jk2t.ddns.net/#openjo

I don't know if the OpenJK guys are responsible for the OpenJO project. I say this because I didn't see any reference to it on the main page of the repository.

"Thanks!"
You are welcome! :)

**Comment by SilentMRG** [comment]
Warning: OpenJO It's completely broken. Play the vanilla version! This is a friendly tip, believe me.

**Comment by ensiform** [comment]
Why do you think we don't include it in _our_ releases? But it's not completely broken, might be your system.

**Comment by SilentMRG** [comment]
The vanilla version worked flawlessly from start to finish. The issues I had with OpenJO are related to this: https://github.com/JACoders/OpenJK/issues/1157 And honestly, I don't think it's my system, this kind of bug is always the fault of the game or the engine. On the other hand, OpenJK is running smoothly so far. Yes, now I understand why OpenJO is not included in their releases, hehehe.

**Comment by SilentMRG** [comment]
This version: https://jkhub.org/files/file/4008-openjo-for-jedi-outcast/

It works my friends! Enjoy!
And may the force be with you! ;)
