### ISSUE TITLE
Error "Could not open string package 'CON_TEXT'"

### ISSUE THREAD

**Issue by Oldfrag** [JACoders/OpenJK#1192]
Hello!

**Operating system and version:**
Windows 11 64 bit
Latest build of OpenJK.

**Is this for single player or multiplayer?**
Single player

GOG release, game wont start with error "Could not open string package 'CON_TEXT'"

log: 

OpenJK: v1.0.1.1 win_msvc-x86 Nov 22 2023
Initialising zone memory .....
----- FS_Startup -----
Current search path:
D:\documents\My Games\OpenJO\base
D:\Games\swjk-ja\GameData\base\assets3.pk3 (16 files)
D:\Games\swjk-ja\GameData\base\assets2.pk3 (62 files)
D:\Games\swjk-ja\GameData\base\assets1.pk3 (8320 files)
D:\Games\swjk-ja\GameData\base\assets0.pk3 (15346 files)
D:\Games\swjk-ja\GameData\base

----------------------
23744 files in pk3 files
execing default.cfg
couldn't exec openjo_sp.cfg
couldn't exec autoexec_sp.cfg
Could not open string package 'CON_TEXT'

![Screenshot 2023-11-26 112630](https://github.com/JACoders/OpenJK/assets/13191269/d0d0ec46-a5fe-4a30-8436-c97163ad94cd)

**Comment by ensiform** [comment]
Looks like you're using openJO with JKA assets.

Use OpenJK with JKA assets.
