### ISSUE TITLE
Problem with cmake -DCMAKE_INSTALL_PREFIX=/path/to/GameData ..

### ISSUE THREAD

**Issue by fred260571** [JACoders/OpenJK#1193]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
FreeBSD 13.2 , Linux latest mint , MacOSX 10.13.6

**Is this for single player or multiplayer?**
Single player

**Description of the bug (and if possible, steps to reproduce the bug):**

when compiling Star Wars Jedi Knight II: Jedi Outcast Demo
cmake -DCMAKE_INSTALL_PREFIX=~/.jedi/base ..
does not work and when launching the demo , it still looks for the file in 
~/.local/share/openjo/base
which will cause problems for people owning Star Wars Jedi Knight II: Jedi Outcast
https://github.com/JACoders/OpenJK/wiki/Compilation-guide

**What did you expect to happen instead?**
For the demo to look for the assets0.pk3 in ~/.jedi/base

**Comment by ensiform** [comment]
You don't specify the base folder iirc you specify the folder above it. But it still puts stuff in /JediOutcast and /JediAcademy if you don't manually move them after since it builds both from the same tree

**Comment by xycaleth** [comment]
Specifying `-DCMAKE_INSTALL_PREFIX=~/.jedi/base` doesn't tell the game where to look for assets. It tells CMake where to install the build artifacts when you run the `install` build target.

You can set a custom search path using `fs_basepath` or `fs_cdpath` when you run the game, e.g.
```
./openjk.i386 +set fs_cdpath ~/.jedi
```
