### ISSUE TITLE
Please tell me how to install Jedi Outcast (Ubuntu arm64)

### ISSUE THREAD

**Issue by ArtemS2** [JACoders/OpenJK#1197]
Please tell me if anything needs to be compiled additionally, and where should the game files be placed?

**Comment by ArtemS2** [comment]
@foreignmeloman x86_64 applications cannot run on linux arm64. That's why I'm asking how to rebuild from source code

**Comment by ArtemS2** [comment]
I finally found it :)

Compiling OpenJO
Some users wish to compile OpenJO (Jedi Outcast) instead of just Jedi Academy. Due to possible bugs and lack of support, OpenJO compilation is disabled by default. Additionally, there is no multiplayer OpenJO build support at this time. To enable OpenJO compilation, follow these steps:

Edit CMakeLists.txt in the repository directory.
Change the BuildJK2SPEngine, BuildJK2SPGame, and BuildJK2SPRdVanilla options to ON.
Follow the 'Getting the Dependencies', 'Generating Project Files', 'Compiling', and 'Installing' sections above.
In your Jedi Outcast GameData folder, delete/move all existing files except for the base folder and version.inf.
Copy the following files from the Jedi Academy GameData to the Jedi Outcast GameData:
cgamex86.dll/so, uix86.dll/so,
SDL2.dll/so, OpenAL32.dll/so,
jospgamex86.dll/so, rdjosp-vanilla_x86.dll/so
Copy openjo_sp(.exe) from the Jedi Academy GameData to the Jedi Outcast GameData and rename it to jk2sp(.exe).

**Comment by SomaZ** [comment]
So, this seems to be resolved. Closing. If you still have issues with that, feel free to reopen the issue.
