### ISSUE TITLE
Oversized fonts in game menu

### ISSUE THREAD

**Issue by Blank99** [JACoders/OpenJK#1226]
**Operating system and version:** Windows 11, Using custom resolution of 1920x1080.
**Is this for single player or multiplayer?** SP
**Description of the bug (and if possible, steps to reproduce the bug):** the ingame menu's font describing items/weapons/force powers is too large and spills over
![image](https://github.com/JACoders/OpenJK/assets/13709902/05396038-a444-483b-9fcb-9f8bb41247d5)
EDIT: Fixed the image

**What did you expect to happen instead?** Regular font size

**Comment by ensiform** [comment]
Did you install any mods?

**Comment by Blank99** [comment]
Not at that time, tried GGFontsHQ mod and it didn't fix it. Tried JKA Font Mod Typomoderno and it did, ugly, but it does the work. Sadly, only font mod that seems to change that font so far out of a few I've tested.

**Comment by Blank99** [comment]
Checking again... I think it's using the wrong font? If I run the regular exe of the game I get in that screen a font that is not allcaps instead of the big fat menu font.

**Comment by ensiform** [comment]
> Checking again... I think it's using the wrong font? If I run the regular exe of the game I get in that screen a font that is not allcaps instead of the big fat menu font.
> 

Yes I believe it's related to a change by @Daggolin but it may be difficult to track down due to the poorly implemented menu code in SP.

Thanks for the find.
