### ISSUE TITLE
1Missing text in menu 

### ISSUE THREAD

**Issue by mihail2245** [JACoders/OpenJK#1232]
Hello. There is a problem in the game Star Wars Jedi Knight -Jedi Outcast.During startup, no text is visible in the menu, no matter how I tried to solve this situation, I tried to set the Russian language, and changed another port for it, nothing helps. In the first case, there is no text either it’s clear that the functions themselves work, and in the case of OpenJO,the game does not want to work, the required render was not found.I don't know,What will I do next? I tried to transfer the render from the first game, but when starting, the game immediately crashes on startup.Most likely I’ll try to put the second game on top of the first one and start it again. If the problem persists, I’ll continue to look for a solution. But I’m turning to you ,maybe you can help me with a solution, although without a screenshot from the game you probably won’t be able to advise me on your solution . I ask you to help me if possible, and then I will continue to look for ways to solve the problem.I use Linux Mint OS 21.3 1Version for 64bit OS

**Comment by mihail2245** [comment]
Hello.I found a solution to the problem here https://github.com/SomaZ/OpenJK/releases I downloaded the necessary render file, replaced it in the OpenJO folder, and everything worked.I advise others to try it too.

**Comment by ensiform** [comment]
Were you using openjk by accident? It only works with academy. OpenJO is for outcast SP. Also, Russian language is not listed in the support for language files for outcast.

**Comment by mihail2245** [comment]
> Were you using openjk by accident? It only works with academy. OpenJO is for outcast SP. Also, Russian language is not listed in the support for language files for outcast.

The problem has already been solved. But for OpenJO I needed a render, but there wasn’t one, because of this the game didn’t work. Using the link provided, I found the solution

**Comment by ensiform** [comment]
The renderer is provided by OpenJO, said link shouldn't be needed.

**Comment by mihail2245** [comment]
> The renderer is provided by OpenJO also, said link shouldn't be needed. Bad install perhaps.

Most likely the problem is in the game, it was downloaded from open sources

**Comment by ensiform** [comment]
No, if you saw the menu screen the renderer works. The renderer is just part of the engine in a separate module, it cannot load at all if that is missing. But you never really provided further information about the what the console said or provided screenshots or videos. Nor said which specific file fixed the issue.

**Comment by mihail2245** [comment]
Topic closed, further discussion it makes no sense, if you think I made it all up, it would be better if I attached a screenshot with the error, and then I would have opened a topic. Problem solved. Topic closed

**Comment by mihail2245** [comment]
The problem was solved on its own.

**Comment by ensiform** [comment]
I am only trying to find out why you were missing a file that you acquired "somewhere else" in the first place.

**Comment by mihail2245** [comment]
> I am only trying to find out why you were missing a file that you acquired "somewhere else" in the first place, which should have been unnecessary.

TO OpenJK The problem is not related, everything is fine there, it’s my own fault for not taking a screenshot.

**Comment by mihail2245** [comment]
Открываю для дальнейшего обсуждения

**Comment by mihail2245** [comment]
> I am only trying to find out why you were missing a file that you acquired "somewhere else" in the first place, which should have been unnecessary.

I'm an idiot, I didn't look properly at what you had OpenJO here, and didn’t check it carefully. Now I’ll need to double-check everything carefully again, I hope everything will be fine
