### ISSUE TITLE
[Warning] OpenJO - Folder path

### ISSUE THREAD

**Issue by SilentMRG** [JACoders/OpenJK#1233]
Hello everybody!

According to the error log below, OpenJO will look for a "base" folder, however, in the last binary provided in the repository, there is no folder with that name, instead, there is a folder called "OpenJK". Obviously, renaming the "OpenJK" folder to "base" will resolve the issue. 

"OpenJK: v1.0.1.1 win_msvc-x86_64 May 1 2024
Initializing zone memory.....
-----FS_Startup-----
Current search path:
C:\Users\Documents\My Games\OpenJO\base
C:\Users\Downloads\OpenJO-windows-x86_64\base

----------------------
0 files in pk3 files
Couldn't load default.cfg"

Yes, all the "pk3" files were in the directory before I started "openjo_sp.x86_64.exe". Just to make it clear.

By the way, the latest version provided is working very well, all elevators work and I'm already in Bespin without having caught any softlock. I noticed that some missing effects, such as the “energy” effect that appears on the floor (grid) of the ion cannon was restored. In another version I tested a few months ago it was absent. Thanks for the good work, guys! =D

Cheers!

**Comment by SilentMRG** [comment]
I forgot to say, I don't know if the latest OpenJK binary has this same naming mistake. I haven't tested it yet. But here's a warning for him too. ;)

**Comment by ensiform** [comment]
There is no naming mistake, you must still have the pk3s installed into the base folder

**Comment by SilentMRG** [comment]
> There is no naming mistake, you must still have the pk3s installed into the base folder

But there is no "base" folder in the binary, only "OpenJK", so, as I said earlier, renaming said folder to "base" solves the issue.

This is the root folder...

![0](https://github.com/JACoders/OpenJK/assets/62117728/45a33df7-f925-4dc6-a079-bb949168dec5)

And this is the "base"...

![1](https://github.com/JACoders/OpenJK/assets/62117728/5c5f54ce-cd78-4485-afb1-d3f657dc5512)

Is there any problem leaving that dll there in the base folder along with the pk3 files? In practice, I don't think so because I haven't seen any errors of any kind so far, hehe. Well, but you are the ones who understand these things after all. =)

I don't have Jedi Outcast installed, I just extracted the GOG offline installer with innoextract and got the "pk3" files.

**Comment by ensiform** [comment]
Yeah openjk/OpenJO so not include base folder with PK3s all ready to go, you were missing the installation of the assets prior it seems.

**Comment by SilentMRG** [comment]
Well, I just downloaded OpenJK and I saw that there is a "base" folder inside the root directory along with an "OpenJK" folder, and both folders have the same dlls, so I suggest the same: create a base folder by default in OpenJO, along with the existing folder OpenJK. This will help people like me not to get confused with nomenclatures, hehe. XD

**Comment by SilentMRG** [comment]
This may seem silly, anyway, it's just a suggestion of a directory tree on the source port, leaving both aligned. =)

**Comment by ensiform** [comment]
> This may seem silly, anyway, it's just a suggestion of a directory tree on the source port, leaving both aligned. =)

I believe the only reason OpenJK makes a base folder is because of the MP dlls are also included there since the other platforms not supported by windows jamp need something to launch. You still need to copy the base folder over as it is.
