### ISSUE TITLE
openjk on RPi5 using snap, GOG and assets

### ISSUE THREAD

**Issue by greenpdx** [JACoders/OpenJK#1237]
I am willing to buy it on GOG but on GOG it states Windows XX  but not RPI OS 2024-07-04

Can't load default.cfg

When I buy it on GOG  will that supply the necessary assets?

How do I install the assets?

**Comment by ensiform** [comment]
You install the assets from another source like gog or steam and either put the openjk files within the same directory or copy the base folder from a copy of gog/steam/windows install into wherever you decide to put your openjk install. You'll have to contact the author of snap package how that is installed, as it is not affiliated with this main repo to my knowledge.

For example I have `~/Games/jka/` and within there is the binaries from the release and them a base folder containing the pk3s from the installation assets0.pk3 and such.

**Comment by greenpdx** [comment]
So I buy the windows version and just use the assets?

**Comment by greenpdx** [comment]
On a Debian x64 host
I use wine to install the "offline" backup.
click option and set the install directory in you home directory, NOT C:
cd to 'Star Wars Jedi Knight - Jedi Academy/GameData'
scp -r base  RPi    (your RPi user@address)
ON RPi
cd ~/snap/openjk/current/.local/share/openjk
mv ~/base .

Works
