### ISSUE TITLE
Doesn't work on macOS Sequoia on M1

### ISSUE THREAD

**Issue by C-arth** [JACoders/OpenJK#1244]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
MacBook Pro 2020 M1, macOS Sequoia 15.1 

**Is this for single player or multiplayer?**
Both

**Description of the bug (and if possible, steps to reproduce the bug):**
Doesn't launch after the installation with guide. I put the log below. 
[OpenJA Sequoia.rtf.zip](https://github.com/user-attachments/files/17703078/OpenJA.Sequoia.rtf.zip)

**What did you expect to happen instead?**

**Comment by ensiform** [comment]
Looks like it's on your end. The file isn't signed because this is open source and we're not paying for that. You must make an exception to run it. Waiting for someone who currently runs on macos to explain how to override the code signing.

**Comment by C-arth** [comment]
Oh! Thank you. You helped me what to do.

**Comment by circa-III** [comment]
Since OpenJK isn't signed, you'll need to use Terminal to whitelist it.

`sudo xattr -rd com.apple.quarantine /Users/user/Applications/OpenJK.app`

You can drag and drop the app in to get the full path if you aren't sure of it.

**Comment by C-arth** [comment]
Thank you! It worked.
