### ISSUE TITLE
Graphic is broken on macOS MacBook Pro 2020 M1, macOS Sequoia 15.1

### ISSUE THREAD

**Issue by C-arth** [JACoders/OpenJK#1245]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
MacBook Pro 2020 M1, macOS Sequoia 15.1

**Is this for single player or multiplayer?**
Single 

**Description of the bug (and if possible, steps to reproduce the bug):**
Graphic is become black squares and player models are invisible. I'll put some screenshots. 
<img width="1440" alt="Снимок экрана 2024-11-12 в 1 35 56 AM" src="https://github.com/user-attachments/assets/a1da23e2-291f-4be8-97fe-bc6b30234bd9">
<img width="1440" alt="Снимок экрана 2024-11-12 в 1 35 59 AM" src="https://github.com/user-attachments/assets/dc103055-1c1a-4354-82cc-de18ed14c091">
How can I fix it?

**What did you expect to happen instead?**

**Comment by ensiform** [comment]
Screenshots are insufficient to help fix anything. Try the forums or discord before jumping to an issue that is likely solved already.

**Comment by C-arth** [comment]
Please, can you send me the link to discord server?

**Comment by C-arth** [comment]
Thank you.

**Comment by taysta** [comment]
https://github.com/JACoders/OpenJK/pull/1246 fixes this
