### ISSUE TITLE
[JO]  light in cutscenes

### ISSUE THREAD

**Issue by johndoe71rus** [JACoders/OpenJK#1250]
OpenJK: v1.0.1.1 linux-x86_64-debug Oct 27 2024
GL_VENDOR: AMD
GL_RENDERER: RAVEN (raven, LLVM 15.0.7, DRM 3.57, 6.8.0-49-generic)
lubuntu 22.04

i realize that Jedi Outcast is still beta. But i want tell about light problem in cutscenes.
this screen from apr-2023
![screen-2023-04-26-19-13-13](https://github.com/user-attachments/assets/1425a8c4-cb31-4bff-aed3-a7a5126aedb4)
and this screen actual build  OpenJK: v1.0.1.1 Oct 27 2024 
![screen-2024-11-08-21-49-11](https://github.com/user-attachments/assets/4154da0d-c49b-45f7-885c-494044aeb310)

**Comment by ensiform** [comment]
Looks like you have cg_shadows higher than 1 maybe?

**Comment by johndoe71rus** [comment]
yep
seta cg_shadows "2"
but i don't touch this.

**Comment by ensiform** [comment]
That would be what you're seeing.
