### ISSUE TITLE
Building the Jedi Outcast executable?

### ISSUE THREAD

**Issue by B-Keeper** [JACoders/OpenJK#179]
Is it just me, or it's not possible to build the JK2 engine with the project files in codeJK2? There are at least 5 errors (and about 10-15 warnings) for each file the compiler starts to build.

And besides, if the aim of the project is to "not attempt to rebalance or otherwise modify core gameplay aspects", why it was necessary to hack the JA engine to (try) to use the JK2 game DLL? (Not to mention that I still can't get it to work, it won't even load a map.)

Wouldn't the code be cleaner and easier to maintain if the JA executable would contain only JA code, and the actual JK2 executable would be mainatined and used for JK2? Or is this the ultimate goal, and this state is just temporary?

**Comment by HEXcube** [comment]
Compiling **OpenJK** for **Jedi Knight 2: Jedi Outcast** does work. However unlike @B-Keeper 's case, it's the *master* branch that builds fine for me, not @eezstreet 's *jk2hd* branch. I used **Ubuntu 12.04LTS** 64bit for building and testing. Here's what I did:

1. Downloaded the master branch https://github.com/JACoders/OpenJK/archive/master.tar.gz
2. Combining instructions from the [Compilation Guide](https://github.com/JACoders/OpenJK/wiki/Compilation-guide), Issue #273 and [Readme in the codeJK2 folder](https://github.com/JACoders/OpenJK/blob/master/codeJK2/README.md) I did these:
  * Turned on `BuildJK2SPEngine`, `BuildJK2SPGame` and `BuildJK2SPRdVanilla` options in the main *CMakeLists.txt* file
  * Ran cmake with `cmake -BuildJK2Support=ON ..`
3. `make rdjosp-vanilla_x86_64 jospgamex86_64 openjo_sp.x86_64` and got binaries **rdjosp-vanilla_x86_64.so**, **jospgamex86_64.so** and **openjo_sp.x86_64**
4. This outcast mode build uses *~/.local/share/openjo* (as opposed to *~/.local/share/openjk* for the regular build) as it's settings folder. So, I copied the pk3 file assets and **jospgamex86_64.so** to *~/.local/share/openjo/base*. **openjo_sp.x86_64** and **rdjosp-vanilla_x86_64.so** goes in *~/.local/share/openjo*. I ran **openjo_sp.x86_64** and the game seems to run well.

OpenJK team doesn't guarentee Jedi Outcast to run bug free, but for me it was worth the risk, coz I got:
* Native 64bit binary (I've been using the @xLAva 's [32bit only Linux build](https://github.com/xLAva/JediOutcastLinux) until now.
* Better engine than Outcast's stock one. (I don't know for sure, but this maybe placebo effect, :-D )
* And nothing beats running Outcast on a bleeding edge OpenJK build :-)

In addition, I tried the other method: running official buildbot build's *openjk.x86_64* binary and libraries with the outcast build libraries using `+set com_jk2 1` option, but that reproduced this issue as well as #273 for me. I'm gonna try again on **Ubuntu 14.04LTS** and let you guys know the result.

**Comment by ensiform** [comment]
You haven't been able to run it from the main SP binary for some time now.  We split it to separate exes like last summer.

**Comment by HEXcube** [comment]
>We split it to separate exes like last summer.

@ensiform Oh, I see. So, that's the reason I couldn't get Jedi Academy's binary (**openjk_sp.x86_64**) to run in Outcast mode. And the reason why it builds fine for Outcast now! :-)
But, that doesn't explain why @eezstreet 's JK2 specialized branch doesn't build. :-( Will OpenJK merge this branch into master?

**Comment by ensiform** [comment]
Nope, its not related.

**Comment by xycaleth** [comment]
To expand on @ensiform's comment, eezstreet's jk2hd branch is something he went off to pursue on his own. It was meant to be a modernized version of JK2. As our goal is to not modify any of the gameplay in JK2 or JKA, it doesn't really have a place in our code.

Regarding not being able to run openjk_sp.x86_64 in SP mode, we chose to split the JK2 and JKA SP binaries because having them combined was making the code too messy.
