### ISSUE TITLE
Broken shaders on Atlantica map

### ISSUE THREAD

**Issue by dionrhys** [JACoders/OpenJK#271]
This is an issue with Atlantica's shader file because it uses '#' character comment blocks which are not valid in a shader file.

For example:
```
####################
////// System //////
####################

textures/atlantica/atlantica_softclip
{
	qer_editorimage	textures/system/clip
	q3map_material LongGrass
	q3map_notjunc
	q3map_nolightmap
	qer_trans	0.5
	surfaceparm	noimpact
	surfaceparm	nomarks
	surfaceparm	nodraw
	surfaceparm	nonsolid
	surfaceparm	nonopaque
	surfaceparm	playerclip
	surfaceparm	monsterclip
	surfaceparm	trans
}
```

Here are some screenshots showing how this affects the map:
![shot2013-05-21_23-22-28](https://f.cloud.github.com/assets/844245/545627/1647d228-c26a-11e2-995d-dfa3c95873b7.jpg)
![shot2013-05-21_23-23-06](https://f.cloud.github.com/assets/844245/545628/16494586-c26a-11e2-99bd-b4a0f7abfa0b.jpg)
![shot2013-05-21_23-23-03](https://f.cloud.github.com/assets/844245/545629/164b9dcc-c26a-11e2-80e7-e302fab2351b.jpg)
![shot2013-05-21_23-23-16](https://f.cloud.github.com/assets/844245/545630/164da2fc-c26a-11e2-9799-c2506a2c7cd9.jpg)
![shot2013-05-21_23-23-19](https://f.cloud.github.com/assets/844245/545632/165cb51c-c26a-11e2-8a12-6d4335a2261b.jpg)
![shot2013-05-21_23-23-24](https://f.cloud.github.com/assets/844245/545633/165f478c-c26a-11e2-8b1c-d214f8164599.jpg)
![shot2013-05-21_23-21-34](https://f.cloud.github.com/assets/844245/545634/1660f352-c26a-11e2-9146-6027dd53b43e.jpg)
![shot2013-05-21_23-21-50](https://f.cloud.github.com/assets/844245/545635/167fdab0-c26a-11e2-91db-a21867fe3e7c.jpg)

The retail version of JKA handles this invalid syntax fine somehow by ignoring them, but OpenJK's new shader code chokes on it and doesn't handle the first shader it finds after a #################### line properly. This means that invalid lines will break whatever shader is supposed to come afterwards, and no warnings are given for this happening.

I'd like a discussion on whether the JKA behaviour of ignoring (liberally-parsing) bad syntax should be restored, OR if the new OpenJK behaviour of breaking the parsing could be improved by adding warnings, OR any another solution that someone thinks is better.

cc @SzicoVII

**Comment by DarthFutuza** [comment]
Was this ever resolved?  If not, I'll just add my input that shinyquagsire23 suggestion seems best as far as how to treat #### based comments.  (Console error, but ignore and compile anyway).
