### ISSUE TITLE
Text invisible in "Jedi Outcast" Menu

### ISSUE THREAD

**Issue by Xeniac-at** [JACoders/OpenJK#273]
How to reproduce:
- Install the Steam Version from Jedi Outcast
- Download and extract openjk-2013-04-14-dd3a8587.zip to the Steam Folder.
- Copy Openjk.dll and faboulous_openjk.pk3 to the "base" folder
- Thats how the main menu looks to me:
  ![sw-outcast](https://f.cloud.github.com/assets/4533931/565634/760bd5e4-c628-11e2-898c-457a2c163dd9.png)

Hardware: Intel Core 7, with ATI Radeon 5500 under Windows 7 64bit.

Becourse i've seen the mapped keys, but nothing else in the menu, i thougt that it meight hat to do with my localized version. (Im German). So i set the Steam Language to English and waited until Jedi Outcast was updated. The original started in with an english menu, but openjk won't display any text.

**Comment by protoss70** [comment]
> +set com_jk2 1 on startup.

can you be a little more spesific like do I just open the game and run the command on the command line or do something else???

**Comment by ensiform** [comment]
There is no more com_jk2 since a long time.

There is a separate executable for it which isn't included in the provided openjk builds. If I can get the link to it someone can show you where to find the prebuilt OpenJO.
