### ISSUE TITLE
Small mouse delay on Linux with Intel graphics

### ISSUE THREAD

**Issue by KaldNL** [JACoders/OpenJK#350]
Would appreciate it if any other Linux users with the open source Intel drivers could chime in here.

It's specific to OpenJK. There's a very slight but noticeable lag when moving the mouse. In some areas of a map it's more noticeable than others. Generally, the smaller the area the less the lag. I have a consistent 125 fps, so that isn't the issue. I can run other games on decent settings without this sort of lag.

Is this related to OpenJK, SDL, or the Intel Linux driver?

**Comment by mrwonko** [comment]
Has this been fixed?

**Comment by xycaleth** [comment]
Closing since this hasn't had any activity in a while. Feel free to reopen if it's still important.
