### ISSUE TITLE
No cursor in game

### ISSUE THREAD

**Issue by exander77** [JACoders/OpenJK#490]
On Ubnuntu saucy I have no cursor in game. Probably related to libsdl2?

**Comment by xycaleth** [comment]
Going to close since this hasn't seen any activity in a while. Feel free to reopen if it's still an issue!

**Comment by ddasilva** [comment]
I am running openjk in a virtual machine, and am getting this after compiling. Running ubuntu.

**Comment by Calinou** [comment]
@ddasilva Try disabling absolute mouse input in your VM ("Mouse Integration" in VirtualBox).

**Comment by ddasilva** [comment]
Thanks, that fixed it
