### ISSUE TITLE
Settings and controls cannot be saved

### ISSUE THREAD

**Issue by ghost** [JACoders/OpenJK#496]
Whenever I try changing the keyboard controls or the video settings the changes never get saved. I've also tried /writeconfig test.cfg, but the configuration is nowhere to be found.

At first, I thought that this could be a permission issue, so I chmod'ed the base directory to 777, but that didn't help. Any ideas?

**Comment by ensiform** [comment]
I'm pretty sure this is non-issue at this point. Close?

**Comment by xycaleth** [comment]
I think the commits mentioned should fix this so closing this. Feel free to reopen if it's still an issue.
