### ISSUE TITLE
100% CPU usage on Linux / need proper Sleep

### ISSUE THREAD

**Issue by mrwonko** [JACoders/OpenJK#507]
> there's also the issue of linux using 100% cpu
> see ioq3/qcommon/common.c NET_Sleep call
> we'll need to adjust our code to match that
> client-only, not dedi
> linux, i assume, but when we remove win32 specific backend it may affect windows
> the idea is to sleep inside of select(), i believe
> currently there is no sleep on linux client

~@Razish

**Comment by smcv** [comment]
I did essentially the same backport as @Razish before I found this bug and saw that you'd done it already, but my version also works in SP by using Sys_Sleep() there. It seems to work OK on Linux; no idea about Windows or Mac.

It's at https://github.com/smcv/OpenJK/tree/sleepy if you want it.

**Comment by ensiform** [comment]
com_maxfps stops working with either implementation on windows in MP.

**Comment by smcv** [comment]
Thanks, that's useful to know. I can see why you wouldn't want to merge either version while it regresses Windows.

**Comment by ensiform** [comment]
Not even sure why it happens, the only difference between us and ioq3 is that we are not yet using SDL/SDL2 on Windows but I'm not sure why exactly that would make a difference yet.

**Comment by smcv** [comment]
I'll try to reproduce it on Windows (or at least Wine) at some point, and see if I can work it out from there.

Does the sleep patch (either Razish's version or mine) work OK on Windows with "+set com_busyWait 1" on the command-line? If a per-platform default (or defaulting to 1) can make things better on Linux while not making Windows actually regress from where it is now, that'd be a start...

**Comment by ensiform** [comment]
That's the default with the patch as far as I know so I'm not sure that would help.

**Comment by smcv** [comment]
No, the default is to not busy-wait (i.e. the new way, using select/sleep, but possibly breaking Windows) in both @Razish's patch and mine:

> +       com_busyWait = Cvar_Get( "com_busyWait", "0", CVAR_ARCHIVE );

**Comment by ensiform** [comment]
Oh right, got them mixed up.

**Comment by smcv** [comment]
I've rebased https://github.com/smcv/OpenJK/tree/sleepy on the unified SDL stuff. It works on Linux, but I don't have a Windows environment - could someone try it on Windows please?

Expected results: normally, CPU usage should be high-ish (on my laptop it's ~ 70% of a CPU core) but no longer 100%. If you set some stupidly low framerate like `set com_maxfps 5`, the frame rate should drop to 5 fps, and the CPU usage should also drop.

If it doesn't work on Windows, please describe what "doesn't work" means, then try with `set com_busywait 1` which should revert to the equivalent of the old code (so, occupying 100% of a CPU core).

**Comment by ensiform** [comment]
FYI your updated patch seems to bring com_minimized and com_unfocused back into dedicated server.

Still haven't tested things yet.  Probably won't until after vacation.

**Comment by xycaleth** [comment]
I'm going through issues to re-evaluate their priority. Is this change necessarily required for milestone 1? And it certainly doesn't seem high priority to me - the game runs fine without it and I see this more as an optimization rather than a need.

It seems like a pretty big change and I don't want to risk destabilizing the code too much as we're trying to wrap up the first release.

**Comment by ensiform** [comment]
Well I would think server hosts wouldn't like servers taking up so much CPU all the time when the original isn't.

**Comment by xycaleth** [comment]
Oh right, so jampDed doesn't do busy waits either?

**Comment by xycaleth** [comment]
jampDed does do busy waits, but adds a `Sleep(5)` to avoid 100% CPU utilization. The same currently happens in OpenJK. For now I think this is fine so I'll remove this issue from milestone 1.

**Comment by smcv** [comment]
> FYI your updated patch seems to bring com_minimized and com_unfocused back into dedicated server.

Yes, ioquake3 has them in its dedicated server too. They are just never set to a non-trivial value in the dedicated server. The memory cost of a couple of cvars is low, and it seems better to have

```
    if (com_dedicated->integer) {
        /* server stuff here */
    } else {
        /* more elaborate logic involving com_minimized, com_unfocused, com_maxfps* */
    }
```

rather than

```
#ifdef DEDICATED
    /* server stuff here */
#else
    if (com_dedicated->integer) {
        /* duplicate copy of server stuff here */
    } else {
        /* more elaborate logic involving com_minimized, com_unfocused, com_maxfps* */
    }
#endif
```

or worse,

```
#ifndef DEDICATED
    if (com_dedicated->integer)
#endif
    {
        /* server stuff here */
    }
#ifndef DEDICATED
    else {
        /* more elaborate logic involving com_minimized, com_unfocused, com_maxfps* */
    }
#endif
```

I know OpenJK doesn't currently support using the client executable as a dedicated server (or at least I think I remember seeing that somewhere?), but if the logic for doing that is more or less intact, then that reduces the delta between ioquake3 and OpenJK, which seems like a win for future maintainability. (I assume you want to absorb pretty much all of the ioquake3 enhancements eventually.)

**Comment by ensiform** [comment]
Sure but it is still irrelevant for the DEDICATED preprocessor define (the separate executable) to have them as cvars which is what I was getting at.
