### ISSUE TITLE
Xinput Support 

### ISSUE THREAD

**Issue by LasagnaPie** [JACoders/OpenJK#539]
I have Jedi Academy/Outcast on Steam would like to able to launch it via Steam Big Picture with full Controller support via XInput with a controller driven UI

These games where released on consoles so those would be inspire how Controllers can be implemented, maybe even the possibility of Splitscreen and multiple controllers.

**Comment by xycaleth** [comment]
Closing this. Should be able to get full controller support via SDL - it just needs to be implemented; but we certainly won't be using XInput.
