### ISSUE TITLE
3840x2160 resolution results in distorted menu and unplayable game

### ISSUE THREAD

**Issue by chrismartinau** [JACoders/OpenJK#559]
When setting the custom resolution to 3840x2160, the main menu appears HUGE, with most of it not visible, off-screen.

My rig is as follows:
R9-290X - Catalyst 14.6 Beta drivers (tried with crossfire disabled and enabled with secondary R9-290)
Windows 8.1
openjk-2014-06-23-8c620db3-windows
JK:JA from steam

Happens if either the conf file is edited:
seta r_customheight "2160"
seta r_customwidth "3840"
seta r_mode "-1"

Or if I do it from the console with a standard res selected:
r_mode -1
r_customwidth 3840
r_customheight 2160
vid_restart

Am I doing something wrong?

**Comment by mrwonko** [comment]
Is this still an issue?

I'm half-tempted to get a 4K screen...

**Comment by xycaleth** [comment]
Seems fixed...
