### ISSUE TITLE
Quicksaves won't load in JK2

### ISSUE THREAD

**Issue by grepwood** [JACoders/OpenJK#585]
Saving game "quik*"...
Done.
Loading... quik
Failed to open savegame 'quik'

From code/ui/ui_shared.cpp:5388 I gathered that it literally saves it as "quik*.sav", and then code/ui/ui_main.cpp:1467 tries to load a "quik.sav" which doesn't exist.
Since game saves are already stored in ~/.local/share/$GAME/base/saves, why would the quicksave name be different in JK2?

**Comment by ensiform** [comment]
Pretty sure they work just fine.  Close?

**Comment by ensiform** [comment]
Sounds like you were using an older jk2 quicksave from before the changes took place really.

**Comment by grepwood** [comment]
I'll try to check this next week. At the moment I'm pretty sure that my quicksave was generate by the same version of jk2 that I was trying to load it with.

**Comment by ensiform** [comment]
Make sure you don't have a quicksave under fs_basepath that it might be loading too.  It may load from there first.

**Comment by ensiform** [comment]
This should be fixed now with #878 and bb0b2f0a541117aba77fc7b59ee51defda99a5b6

Note: there's no up to date windows prebuilt build currently.

**Comment by grepwood** [comment]
@ensiform I will rebuild OpenJK this weekend and see if I can confirm everything.

**Comment by grepwood** [comment]
Confirmed. Works fine.
