### ISSUE TITLE
MAX_PATCH_PLANES gets hit on some maps that didn't in jasp or jamp

### ISSUE THREAD

**Issue by ensiform** [JACoders/OpenJK#589]
This error happens upon loading some maps in MP or SP OpenJK engine but did not happen in original.

Known maps: jedicouncil_gcx

Mostly posting issue for reference. Thread on jkhub has more details.

**Comment by xycaleth** [comment]
One way of fixing this would be to disable SSE2, but x64 builds would still exhibit the problem because SSE2 cannot be disabled (as far as I know). We really need a way to fix the problem, regardless of the instruction set that's used.

**Comment by ensiform** [comment]
It also happens in a couple of 3rd party maps in ioquake3 too.  And I don't think they use sse2 or any SSE flags in the make file.

**Comment by xycaleth** [comment]
I'm absolutely sure that you won't hit the problem if you aren't using any MMX/SSE instructions.

**Comment by ensiform** [comment]
Mingw or GCC is probably defaulting it then.

**Comment by ensiform** [comment]
I think I only tested x86_64 ioq3 though hmm.
