### ISSUE TITLE
uiInfo.playerSpecies is 60MB in size

### ISSUE THREAD

**Issue by xycaleth** [JACoders/OpenJK#599]
MAX_PLAYERMODELS was increased from 32 to 512 at some point which has caused uiInfo.playerSpecies to grow from 2-3MB to ~60MB in size.

**Comment by xycaleth** [comment]
Best solution I can think of would be to dynamically allocate the array so we only have the amount we need.

**Comment by ensiform** [comment]
Fixed in 10cf89f0f6b640ae13766aa56383dac590a95600 df85f840fa563c64d65c76eaff4680105e024ae5 and 61499d87c2e414e373e6c3d724c4736b3cd6adfb
