### ISSUE TITLE
Add new syscalls to check for engine type

### ISSUE THREAD

**Issue by A-t48** [JACoders/OpenJK#608]
Hi, Subaru here. In some cases (patching the engine at runtime, mainly) it is useful to know what engine we are running (mostly if it is retail or not, but there are other instances, too).

I'd like to add TRAP_GETENGINE and TRAP_GETENGINEVERSION to the list of syscalls, replacing TRAP_TESTPRINTFLOAT and TRAP_TESTPRINTINT which do nothing.

trap_GetEngine would return a const char* representing the engine name ("OpenJK" in this case, "jaMME" for jamme, something else for thoughtful people who fork and pay attention). On baseJKA if it is called it will return null, so no issue there.

trap_GetEngineVersion would return a string version that is up to the engine maker (semantic versioning would be preferred).

Why not add new traps to the end? Well, in base it will cause needless errors and returns an ugly -1. 

In any case, I have no problem with creating a patch to do this, but I wanted to make sure that the work would be accepted before I did it.

**Comment by EpicLoyd** [comment]
eeeem, there is another way to check it, if engine uses new api (not syscalls ) then its ojk, if it use syscalls then jamp.

**Comment by A-t48** [comment]
What other api? How can I check for it?

**Comment by A-t48** [comment]
Context: I'm running in mod code, linked to the original engine.

**Comment by EpicLoyd** [comment]
if you are querying modification using vmMain function ( cg/g_main.c  ) then, it uses legacy api ( jamp ) . if you are querying modification using GetModuleAPI function, then it uses new api (OpenJK ). 
```C

int enginetype = 0; /// Define it somewhere



Q_EXPORT gameExport_t* QDECL GetModuleAPI( int apiVersion, gameImport_t *import ) { //// If Module API ( OpenJK )
   .....
   .....
 enginetype = 1; //OpenJK
}

(or)

Q_EXPORT intptr_t vmMain( int command, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4,
	intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11 ) {  /// If vmMain ( JaMP)
   .....
   .....
enginetype = 2; //JaMP
}

```

**Comment by eezstreet** [comment]
Just check the "version" cvar. If it's the same as baseJKA, then you know you're working with base.

Date: Sat, 3 Jan 2015 18:08:34 -0800

**Comment by ensiform** [comment]
Basically what eezstreet said.

If dllEntry or vmMain are accessed, then its an older engine.
Or if GetModuleAPI is accessed, then its OpenJK.

**Comment by A-t48** [comment]
Did not know about the version cvar, thanks. That is exactly what I wanted.

**Comment by A-t48** [comment]
![Ummm](http://i.imgur.com/nctnmN3.png)

**Comment by A-t48** [comment]
Can we make that say openJK?

**Comment by Razish** [comment]
No, for compatibility issues.

Instead of relying on the version cvar or an engine function that may or may not exist, it is more reliable to do a checksum of the engine in memory to know for sure that the code you're trying to patch is the same as base.

**Comment by A-t48** [comment]
It was going to be in addition to checking some bytes in memory. What kind of compatibility problems would be caused by changing that cvar?

**Comment by ensiform** [comment]
Some older tools like the all seeing eye break and you won't see servers if it doesn't say JAmp: v1.0.1.0

**Comment by A-t48** [comment]
Can we tack on [OpenJK] at the end? _that_ shouldn't break anything.

**Comment by ensiform** [comment]
Why do you need it?

Check the year.

**Comment by xycaleth** [comment]
@A-t48 Can we close this issue now? I think the issue's been solved now.
