### ISSUE TITLE
vid_restart while the game is running a map will cause a crash in SP

### ISSUE THREAD

**Issue by ensiform** [JACoders/OpenJK#609]
Using vid_restart while a map is loaded (game module loaded) in SP will likely cause a crash in one of the many renderer functions being used in the game code.

Mostly posting for reference. @xycaleth can add to this mebbe.

Caused by modular renderer.

**Comment by xycaleth** [comment]
So my first guess is that the game module needs to be updated with new function pointers for the renderer on `vid_restart`.
