### ISSUE TITLE
Eent-files for external map entities

### ISSUE THREAD

**Issue by keyten** [JACoders/OpenJK#612]
Load entities from mapentities/mapname.eent in addition to loading them from the .bsp file.

Like in the redsaurus SP Customization Mod: http://jkhub.org/topic/2480-sp-customisation-stuff/?p=75158

**Comment by ensiform** [comment]
Was this originally taken from rtcwcoop ? They have eents files support too. But its GPLv3.

**Comment by xycaleth** [comment]
Seems like a neat feature to have. It should be easy enough to add without source code tbh so licensing issues aren't a problem.

**Comment by ensiform** [comment]
I just was clarifying if that was where red took it from or not.

Yes its easy, I did it years ago and as have some other older mods.

Could probably also extend Icarus to spawn entities maybe as well.

**Comment by redsaurus** [comment]
Was from scratch https://github.com/redsaurus/OpenJK/commit/8cc21f9761cb6a2b0502ea6ce4db35f6fd541d6c

**Comment by ensiform** [comment]
How's this look for MP?

http://slexy.org/raw/s2K3ibD6Fr

Not tested.

**Comment by dionrhys** [comment]
I've merged something similar to this in #674. The engine will now load a .ent file for the map if one exists **instead** of the BSP's entities. Allowing the entire list of entities to be overriden allows addition and removal of BSP entities and their properties, as opposed to only the addition of entities covered in this issue.

Mods are still free to implement their own entity loading systems in gamecode.
