### ISSUE TITLE
JA++ No longer working

### ISSUE THREAD

**Issue by glimpee** [JACoders/OpenJK#617]
So I started JA yesterday, got JA+ and JA++ (++ onlyworked once I got JA+) and Ive been loving it, playing 1st person staff, but I tried to login today - and ja++ is no longer working! Custom saber colors are gone - I can see people while Im dueling - and no first person.

I dont know much about computers, but I have openjk, ja+ and ++, and I think I followed all the guides

**Comment by ensiform** [comment]
This has absolutely nothing to do with OpenJK.
