### ISSUE TITLE
r_overbrightbits 1 = black

### ISSUE THREAD

**Issue by Boothand** [JACoders/OpenJK#624]
Turning it on, and doing vid_restart results in a mostly black map:

![shot2015-02-08_17-16-23](https://cloud.githubusercontent.com/assets/5933597/6099172/e139ffa8-aff1-11e4-863b-2015a7511400.jpg)

**Comment by ensiform** [comment]
Does not happen here, also duplicatae of #390

**Comment by xycaleth** [comment]
@Boothand How recent is your build of OpenJK?

**Comment by ensiform** [comment]
OS ? Graphics card / vendor / driver ?

**Comment by Boothand** [comment]
That was the latest build, from the same day or the day before as the day I posted it. Was running fullscreen. Windows 8, Nvidia Geforce GTX 780, latest drivers (not sure about specific drivers there).

**Comment by xycaleth** [comment]
@Boothand Are you still having these issues?

**Comment by Boothand** [comment]
Yes, still black with overbrightbits in fullscreen (latest build)

**Comment by xycaleth** [comment]
Can you post your openjk.cfg file somewhere (slexy/pastebin) please? The one in `My Games/OpenJK/<mod folder>/`.

**Comment by Boothand** [comment]
https://dl.dropboxusercontent.com/u/58757568/openjk.cfg

**Comment by xycaleth** [comment]
@Boothand Can you try running OpenJK with the above commit? I think I've fixed the issue but I'm not sure!

**Comment by Boothand** [comment]
Could I have a windows build? I don't have time to get into compiling it at the moment..

**Comment by xycaleth** [comment]
Sure, I'll try and get a build for you tonight (in about 3 hours).

**Comment by xycaleth** [comment]
@Boothand Try this:

https://dl.dropboxusercontent.com/u/874909/openjk.zip

**Comment by Boothand** [comment]
Seems to be fixed now :)

**Comment by xycaleth** [comment]
Thanks for testing @Boothand  =]
