### ISSUE TITLE
VM_CreateLegacy on ui failed

### ISSUE THREAD

**Issue by Thandriel** [JACoders/OpenJK#631]
Hi, I'm trying to run OpenJK on my Ubuntu 14.10 x64. And when i try to run openjk.x86_64 in my Game Data folder it throws error: recursive error after: VM_CreateLegacy on ui failed. And when i try to start a level in openjk_sp.x86_64 the game throws: Failed to load jagame library (but does not crash :) ).

Here is crashlog:

>tty console mode disabled
>OpenJK-MP: v1.0.1.0 linux-x86_64 Feb  8 2015
>----- FS_Startup -----
>Current search path:
>/home/than/.local/share/openjk/base
>/home/than/Downloads/Jedi Academy/GameData/base/assets3.pk3 (16 files)
>/home/than/Downloads/Jedi Academy/GameData/base/assets2.pk3 (62 files)
>/home/than/Downloads/Jedi Academy/GameData/base/assets1.pk3 (8320 files)
>/home/than/Downloads/Jedi Academy/GameData/base/assets0.pk3 (15346 files)
>/home/than/Downloads/Jedi Academy/GameData/base
>
>----------------------
>23744 files in pk3 files
>execing mpdefault.cfg
>couldn't exec openjk.cfg
>couldn't exec autoexec.cfg
>----- Initializing Renderer ----
>Trying to load "rd-vanilla_x86_64.so" from "/home/than/Downloads/Jedi Academy/GameData"...
>QKEY building random string
>QKEY generated
>SDL using driver "x11"
>Initializing display
>Display aspect: 1.779
>...setting mode 4: 800 600
>Using 24 color bits, 24 depth, 8 stencil display.
>Available modes: '1366x768 1360x768 640x480 800x600 1024x768'
>GL_RENDERER: Mesa DRI Intel(R) Sandybridge Mobile 
>Initializing OpenGL extensions
>...GL_S3_s3tc available
>...GL_EXT_texture_compression_s3tc available
>...no tc preference specified
>.....using GL_EXT_texture_compression_s3tc
>...using GL_EXT_texture_env_add
>...GL_EXT_texture_filter_anisotropic available
>...using GL_EXT_texture_filter_anisotropic
>...using GL_EXT_texture_edge_clamp
>...using GL_ARB_multitexture
>...using GL_EXT_compiled_vertex_array
>...GL_NV_register_combiners not found
>
>GL_VENDOR: Intel Open Source Technology Center
>GL_RENDERER: Mesa DRI Intel(R) Sandybridge Mobile 
>GL_VERSION: 3.0 Mesa 10.3.2
>GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_clear_buffer_object GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_conditional_render_inverted 
>GL_MAX_TEXTURE_SIZE: 8192
>GL_MAX_TEXTURE_UNITS_ARB: 8
>
>PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
>MODE: 4, 800 x 600 windowed hz:N/A
>GAMMA: hardware w/ 0 overbright bits
>rendering primitives: single glDrawElements
>texturemode: GL_LINEAR_MIPMAP_NEAREST
>picmip: 0
>texture bits: 0
>lightmap texture bits: 0
>multitexture: enabled
>compiled vertex arrays: enabled
>texenv add: enabled
>compressed textures: enabled
>compressed lightmaps: disabled
>texture compression method: GL_EXT_texture_compression_s3tc
>anisotropic filtering: enabled  (16 of 16)
>Dynamic Glow: disabled
>
>------- sound initialization -------
>SDL_Init( SDL_INIT_AUDIO )... OK
>SDL audio driver is "pulseaudio".
>SDL_AudioSpec:
>  Format:   AUDIO_S16LSB
>  Freq:     44100
>  Samples:  512
>  Channels: 2
>Starting SDL audio callback...
>SDL audio initialized.
>----- Sound Info -----
>    1 stereo
>16384 samples
>   16 samplebits
>    1 submission_chunk
>44100 speed
>0x49230c0 dma buffer
>No background file.
>----------------------
>------------------------------------
>
>--- ambient sound initialization ---
>Sound memory manager started
>Sys_LoadGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>VM_Create: uix86_64.so failed!
>Sys_LoadLegacyGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadLegacyGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadLegacyGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadLegacyGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>VM_CreateLegacy: uix86_64.so failed!
>*******************
>ERROR: VM_CreateLegacy on ui failed
>********************
>
>GL_VENDOR: Intel Open Source Technology Center
>GL_RENDERER: Mesa DRI Intel(R) Sandybridge Mobile 
>GL_VERSION: 3.0 Mesa 10.3.2
>GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_clear_buffer_object GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_conditional_render_inverted 
>GL_MAX_TEXTURE_SIZE: 8192
>GL_MAX_TEXTURE_UNITS_ARB: 8
>
>PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
>MODE: 4, 800 x 600 windowed hz:N/A
>GAMMA: hardware w/ 0 overbright bits
>rendering primitives: single glDrawElements
>texturemode: GL_LINEAR_MIPMAP_NEAREST
>picmip: 0
>texture bits: 0
>lightmap texture bits: 0
>multitexture: enabled
>compiled vertex arrays: enabled
>texenv add: enabled
>compressed textures: enabled
>compressed lightmaps: disabled
>texture compression method: GL_EXT_texture_compression_s3tc
>anisotropic filtering: enabled  (16 of 16)
>Dynamic Glow: disabled
>Sys_LoadGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>VM_Create: uix86_64.so failed!
>Sys_LoadLegacyGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadLegacyGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadLegacyGameDll(/home/than/.local/share/openjk/base/uix86_64.so) failed: "Failed loading /home/than/.local/share/openjk/base/uix86_64.so: /home/than/.local/share/openjk/base/uix86_64.so: cannot open shared object file: No such file or directory"
>Sys_LoadLegacyGameDll(/home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so) failed: "Failed loading /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: /home/than/Downloads/Jedi Academy/GameData/base/uix86_64.so: cannot open shared object file: No such file or directory"
>VM_CreateLegacy: uix86_64.so failed!
>recursive error after: VM_CreateLegacy on ui failed

Edit: I'm using: openjk-2015-02-09-366933d5-linux-64 build (I've tried few older ones with same results)

**Comment by ensiform** [comment]
This is not something to make a github issue about.

Please copy the so files from within the build to base folder from OpenJK mod folder if you have these issues.
