### ISSUE TITLE
russian language doesnt works in last version from 10.02.2015

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#632]
Operating System:
windows 7/8.1

SP/MP:
MP

What the problem is:
Russian translation looking like this: 
https://www.dropbox.com/s/zqru0bjwcjjshwl/shot2015-02-17_00-04-02.jpg?dl=0
https://www.dropbox.com/s/r3klf3y2kdt27t2/shot2015-02-17_00-03-52.jpg?dl=0
I'm using this translation pack https://www.dropbox.com/s/swkqbaiidbl6lq0/JErus.pk3?dl=0 as usual. It's also doesnt look like random characters (you know, like an error) without translation pack, just the same things (numbers and so on).

**Comment by ensiform** [comment]
Probably because of SDL, is translating to utf8 internally.

Unlikely to be fixed anytime soon.

**Comment by dionrhys** [comment]
Can you provide the actual Cyrillic characters you tried to type there? It looks like keyboard mashing instead of typing coherent words because of the pattern of characters.

**Comment by ensiform** [comment]
It's already a known issue that SDL fucks up dead keys by not using WM_CHAR

**Comment by sudge** [comment]
![shot2015-04-07_14-38-10](https://cloud.githubusercontent.com/assets/10692765/7019674/5fa61524-dd34-11e4-8088-50154de9b077.jpg)
![alph](https://cloud.githubusercontent.com/assets/10692765/7019673/5fa60c96-dd34-11e4-808c-ea953502ffa4.png)
All russian characters missing one red marked, it didnt work on base jamp too.
And if can, please mark somehow early versions with russian support, it is important because there is huge community of russian players need this.

**Comment by ensiform** [comment]
People will have to download the font fix.  Again, no distribution of assets is permitted legally among other reasons.

**Comment by xycaleth** [comment]
I'm considering fixing this issue for first release. It will delay the first release but it's worth it seeing as a lot of players are not English or American.

**Comment by xycaleth** [comment]
I've looked further into fixing this, and it's not too difficult to fix. Just time consuming. Text input events generated by SDL give us the UTF-8 encoded character, which we convert to UTF-32. Originally, JA would receive text input events (or its equivalent in Windows land) with the character encoded under the current keyboard layout's natural character encoding. e.g. for Russian, this would be Windows-1251, for Polish this would be Windows-1250, for Chinese this would be Big-5, and so on...

So to fix this, we can map the UTF-32 character to it's equivalent character code and encoding. Basically, we need a big table/hash map.

**Comment by xycaleth** [comment]
Fix for Russian and Slavic characters is in b1e5a37

**Comment by EpicLoyd** [comment]
thanks

**Comment by xycaleth** [comment]
Going to mark as fixed... I'm not aware of any players using the languages which aren't fixed yet so that can be done after the first release I think.
