### ISSUE TITLE
Lighting messed up in mission select

### ISSUE THREAD

**Issue by Cerezk** [JACoders/OpenJK#636]
It seems the lighting source is incorrectly moving around on Luke and Kyle on the mission select screens, in the communications window. 

The light in the original game seems to have a direct overhead position, while in OpenJK it is radically jumping around, causing strange shadow effects on the faces. 

Discussion, screenshots, and details here: 
http://jkhub.org/topic/5441-mystery-shadow/

**Comment by xycaleth** [comment]
I suspect it's to do with this line here:
https://github.com/JACoders/OpenJK/blob/master/code/ui/ui_shared.cpp#L7231

@Cerezk Can you try replacing that line with:
```ent.renderfx = RF_NOSHADOW;```
And see if you still get the issue.

That's what the line was originally before any changes.

**Comment by Cerezk** [comment]
Yes! That's it. That's what was messing up the lighting/shadows in the communications window. I can confidently confirm that this fix works indeed. Thank you.
