### ISSUE TITLE
r_gamma affects entire screen

### ISSUE THREAD

**Issue by xycaleth** [JACoders/OpenJK#637]
Setting `r_gamma` affects the entire display as setting the gamma ramp affects the display owning the game window. To improve this, we could apply the gamma correction ourselves in the renderer as a "post processing" step so that it only affects the rendered image, instead of the whole display.

For the vanilla renderer, we would need to check for availability of ARB shaders (should be available on every PC nowadays), and then apply the gamma correction in a pixel shader. Steps to take:

1. Copy back buffer to texture using `glCopyTexImage2D`.
2. Draw texture to screen as full-screen quad, applying pixel shader to gamma correct the texture.

**Comment by sudge** [comment]
I have an application which can fix gamma without system reboot. https://www.dropbox.com/s/6icc005yj0ilria/fixgamma.rar?dl=0 fixgamma.exe in archive. I have no idea about virus check, you can try yourself.
