### ISSUE TITLE
about something havent done at the moment

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#638]
Operating System:
I think whatever 

SP/MP:
whatever, more MP

What the problem is:
1) Well, talking about people who are not such as IT specialist or something like that. Some of them really need included instruction about what to do with files in achve, I know there is instructions on github page, but people often just miss it. People dont know how to run the game as portable (configs in the game folder), they dont know how to make executable file to run some modification. So what about just a little instruction in txt file included in achive? Just write as "for stupid", some people really need it. Or maybe some *.bat of *.sh (depends on platform) to run the game in portable mode. Plus some people really looking for installer, they just use to things like that.
2) Still have no folders support in demo list. Can it be done?
3) Can't pick black character color anymore. What is the code? It was 256 256 256 in original JAMP, but I tried 256 256 256, 0 0 0, 00 00 00, and so on, nothing just works. 
4) Have no any speedometer ingame. Somewhere speed is changes, but I cant look at that. 
5) No scores in duel using "cg_hudfiles 1" https://www.dropbox.com/s/xl5ldcaoofl2syj/scores.png?dl=0
6) No forcemodel for allies/enemies/yourself separated.
7) About r_picmip. With 16 it disable textures completely, but the same for SABERS. I think no one would like that https://www.dropbox.com/s/1n4akljgcwh505j/Screenshot_1.png?dl=0 

I am using this file to fix it https://www.dropbox.com/s/lw21h4zcz6hhfxc/AAA_nopicmip.pk3?dl=0 but it's already modification. It is looking like that https://www.dropbox.com/s/ks274haf2ugt7p7/Screenshot_3.png?dl=0 and also it is going to be another problem (on the screen) https://www.dropbox.com/s/e82ii5a7nw6m25s/Screenshot_4.png?dl=0 BUT any modificated console background, e.g. this one https://www.dropbox.com/s/gl5wge42teg5al0/hud_transp_console.pk3?dl=0 looking just fine https://www.dropbox.com/s/jgt9abwnxackcad/Screenshot_5.png?dl=0 and also fixes the entire problem of console background in the original JAMP (too dark and not tranparent background, hard to see black color and something like that).

Can it be done as default function? It seems fair enough. 

Same things to separated picmip for player textures and map textures, it is already exist in Sil's mod, but it is just useful itself for players who want to disable map textures for performance or simpify. 

Thank you.

**Comment by Razish** [comment]
You should really make separate issues for these.

> Well, talking about people who are not such as IT specialist or something like that. Some of them really need included instruction about what to do with files in achve, I know there is instructions on github page, but people often just miss it. People dont know how to run the game as portable (configs in the game folder), they dont know how to make executable file to run some modification. So what about just a little instruction in txt file included in achive? Just write as "for stupid", some people really need it. Or maybe some *.bat of *.sh (depends on platform) to run the game in portable mode. Plus some people really looking for installer, they just use to things like that.

This will all be handled with an official release and website, nothing to worry about here. Up until now it's mostly been preview builds that get frequently updated for people who are curious, so it was up to them to work out how to use the files. If they couldn't work that out, it's probably not suitable for them.

> 2) Still have no folders support in demo list. Can it be done?

It can be done. Not sure if it will be done. Pull requests are welcome.

> 3) Can't pick black character color anymore. What is the code? It was 256 256 256 in original JAMP, but I tried 256 256 256, 0 0 0, 00 00 00, and so on, nothing just works.

The original method was to use 256,256,256, which abused integer overflow. That bug was fixed and a server-side cvar was added to allow `r+g+b < 100`  - I think it was `g_charRestrictRGB`

>4) Have no any speedometer ingame. Somewhere speed is changes, but I cant look at that. 

I don't think OJK will add a speedometer. It's not a commonly desired feature, and it's left up to a mod to implement.

> 6) No forcemodel for allies/enemies/yourself separated.

Again, up to a mod to implement.

> 7) About r_picmip. With 16 it disable textures completely, but the same for SABERS. I think no one would like that https://www.dropbox.com/s/1n4akljgcwh505j/Screenshot_1.png?dl=0
I am using this file to fix it https://www.dropbox.com/s/lw21h4zcz6hhfxc/AAA_nopicmip.pk3?dl=0 but it's already modification. It is looking like that https://www.dropbox.com/s/ks274haf2ugt7p7/Screenshot_3.png?dl=0

Best done in a PK3 with shaders

> and also it is going to be another problem (on the screen) https://www.dropbox.com/s/e82ii5a7nw6m25s/Screenshot_4.png?dl=0 BUT any modificated console background, e.g. this one https://www.dropbox.com/s/gl5wge42teg5al0/hud_transp_console.pk3?dl=0 looking just fine

Sounds like interfering PK3, not up to OJK to "fix"

> Same things to separated picmip for player textures and map textures, it is already exist in Sil's mod, but it is just useful itself for players who want to disable map textures for performance or simpify.

This is better done in a separate PK3 with shaders.

**Comment by xycaleth** [comment]
> 2) Still have no folders support in demo list. Can it be done?
Do you mean navigating folders? Or for the game to search for demos in folders? The latter already exists in the OpenJK mod code. Existing mods would have to be changed to support it.

**Comment by sudge** [comment]
>

**Comment by sudge** [comment]
>You should really make separate issues for these.
OK
>The original method was to use 256,256,256, which abused integer overflow. That bug was fixed and a server-side cvar was added to allow r+g+b < 100 - I think it was g_charRestrictRGB
so how to make black? 
>Best done in a PK3 with shaders
There is no any problem using .pk3 exept stupid sv_pure block everything and kick players from the server for having custom maps in base folder. So it is the problem. I cant use .pk3 with sv_pure 1.

**Comment by sudge** [comment]
>Do you mean navigating folders?

Yes, navigating folders in "demos" folder. It's not comfort much if you have 100 demos just in one list.

**Comment by Razish** [comment]
> so how to make black?
Use 0 0 0 on a server that allows it.

**Comment by ensiform** [comment]
So don't play on sv_pure servers.

**Comment by sudge** [comment]
>Use 0 0 0 on a server that allows it.

Can it be controled some way from the server configuration?

>So don't play on sv_pure servers. It protects against nothing.

Sure, it is, but there is no any duel/tffa server without sv_pure 1, that's the thing. 
Okay, thanks a lot anyway for response. If you have any solution for this or any other idea what to do, please let me know about it.

**Comment by xycaleth** [comment]
> >Use 0 0 0 on a server that allows it.

> Can it be controled some way from the server configuration?

Yes, you can set the `g_charRestrictRGB` cvar to `0` to allow black. The default value is `1`.

**Comment by sudge** [comment]
Okay, solved, thank you!
