### ISSUE TITLE
Still no any aspect ratio settings

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#653]
Not depends on version and operating system I believe. Havent find any aspect ratio settings ingame, so if I have e.g. 24" widescreen monitor and videomode of 1280x1024 it will be stretched to full widescreen by default and it cannot be turn into black frames and squre by the game option. Instead of it you should check videodapter driver settings or harware monitor setting to get it. Square resolution is still the best for multiplayer and there are many standart videomodes with square resolution.

**Comment by ensiform** [comment]
The menus are not changing in OpenJK. How much more clear does it have to be that assets are not being modified by this project.

Use the console or configuration file like always.

As far as proper hud aspect etc, it can be done but not universally across all mods and will definitely look weird/broken with fonts if using a non-fixed mod as well.

**Comment by ensiform** [comment]
The OpenJK cgame mod code already fixes the aspect ratio problem for fov FYI. SP too.

I forget the full cvar names off the top of my head but a quick auto completion with tab and cg_fov will probably show the options.

**Comment by xycaleth** [comment]
Unfortunately as @ensiform says, we can't provide modified menus with OpenJK as the menu files are not covered under a GPL-compatible license.

With the OpenJK mod, you can set `cg_fovAspectAdjust` to `1` using the console to avoid the 3D rendering from stretching. Note however, that this doesn't fix the HUD rendering from stretching.

**Comment by sudge** [comment]
![16042015019](https://cloud.githubusercontent.com/assets/10692765/7175974/d92c941e-e43b-11e4-9654-d456f9b11572.jpg)

This is aspect ratio I am talking about, it seems this is the only way I can show you. But this one by monitor settings, not ingame. No any problem with FOV so far.

**Comment by ensiform** [comment]
Should stretch regardless.  The game has always drawn in virtual 640x480.

**Comment by sudge** [comment]
Well, not such a bit problem anyway, closed.
