### ISSUE TITLE
little problem with character encoding

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#654]
![screenshot_3](https://cloud.githubusercontent.com/assets/10692765/7176381/b11136ac-e43f-11e4-9e5d-688c1cdb5fc5.png)

Latest build from 14.04. These keys have the same character in the russian layout, but in fact, as you can see, they are different. I thought it maybe only my laptop keyboard, but I plug usual USB keyboard and have the same result. Same character Ж with translation pack and some unknown character without it.

**Comment by xycaleth** [comment]
Thanks for reporting the bug. It looks like there's a small bug in the code here:

https://github.com/JACoders/OpenJK/blob/master/shared/sdl/sdl_input.cpp#L662

It should be returning 240 instead of 230. I'll fix ASAP unless someone else gets to it first.

**Comment by ensiform** [comment]
http://hg.libsdl.org/SDL/rev/02273530b7bf Might affect things differently in 2.0.4
