### ISSUE TITLE
cl_noprint 1 affects cvar result showing in console

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#656]
MP, probably SP too, not depends on OS I guess. Well, after cl_noprint 1 there is no showing result of type any cvar in console. Let it be com_affinity, so it shows only clear space/nothing. Any setting is the same result.

**Comment by ensiform** [comment]
That's intended.

**Comment by ensiform** [comment]
If you are looking to just hide the text at top of screen while the console is not open, you can just do con_notifytime -3.

**Comment by sudge** [comment]
Thank you, I will try it.

**Comment by ensiform** [comment]
Should work.

**Comment by sudge** [comment]
It's fine!
