### ISSUE TITLE
demo stop recording when sever changing the map

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#657]
MP. Says it all. I correctly remember having demos which changing the map. So now it just stop recording.

**Comment by ensiform** [comment]
No they didn't.

And its intentional so you don't get unnecessary map loads at the end of demo anyway.

**Comment by ensiform** [comment]
Basically everyone uses per map demos anyway.  It would serve little purpose to have it be multiple map based, especially with the fact that file names are defaulted with date/time and map(?)
