### ISSUE TITLE
Binding keys to alt produces Windows alert sound

### ISSUE THREAD

**Issue by Razish** [JACoders/OpenJK#664]
I have `+moveup` bound to alt and when I then try to press a movement key (any key, really) I get a Windows alert sound and the cursor flickers on/off.

Issue exists since SDL2 migration, and only occurs on Windows.

**Comment by ensiform** [comment]
SDL2 issue won'tfix until they apply my patch.

**Comment by ensiform** [comment]
See https://bugzilla.libsdl.org/show_bug.cgi?id=2669

**Comment by ensiform** [comment]
Fixed in SDL hg newest for 2.0.4

**Comment by mrwonko** [comment]
We now use SDL 2.0.4 - is this fixed?

**Comment by Razish** [comment]
I've not verified it myself, but have had two people confirm it working on 2.0.4

**Comment by ensiform** [comment]
Yeah I've been using the latest sdl locally with the fix for some time.  Confirmed.
