### ISSUE TITLE
Problem with accent

### ISSUE THREAD

**Issue by Yberion** [JACoders/OpenJK#669]
Since SDL2 we can't use this accent ^, making "ê" will result in game to ^e.

**Comment by xycaleth** [comment]
What keyboard layout are you using?

**Comment by xycaleth** [comment]
Nevermind, I've managed to reproduce the problem. I'm assuming you're using a French AZERTY keyboard, and typing ^ and then e to get a ê :)

**Comment by xycaleth** [comment]
This is a bug in SDL2 (https://bugzilla.libsdl.org/show_bug.cgi?id=2834) and looks like it will be fixed for SDL 2.0.4.

**Comment by Yberion** [comment]
Ok good to hear, thanks for your answer :)

**Comment by ensiform** [comment]
Fix was applied on June 25th to SDL2 Pending 2.0.4 release.

http://hg.libsdl.org/SDL/rev/02273530b7bf

**Comment by Yberion** [comment]
Good, thank you

**Comment by mrwonko** [comment]
We now use SDL 2.0.4 - is this fixed?

**Comment by ensiform** [comment]
Should be

**Comment by mrwonko** [comment]
Yup, works properly now.
