### ISSUE TITLE
BUILD PROBLEMS

### ISSUE THREAD

**Issue by Brownjor10** [JACoders/OpenJK#670]
I am trying my damnedest to create a personal build, based off of the current source code.  I've used the guide and Visual Studio 2013 with CMake.  When I compile I always get a cmd.exe error, as well as a bunch of warnings...  but it makes the exe.  But when I get in game, new models can't spawn and lightsabers don't turn on.  I'm really lost here!  

SIDE NOTE:  If you guys could raise the Single Player NPC Limit to 0x80000 from 40000, that would be amazing.  Idk if it would affect game memory, but I shockingly hit the limit again because I'm making a huge mod with over 300 added characters (with menus to spawn and become any character) using models from Kotor, some I made from ToR and some ported from the HD mod for Dark Forces 2.

**Comment by Razish** [comment]
`I always get a cmd.exe error`
Then fix it.

But seriously, we can't give more information without you giving us more information.
What error? At what stage of building? What warnings? Does vanilla jamp.exe work or are the ingame issues local to OpenJK?

**Comment by ensiform** [comment]
Better discussion for the forums.
