### ISSUE TITLE
Fonts are not displayed in menus

### ISSUE THREAD

**Issue by LeFlou** [JACoders/OpenJK#675]
I've compiled OpenJK with MSVC 2010 in debug.
I've launched openjk_sp.x86.exe but it doesn't show any fonts in menu.
![fonts](https://cloud.githubusercontent.com/assets/9358055/8089454/49b357c6-0fa8-11e5-8024-cc6f0c60319c.JPG)

**Comment by ensiform** [comment]
Once again, stop using OpenJK (JKA version) With Jedi Outcast.

**Comment by cpfr** [comment]
It would be helpful to add a link or advice to this issue, since there might be other people (like me) who want to use OpenJK with Jedi Outcast (in order to make it work on linux platforms).
Is there a Jedi Outcast version of OpenJK or am I able to compile such a version myself?

**Comment by Razish** [comment]
It hasn't been tested in a while, but passing `-DBuildJK2SPEngine=On -DBuildJK2SPGame=On -DBuildJK2SPRdVanilla=On` to CMake may do the trick.

**Comment by ensiform** [comment]
The advice is there, just look in the codejk2 folder.
