### ISSUE TITLE
r_ext_multiTexture 0 still crashing

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#680]
Build from 30 june 2015. Some setting from this config file (my usual config) causes default windows error in the 1st loading screen before entering main menu. I cant rly recognize which one is the reason. Maybe you have an idea. Btw it is everything okay in build from june 12 and it is everything okay if not using config file. Anyway it is an issue because the game do not start at all. I thought it is r_mapoverbrightbits 2, but it is not.

https://www.dropbox.com/s/uh5ozqd8er763fl/config.cfg?dl=0

**Comment by ensiform** [comment]
Singleplayer? JA or JO?
Multiplayer?

You sure all the DLLs being used are updated correctly?

**Comment by Razish** [comment]
It would help to do /writeconfig blah.cfg and upload that, it could be one of the cvars in your config in conjunction with another cvar that exists.

**Comment by sudge** [comment]
JA, MP, every file just copy-replace and also I tried to clean install (in the new folder, and everytime fs_homepath ".") and exec cfg, had the same result. 

>It would help to do /writeconfig blah.cfg and upload that

Can you please explain a little bit more? I cant even enter the main menu after executing my cfg file and restart the game. If I understand correctly, this is the one you ask https://www.dropbox.com/s/habj3cpu0fi8va4/321.cfg?dl=0 Just after executing, no restart.

**Comment by Razish** [comment]
Hm. Try `+set r_ext_multitexture 1`

**Comment by sudge** [comment]
> +set r_ext_multitexture 1

Yep, this one is the reason.

**Comment by Razish** [comment]
Bah. That should have been fixed in #400

There's no particular reason to disable it. You will get absolutely minuscule performance difference.

**Comment by sudge** [comment]
>You will get absolutely minuscule performance difference.

No, about 30% or more fps boost with multitexture disabled, tested on nvidia adapter.

As I said before, there was no such a problem in build from june, 12. Just in 2 latest builds. You can check it out what had been changed.

**Comment by ensiform** [comment]
On what system specs?

**Comment by xycaleth** [comment]
> No, about 30% or more fps boost with multitexture disabled, tested on nvidia adapter.

I find that difficult to believe. Multitexturing reduces the number of triangles you have to draw, therefore it will improve FPS. My own testing backs this up as well.
