### ISSUE TITLE
where is cvar dissapeared?

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#683]
Windows, MP, Latest build. The problem is: cvar cg_fovAspectAdjust just dissapeared from the game, if I type it the console, it just says unknown. It IS there in the code, no need to proove, just use the search for "aspect" right there. I havent find any information about this cvar being removed or renamed or something else.

**Comment by ensiform** [comment]
It's not an engine cvar. You are not loading the correct client mod which has this feature.

Try the forums next time.

**Comment by sudge** [comment]
But it did work some time ago >,>

**Comment by ensiform** [comment]
And it still works. You just aren't using openjk mod

**Comment by sudge** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/10692765/8802234/f35665a8-2fe1-11e5-9097-ae9b2dce0d19.png)
>You just aren't using openjk mod

I do.

**Comment by ensiform** [comment]
That does not imply openjk mod.

**Comment by Razish** [comment]
You need to load the OpenJK cgame mod for that cvar to be registered.
Clean out residual DLLs in your homepath (usually C:\Users\username\Documents\My Games\OpenJK)

**Comment by ensiform** [comment]
It also will not appear during the menu there, if you have not loaded the mod at all yet with a fresh config.
