### ISSUE TITLE
OpenJK SP sometimes crashes when fighting against a sith (divide-by-zero)

### ISSUE THREAD

**Issue by iolojz** [JACoders/OpenJK#699]
Exception Type:        EXC_ARITHMETIC (SIGFPE)
    Exception Codes:       EXC_I386_DIV (divide by zero)

    Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
    0   jagamex86_64.dylib            	0x000000011dfbe9b8 WP_SaberDamageTrace(gentity_s*, int, int) + 15736
    1   jagamex86_64.dylib            	0x000000011dfbf158 WP_SabersDamageTrace(gentity_s*, int) + 264
    2   jagamex86_64.dylib            	0x000000011df09b4b ClientEvents(gentity_s*, int) + 171
    3   jagamex86_64.dylib            	0x000000011df112ca ClientThink_real(gentity_s*, usercmd_s*) + 4250
    4   jagamex86_64.dylib            	0x000000011df12483 ClientThink(int, usercmd_s*) + 1091
    5                                 	0x000000010f3119ae SV_ExecuteClientMessage(client_s*, msg_t*) + 1582
    6                                 	0x000000010f2f2faa Com_EventLoop() + 762
    7                                 	0x000000010f2f3cb5 Com_Frame() + 117
    8                                 	0x000000010f35e80a main + 346
    9   libdyld.dylib                 	0x00007fff860a75c9 start + 1

I am using OS X 10.10.4 and OpenJK version: openjk-2015-08-04-606fead2-osx downloaded from http://builds.openjk.org.

**Comment by xycaleth** [comment]
Thanks for reporting this issue. I think I already came across this bug yesterday and fixed it in 85d17952a9c. Are you able to build OpenJK yourself to try? If not, a new build should be available on Monday evening.

**Comment by iolojz** [comment]
I think so, I'll try :)

**Comment by iolojz** [comment]
Yes, it seems to be fixed :)
