### ISSUE TITLE
Extract DLLs into temp folder instead of home folder

### ISSUE THREAD

**Issue by xycaleth** [JACoders/OpenJK#704]
When extracting DLLs from PK3s, it would be better to extract them to a temporary folder instead of the home folder.

Many JKA players are accustomed to installing new mods directly into the GameData folder, and if DLLs are extracted into the home path then newly updated DLLs in the GameData folder will never be loaded (files are searched in home path first, before base path). This has been the cause of a number of usability issues with OpenJK.

To avoid this issue altogether, DLLs should be extracted to a user-writeable temporary folder instead.

**Comment by ensiform** [comment]
Can we make the game clean the basepath and homepath on shutdown?

**Comment by xycaleth** [comment]
What would you do in the clean up?

**Comment by ensiform** [comment]
Delete the DLLs

**Comment by xycaleth** [comment]
What if the player intentionally put DLLs outside of PK3s? :p

**Comment by ensiform** [comment]
Only do that for home

**Comment by xycaleth** [comment]
What if the player intentionally put DLLs outside of PK3s in the home folder?

**Comment by ensiform** [comment]
They shouldn't be anymore if the new way is temporary folder.
