### ISSUE TITLE
How to Launch Compiled Game?

### ISSUE THREAD

**Issue by ryanjkoehler** [JACoders/OpenJK#705]
I've followed all the steps in the compiling instructions, but I don't have any idea how to launch the game.  Some things I don't know:

Where is the GameData folder supposed to be?  The instructions say, "We highly recommend setting CMAKE_INSTALL_PREFIX to JKA's GameData folder", but there's no GameData folder.  Do I create it? Where should it be located?

I'm on a mac.  After running `make install` in the build directory it installed a folder JediAcademy with 3 files: OpenJK, OpenJK SP, and openjkded.x86_64 in the folder I set as the CMAKE_INSTALL_PREFIX.  Which one do I open to start the game? How do I open it, do I have to create a .command file?

**Comment by ensiform** [comment]
Can you please ask questions on the forums as directed in the readme.

**Comment by ensiform** [comment]
@redsaurus or @Xycaleth can comment on where it belongs on Mac
