### ISSUE TITLE
Issue with optimized vehicle networking

### ISSUE THREAD

**Issue by TheSil** [JACoders/OpenJK#708]
This thing in codemp/qcommon/msg.cpp 

    {//pilot riding *inside* a vehicle!
        MSG_WriteBits( msg, 1, 1 ); // Pilot player state
        numFields = (int)ARRAY_LEN( pilotPlayerStateFields ) - 82;
        PSFields = pilotPlayerStateFields

was originally intended to save some network bandwidth by not sending unnecessary data over network (last 82 fields). However it is buggy because those data are not actually unnecessary, see https://github.com/TheSil/base_enhanced/issues/15. 

Consider removing this "optimization", it makes no sense in nowadays networks anyway. Currently it just causes bugged functionality for piloted vehicles at the cost of some legacy and non beneficial optimization. 

One observation: If you remove this limit from server engine, vanilla client engine can deal with this.  Unfortunately though it causes issues with openjk clients, because OpenJK added this check:

	if ( lc > numFields || lc < 0 )
		Com_Error( ERR_DROP, "invalid playerState field count" );

Now openjk client engine expects to have same limited number of fields, even though it can handle original array size ARRAY_LEN( pilotPlayerStateFields ), while buffer does not overflow.

**Comment by ensiform** [comment]
Which part should be removed for the initial fix?

Would rather keep the sanity check in, and figure out why it fails.

**Comment by TheSil** [comment]
What i tested was replacing

numFields = (int)ARRAY_LEN( pilotPlayerStateFields ) - 82;

with

numFields = (int)ARRAY_LEN( pilotPlayerStateFields );

Everything else can stay i believe.

**Comment by ensiform** [comment]
What about changing the write function as well to remove the 82?

**Comment by TheSil** [comment]
Yea you are right, it should be changed in both occurrences, read and write.

**Comment by deathsythe47** [comment]
I get dropped with invalid playerState field count error whenever I try to pilot vehicles with openjk client. Looks like no siegers will be using openjk for now.

**Comment by ensiform** [comment]
I didn't have issue playing on hoth locally?

**Comment by Razish** [comment]
I was playing hoth + korriban using OpenJK the other day..

**Comment by ensiform** [comment]
For now I think I will add another int that is the absolute size of each array to check against.  And ignore the -82 for checking.  But that could still fail if somehow its reading in the wrong fields anyway?
