### ISSUE TITLE
Delete some branches?

### ISSUE THREAD

**Issue by mrwonko** [JACoders/OpenJK#713]
It seems to me like the branches release/1.0, sdl2-windows-port and possible rend2motionblur and coop could be deleted? I'm not sure about the latter two, could the (former) maintainers of those branches weigh in?

**Comment by xycaleth** [comment]
The release/1.0 branch was meant to be a working branch for tidying up the 1.0 release, but we lost momentum on it so it hasn't been touched in a while.

sdl2-windows-port, rend2motionblur and coop can go. sdl2-windows-port been merged into master, and the other two have been abandoned.
