### ISSUE TITLE
Some little issues which possible already known, but still exist aswell

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#714]
It is maybe in the latest build, I dunno, because it crashes on startup, and it is also going from build to build. Let's say it is related just for latest working build.

1) If you type something like "callvote timelimit 10" there will be no any description of vote in the left upper corner, just VOTE and YES/NO; can't really demonstrate it, because I need another players for that. Same appers to any vote from the console.

2) ...but it look like it's ok if you watch the demo, it says what thing you going to vote in left upper corner in the place for description like < timelimit 10 >

3) showing scoreboard seem to be broken or something; first of all it doesnt show spectators in TFFA (ah cmon you can try yourself, have no any tffa game online), it's maybe the same for CTF, BUT they are visible in demo's, look http://i6.5cm.ru/i/W73S.png 

4) if you call a vote and press your scoreboard button it will be show random chars in the vote description like < 562sfghwe > but another chars, just unknown by myself, and chars will change for anothers every half second or something like that; also, I've tried to watch demo using demoplayer configuration file, it changes timescale to slow down or get further, I just press to make demo faster and press scoreboard button for a bit long, and it crash with message like "command overflow"

5) maybe an olb bug, but still exist: take dual sabers in menu, open the console and type "saber1 dual_1", open the saber menu and you'll see one staff saber and one single saber as duals, you can also try to replace both sabers to staffs; it will not appear in game, but it will show in menu

**Comment by Razish** [comment]
You're using the JA++ client, and most of these issues are related to the gamecode, not the OpenJK engine.

**Comment by sudge** [comment]
Excuse me, ja++ part is only about things related to demo's. Everything else is about pure base client, also pure base server.

**Comment by ensiform** [comment]
Vote bugs are already fixed. A pure base server won't be fixed because it's broken in the cgame which you cannot use the fixed cgame portion as mentioned unless this is something different from what I understand.

**Comment by sudge** [comment]
@ensiform do you mean that vote work correctly if openjk server is using, but doesnt work on jamp server with pure?

**Comment by ensiform** [comment]
The vote is not relevant to the server engine being run. This is controlled by the mod code.

**Comment by sudge** [comment]
@ensiform it's ok then; but also, I remember another thing that seem like issue: cvars like com_maxfps can be set as words like that http://i6.5cm.ru/i/rZaZ.png , I dunno which values the going to be, but seems like set as maximum possible

**Comment by Razish** [comment]
That will be treated as 0, i.e. unlimited. No harm done.

**Comment by sudge** [comment]
@ensiform so, what is up with spectators? Is it relevant to pure or fixed already? It seem still not shown in TFFA and probably CTF too; and last point also not clear; about everything else it seem issue should be closed.

**Comment by ensiform** [comment]
Its relevant to pure.  Its fixed in OpenJK and JA++ afaik.

**Comment by ensiform** [comment]
![shot2015-09-20_17-28-04](https://cloud.githubusercontent.com/assets/997399/9983299/01a88e78-5fbd-11e5-8884-5a963ca87ba4.png)

See...
