### ISSUE TITLE
Last build for windows is broken badly

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#721]
Windows build from 21-22 sept, MP. http://i6.5cm.ru/i/7UDV.png 
Looks like some shader issue.

**Comment by mrwonko** [comment]
I've had a similar issue. Is this when starting a server using the menu? Does it work correctly when you start using the console with `map`?

**Comment by sudge** [comment]
No, the same problem using console. Affect even starting loading screen before developers logo, its pure white.

**Comment by mrwonko** [comment]
Turns out the issue for me was having `ui_dedicated 1` set, but sounds like you have a different issue?

**Comment by ensiform** [comment]
Its not really a shader issue, its just because something ran out of space most likely and is only giving out shader handle 0 (NULL shader) for everything.

Make sure renderer is up to date with the engine just to be sure.

**Comment by weaponrex** [comment]
hi i just copy all the files to replace, and i got the same issue as original poster.

**Comment by Razish** [comment]
Yep, issue seems to be with conflicting versions in some libraries we're using. Trying to work out the best fix atm.

**Comment by Razish** [comment]
For now, you can use a previous build: [2015-09-14](http://builds.openjk.org/openjk-2015-09-14-d4ac38d2-windows.zip)
