### ISSUE TITLE
Clipboard not working with console

### ISSUE THREAD

**Issue by weaponrex** [JACoders/OpenJK#723]
Hi, ctrl+v is not working to paste text in console, latest build

**Comment by ensiform** [comment]
Hasn't changed.  Whats in your clipboard?  ASCII text?

**Comment by Razish** [comment]
Seems to be related to SDL migration or such.
As a workaround, try using the insert key. You may need to use a modifier like shift+ins or ctrl+ins, can't quite remember.

**Comment by ensiform** [comment]
Its because of the workaround to turn key events for letters to capital.  Found a solution already.
