### ISSUE TITLE
Horrific text overlap

### ISSUE THREAD

**Issue by chrissypiercey** [JACoders/OpenJK#735]
Windows 10 64-bit

MP

Text overlaps, is misplaced, etc.
![text overlap](https://cloud.githubusercontent.com/assets/15004310/10486607/bdf77564-725d-11e5-8a2b-969909cd7386.jpg)

**Comment by ensiform** [comment]
Looks like you have a custom menu mod installed, my screen does not look like this at all.

Need more information.

**Comment by chrissypiercey** [comment]
Seems to be an issue with JA++.

**Comment by ensiform** [comment]
Make the issue there. Closing.
