### ISSUE TITLE
Game crashed when I start it with fs_game OpenJK

### ISSUE THREAD

**Issue by Paullik74** [JACoders/OpenJK#751]
Hi,
I've got Steam version + latest build OpenJK (Windows), and when I try run the game from shortcut openjk.x86.exe with argument +set fs_game OpenJK, it crashed.

![image](https://cloud.githubusercontent.com/assets/10046079/11149182/7b4e815e-8a21-11e5-8178-0725ad4a8ef4.png)
![image](https://cloud.githubusercontent.com/assets/10046079/11149066/e30b750a-8a20-11e5-8fb3-d25e0171da5a.png)
![image](https://cloud.githubusercontent.com/assets/10046079/11149081/002b185c-8a21-11e5-948a-1ad55ae235ba.png)

crashlog here:
[crashlog-2015-11-13_16-09-59.txt](https://github.com/JACoders/OpenJK/files/34047/crashlog-2015-11-13_16-09-59.txt)

„Mismatched UI_API_VERSION: expected 1, got 2” - Huh? :D

When I run openjk.x86.exe everything is OK, but no OpenJK features.

OS: Windows 10 Pro 64bit

**Comment by Razish** [comment]
Delete any DLLs in `fs_homepath` and `fs_basepath` i.e. `Documents/My Games/OpenJK` and `GameData/OpenJK`

It means it's loading an old version of the OpenJK uix86.dll

**Comment by Paullik74** [comment]
Delete the whole folder Documents/My Games/OpenJK and from GameData/OpenJK move jagamex86.dll to another place and nothing changed. :/

**Comment by Razish** [comment]
Ah, you have `D:\Hry\OpenJK\OpenJK\openjk.pk3` and `D:\Hry\OpenJK\OpenJK\openjk-x86.pk3`
Try deleting the oldest one (or both and reinstall openjk)

**Comment by Paullik74** [comment]
Nice :). I delete openjk.pk3 file and it works. Thank you.

Maybe it would be good delete oldest file openjk.pk3 from latest Windows build ZIP.

![image](https://cloud.githubusercontent.com/assets/10046079/11151980/4fdf9ef4-8a30-11e5-8856-1ff115e58311.png)

**Comment by dionrhys** [comment]
@deepy It looks like buildbot doesn't clean the install directory when it's packaging up the zip for distribution. Could you have a look?

**Comment by ensiform** [comment]
Hmm I would think openjk-x86.pk3 would still be the preferred file being used though.  Strange.

**Comment by sudge** [comment]
About the same problem, but using +set fs_game japlus (ja++). Error says: GetGameAPI failed on uix86.dll and link to crashlog. 
There is:
> --- ambient sound initialization ---
Sound memory manager started
VM_Create: uix86.dll succeeded
Mismatched UI_API_VERSION: expected 1, got 2
Closing SDL audio device...
SDL audio device shut down.
GetGameAPI failed on uix86.dll

in the end.

**Comment by Razish** [comment]
Updating JA++ (and clearing out old files if necessary) works.

Leaving this open until the buildbot is fixed.

**Comment by xycaleth** [comment]
I'm guessing this has been fixed now. Closing.
