### ISSUE TITLE
Endianess Functions use platform-dependent int-types

### ISSUE THREAD

**Issue by mrwonko** [JACoders/OpenJK#756]
```
short ShortSwap( short l );
int LongSwap( int l );
```

That should be `int16_t`/`int32_t`. It would also be nicer to use inline functions instead of defines for `LittleShort` etc. The swapping could also be generalized using a template, but that may have to wait until the mp libraries are C++?

This is mostly a note to myself; I'm just too busy to do this right away. (Because I'd like to do it cleanly, and that takes time.)

**Comment by ensiform** [comment]
>This is mostly a note to myself; I'm just too busy to do this right away. (Because I'd like to do it cleanly, and that takes time.)

Wouldn't these make more sense in a mental note document on google or something? =p

**Comment by mrwonko** [comment]
> Wouldn't these make more sense in a mental note document on google or something? =p

I don't see how this is not an issue with OpenJK.

**Comment by RostakaGmfun** [comment]
I'm currently working on this, PR will be opened ASAP.

**Comment by bmwalters** [comment]
This was fixed by #856, no?

**Comment by xycaleth** [comment]
Looks like it!
