### ISSUE TITLE
Arrays that need to be alphabetically sorted

### ISSUE THREAD

**Issue by ensiform** [JACoders/OpenJK#760]
We currently have several arrays in mod code that must be sorted alphabetically or they break.  I believe there are 2 commands/functions in the g_svcmds.c to check to make sure the fields and spawns are sorted but maybe that is not the best way to go.  Should we instead have an init function that warns what array indices are out of order for developer/debug on startup of modules?  It can already be done for cg_consolecmds since that has an Init function but lots do not.

I would prefer to keep the bsearch usage but its not 100% necessary though it seems used in some other tech3 variants still.

**Comment by mrwonko** [comment]
If you want a sorted container, why not use `std::set`? Yay for abstractions! Unless it's in the ABI, I suppose.

**Comment by xycaleth** [comment]
Why not just use a linear search? There's no reason not to and will likely be faster.

**Comment by ensiform** [comment]
Because mod is C not C++.

I don't think anyone has proven one way or the other which is faster?  It just looks cleaner than a mega if else spam.

**Comment by mrwonko** [comment]
> Because mod is C not C++.

Historically, yes. There's no reason for it to stay that way.

**Comment by xycaleth** [comment]
It will be faster (though not noticeably) because it utilises the CPU cache better. Not noticeably faster though. Writing a generic linear search function is also trivial. Here's one I wrote just now:
```c++
void *linear_search( const void *key, const void *ptr, size_t count, size_t size, int (*cmp)(const void *a, const void *b) ) {
  for ( size_t i = 0; i < count; i++ ) {
    if ( cmp(key, ptr) == 0 ) return (void *)ptr;
    ptr = (const char *)ptr + size;
  }
  return NULL;
}
```
Replace all your `bsearch` calls with linear_search and you no longer need to keep your arrays sorted, which is both error prone and annoying for coders.

**Comment by mrwonko** [comment]
But who in his right mind would write a linear search when you have `std::find`?

**Comment by xycaleth** [comment]
Mod code is currently still written in C :)

**Comment by ensiform** [comment]
There's very little benefits to change it to C++ outright right now other than to annoy server owners that run older centos with ancient gcc versions etc.

**Comment by ensiform** [comment]
That algo seems sufficient.  Q_LinearSearch okay for name to avoid any possible external collisions with lsearch or linear_search since it'd be included in q_shared.h

**Comment by ensiform** [comment]
Close when SP changes as well.

**Comment by ensiform** [comment]
I believe we removed all of the binary searching arrays now did we not? Can close if verified.

**Comment by Razish** [comment]
0 instances of bsearch, 20 instances of Q_LinearSearch. Closing.
