### ISSUE TITLE
weird messages that causes small lags in MP

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#762]
It happens I can see some messages in multiplayer, I havent seen them before using older builds. Builds exactly from buildbot. I can't see if there's some event which cause messages, but it seem to be when the map restarting (second one "...fs_game value..." exactly after restarting), or even after "Tab" to reload models (not sure).
http://i6.5cm.ru/i/CRV2.png
http://i6.5cm.ru/i/Zqqq.png

**Comment by ensiform** [comment]
The messages aren't causing the issue, the lag exists for other reasons.  And that only adds to it.

**Comment by ensiform** [comment]
Either way, made the first message less spammy so it shouldn't add to lag.  (In release mode)

And made the other one developer only.

**Comment by ensiform** [comment]
If someone wants to raise the lag issue or look into it that would probably help a lot of projects.  I do not want to just blindly increase the queue size because it'll just fill the queue up anyway.  I notice that the mouse event usually is some form of val1=1 val2=0 or 0,-1 etc when it happens.

**Comment by Razish** [comment]
Sounds like SDL keeps receiving mouse events when there's a hitch, then they're all added to the game at once. Made more noticeable by better mouse code in SDL2?
Could experiment with either silently dropping events, interpolating events if queue limit is exceeded, queue events uniquely and fine-tune the queue sizes and integrate the previous suggestions.

**Comment by ensiform** [comment]
See #745 for condump log of overflow spam with values.
