### ISSUE TITLE
¿fovAspectAdjust not working?

### ISSUE THREAD

**Issue by TriForceX** [JACoders/OpenJK#763]
Ive readed this in the changelog

[+] Added cg_fovAspectAdjust to correct field of view on non-4:3 aspect ratios
[+] Added cg_fovViewmodel to adjust the field of view for first-person weapons

so, in-game i cant use them, isnt recognized... i checked it in cg_view and everything looks correct. (also i tried to port it to jk2 to see if works, but when i use it, the screen fucked up).

PD: I compiled from my own repo and tried using the last build with no results.
¿what happen?

**Comment by ensiform** [comment]
Works just fine.  Likely not using correct cgame file either through connecting to pure server or not having it in a pk3 or not having the local one used because pk3 takes precedence without fs_dirbeforepak.
