### ISSUE TITLE
segfault at end of single player

### ISSUE THREAD

**Issue by chrysn** [JACoders/OpenJK#764]
when i completed the single player mission (light side), i experienced a segfault of the game after kyle and jaden are talking about future missions.

when trying to reproduce it, i worked from a safegame and cheat-killed ragnar (i had a hard time killing him the first time); the screen then goes black after "i'll annihilate you all" with fire sounds in the background and stays thus until i press enter, when the game again segfaults:

```
]npc kill all
^2Killing NPC tavion_sith_sword named tavion_ragnos
[...]
^3Skipping cinematic...
tty]*** Error in `/usr/lib/openjk/JediAcademy': free(): invalid size: 0x000000000bfb7790 ***
----- CL_Shutdown -----
Closing SDL audio device...
SDL audio device shut down.
-----------------------
tty]zsh: segmentation fault  openjk_sp
```

the game version i'm using is "openjk v1.0.1.1 linux-x86_64 Aug 16 2015", as packaged in debian experimental as 0~20150815+dfsg1-1.

please let me know if you need further information (eg. gdb info)

**Comment by ensiform** [comment]
We cannot take bug reports of versions that are that old as there is no stable release yet.  Can you try with newest source version instead?  The debian pacakges aren't even created by the OJK maintainers either.

**Comment by chrysn** [comment]
with the 2015-11-30-c8c64c4b-linux-64 version built by you, the segfault does not occur any more; however, the effect of being stuck after the vanishing of ragnar persists (black screen, fire sounds). pressing enter then skips the whole good-ending final scene. if that, as i have a vague impression, is related to cheating the end, please close the bug and accept my apologies for being noisy / not up to date on the latest release.
