### ISSUE TITLE
[ENHANCEMENT] Make Force Effect hideable

### ISSUE THREAD

**Issue by StanleySweet** [JACoders/OpenJK#771]
In Jedi Knight : Jedi Outcast, force push didn't make that zoom effect, It would be nice to be able to disable it, as it seemed to be hard coded last time I checked.

**Comment by ensiform** [comment]
Le sigh.

cg_renderToTextureFX 0.

**Comment by StanleySweet** [comment]
Thanks

2015-12-22 19:12 GMT+01:00 Ensiform <notifications@github.com>:
