### ISSUE TITLE
[ENCHANTMENT] Enable all effects from JKA that's not present in JKO

### ISSUE THREAD

**Issue by Civil** [JACoders/OpenJK#774]
There is at least "Glow" effect in JKA that's missing in JKO. Find a way to enable it (setting config option doesn't do any good).

**Comment by ensiform** [comment]
Dynamic Glow option cannot simply be enabled in JKO sorry.

I gave out the fixed shader files for joMME and the jk2mv to use and it can be made to work with the JK2SP variant of our SP engine but its not going to be released and this type of request should not be made on the issue list.

**Comment by Civil** [comment]
Why this type of request shouldn't be on the issue list? Because it's mostly about shaders?

**Comment by ensiform** [comment]
Because it strictly requires asset files to make function as you see fit.  Which distributing assets is not part of OpenJK.

**Comment by ensiform** [comment]
If you want to use this for personal use you can: https://dl.dropboxusercontent.com/u/13001904/z_dynglow.pk3

**Comment by Civil** [comment]
Thanks!
