### ISSUE TITLE
sv_maxping is useless and terrible

### ISSUE THREAD

**Issue by Caelish** [JACoders/OpenJK#776]
Okay, so that's slightly clickbaity of me. sv_maxping is a great idea; denying clients with pings above a customizable limit is by itself a *good*, useful idea. In fact, if it functioned correctly, I'd use it on servers I host to prevent some flavors of VPN abuse.

Unfortunately, it has a number of issues:
 * Occasionally, it'll tell clients their ping is too high and block them even when set to 999, even in instances where the client's actual latency to the server is not even a three-digit number.
 * It can be very easily bypassed using the magic of /reconnect
 * It only evaluates the first packet (?) or some single connectionless packet. Personally, I handle these differently from normal gameplay packets, in a way that increases latency, but also increases throughput (using things like the TOS byte), which leads me to the next point...

* It's basically completely, wildly inaccurate. It blocks some clients with significantly less latency than the limit set by the cvar, and it doesn't block some clients with significantly more latency if they just reconnect.

I really really *want* a working sv_maxping because of how it'd help me cut down on VPN abuse, but the current method is clearly not very useful. What I'd like to see is the way it works overhauled to either evaluate multiple packets for average latency (say the first 20 or something), or simply kicking players if their ping stays above X for more than Y seconds. Or maybe there's a better way I haven't considered. But I'd really like to see it implemented in a more useful way.

**Comment by ensiform** [comment]
It would have to be a separate option.

**Comment by eezstreet** [comment]
Simply kicking players if their ping remains over a certain threshold for a set period of time (90 seconds) seems like a good option.


Sent via the Samsung Galaxy S® 5 ACTIVE™, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by ensiform** [comment]
Which can be done in mod code.  I realize you want an agnostic solution but we would rather have little if any mod fixes in the engine.

**Comment by Caelish** [comment]
@ensiform I have tested it with OpenJK, yeah; I can consistently reproduce sv_maxping being really really inaccurate in terms of predicting client latency on servers that have been up for <24 hours.

I'm honestly not too worried about more advanced measures of stopping VPN abuse beyond simple latency. A lot of commonly used VPNs have very high latency (think consistent 500+ ms), I think accurate, working sv_maxping could be low hanging fruit to weeding those out for me.

**Comment by ensiform** [comment]
Unfortunately its not looking at active connected ping since they are not actively connected.  It happens during the initial connection only and doesn't do anything later on as the challenge packets are not checked once a connection is established.

**Comment by ensiform** [comment]
This can potentially be closed once #832 is merged.

**Comment by Caelish** [comment]
It just got merged, so I'll close this. :)
