### ISSUE TITLE
Upgrade included SDL to 2.0.4

### ISSUE THREAD

**Issue by ensiform** [JACoders/OpenJK#788]
This is needed to fix some of the input issues, alt code functionality, and fixing the alt beep on windows.

**Comment by Yberion** [comment]
I do like this idea!

**Comment by ensiform** [comment]
Not an idea lol.

**Comment by Razish** [comment]
Update please - I was going to do it myself but it looks like we need new VS2015 DLL+lib combo. The last one was provided by mrwonko.

**Comment by mrwonko** [comment]
I'll look into it this weekend.

**Comment by mrwonko** [comment]
See pull request #815.
