### ISSUE TITLE
Little camera hiccup motion when joining MP game

### ISSUE THREAD

**Issue by deathsythe47** [JACoders/OpenJK#790]
In MP, when you finish loading a map and get ingame as spectator, the screen abruptly cuts to the ingame view, and your camera does this hiccup motion. Like, it jerks forward and back really quick.

It looks bad. It also ruins the effect of the levelshot image transitioning into the ingame view. In singleplayer, you get a nice "wipe" effect for the levelshot transitioning to the ingame view, which is especially effective if the levelshot was taken from the perspective of the spawn. But in multiplayer, it abruptly cuts to the ingame view and then jerks the camera around.

**Comment by ensiform** [comment]
The dissolve wipe effect is for SP only.

I don't know what the jerky movement you'er speaking of though.

**Comment by Razish** [comment]
Probably the lerp from 0,0,0 to spectator spawn location.

**Comment by deathsythe47** [comment]
Here's a gfy of the jerky movement:

https://fat.gfycat.com/BoringHarmlessAtlasmoth.webm

**Comment by ensiform** [comment]
Yeah that's pretty harmless.

Would need the map to know if its doing what @Razish said though.

**Comment by deathsythe47** [comment]
Good point on that, I am running a custom server mod AND client mod, so I guess this isn't specific to OpenJK.

**Comment by ensiform** [comment]
Its still possible that it happens in base but im not sure what mod you're running.  I see nothing to suggest its the engine's fault either way.
