### ISSUE TITLE
Mac builds currently crash

### ISSUE THREAD

**Issue by ensiform** [JACoders/OpenJK#792]
Mac builds currently crash and have crashed for some time now per Circa on forums.

See thread starting here: http://jkhub.org/topic/5880-nightly-builds/?p=88008

@xycaleth @redsaurus @MazterQyou @deepy

**Comment by isair** [comment]
Latest nightly doesn't seem to crash for me.

**Comment by Razish** [comment]
Okay. Closing this for now, please open a new issue for mac-specific and buildbot-specific builds that crash and we will investigate each separately.
