### ISSUE TITLE
Failed loading ./rdsp-vanilla_i386.so: libjpeg.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fdoerrer** [JACoders/OpenJK#801]
Occurs on launch
I ran `ldd rdsp-vanilla_i386.so` and yes, it returned `libjpeg.so.8 => not found`
It wasn't in my repositories for debian jessie, so I tried establishing a link between `~/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libjpeg.so.8` and `/usr/lib/i386-linux-gnu/`, but the same error occurs.
am I linking it to the right directory?

**Comment by ensiform** [comment]
This isn't typically something for the issues list but a problem with your system configuration and better suited for the forums.

**Comment by Razish** [comment]
It may be worth attempting to compile it on your own system - you can also configure to use the provided libjpeg or the one installed on your system.

**Comment by xycaleth** [comment]
Closing since #920 seems to be the same issue and that has more information.
