### ISSUE TITLE
some cvar and video mode issues

### ISSUE THREAD

**Issue by sudge** [JACoders/OpenJK#803]
//Windows 7 x64
1) Setting cl_maxpackets to 20 (and up to 27) cause spam infinite messages which are also seen on the top left corner; 28 and above have no such a problem.
![shot2016-02-11_03-44-25](https://cloud.githubusercontent.com/assets/10692765/12963719/6edb2260-d076-11e5-9497-bd57e5f2e914.jpg)
2) Something really weird with r_displayrefresh; first of all, as I said before in another report, if you change the value of r_displayrefresh it doesnt work until you minimize and maximaze the game once, and this is everytime you just run the game or do vid_restart, I believe it is only 0 value work well everytime; what I just did: set cl_maxpackets to 60 and r_displayrefresh to 60, vid_restart, minimize and maximize the game - it look like refresh rate was about 30 instead of 60 (it is well seen, just like frame skip or something like that, dont know how to explain better, it just well seen if you compare); then I set r_displayrefresh to 0, vid_restart, minimize-maximize and it look like refresh rate of 60 aswell (smooth); so it seem to be 0 value the same as 60 actual refresh rate and 60 value the same 30 actual refresh rate;

I dont know if it is SDL-related issue, but it's something to be fixed, because I believe no one could think it is needed to minimize and maximize the game after every run to get displayrefresh work.

**Comment by Razish** [comment]
`#define MAX_PACKET_USERCMDS 32`
This is how many usercmds JA will attempt to squeeze into one packet. Packet loss and ridiculously high framerates will trigger this warning. It's relatively harmless and more of a notification that your configuration isn't suitable for your network environment.
FWIW, it can occur with no packet loss at `cl_maxPackets 31` or lower, assuming 1000 fps. `cl_maxPackets 20` requires <= 640 fps.

**Comment by sudge** [comment]
@Razish 
>There isn't much reason at all to have such a low
I know how does it work aswell, but the issue is that it spam infinite messages to the console, it can be just warning message, but currently it doesnt look like warning message, it look like something broken.

Thank you for such information, but it was previously well known by myself.

**Comment by Razish** [comment]
But that's intended, it should notify every time a usercmd fails to be included in a packet. Maybe the message could be more verbose/descriptive.

**Comment by sudge** [comment]
Problem with display refresh should be about closed, because it seems not related to the latest build. Should be some SDL-related stuff (because of updated version). So be aware.
