### ISSUE TITLE
Menu item texts are not drawn

### ISSUE THREAD

**Issue by tankefugl** [JACoders/OpenJK#805]
What I did:
* Built OpenJK following the build instructions
* Ran OpenJK from Visual Studio using the SP Client target, using the Debugging with Visual Studio instructions
* Also ran a release-compiled version outside of debugging

What I observed:
* When entering the main game menu, none of the item choice texts were drawn. (New, Load, Options, etc.)
* Menu items reacted to mouseover (sound and highlight), even though the text wasn't drawn

Built using VS2015 Update 1.

**Comment by ensiform** [comment]
Sounds like you're trying to use JK2 with OpenJK?  If so duplicate, and you need to build the JK2 client.

**Comment by tankefugl** [comment]
Alright, thanks. I'll close the issue then.
