### ISSUE TITLE
Oculus Rift support

### ISSUE THREAD

**Issue by Camron** [JACoders/OpenJK#83]
The SDK is available after registering at https://developer.oculusvr.com/

Development info can be found here:
https://developer.oculusvr.com/forums/
http://www.mtbs3d.com/phpBB/

**Comment by HEXcube** [comment]
@xLAva has added **Occulus Rift DK2** support to **Jedi Academy**. Check out the latest release - https://github.com/xLAva/JediAcademyLinux/releases . For source code, see the DK2 branch - https://github.com/xLAva/JediAcademyLinux/tree/HmdSupportDK2 . Looks like Virtual Reality is the "way of the Force"! :-)

**Comment by Grix** [comment]
Fantastic!
