### ISSUE TITLE
Footprints aren't drawn with the correct rotation

### ISSUE THREAD

**Issue by xycaleth** [JACoders/OpenJK#831]
**Operating system and version:**
OS X 10.11

**Is this for single player or multiplayer?**
Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
Footprints created from walking on sand aren't drawn at the correct rotation. They appear to be at 90-degrees to what it's supposed to be:
![Footstep drawn badly](https://cloud.githubusercontent.com/assets/1146859/14986443/deb76496-1143-11e6-8ffb-6cf351c04bf2.jpg)

**What did you expect to happen instead?**
Footprints should be draw in the same direction as the one the player is walking in.

**Comment by ensiform** [comment]
Is this a bug specific to OpenJK?

**Comment by xycaleth** [comment]
I'm pretty sure it's OpenJK specific. I don't have retail JKA on my mac.

**Comment by ensiform** [comment]
Can you check the cgame code for what method renders them?

**Comment by xycaleth** [comment]
Footsteps are created here:
https://github.com/JACoders/OpenJK/blob/master/codemp/cgame/cg_players.c#L2232-L2284

And then drawn from here:
https://github.com/JACoders/OpenJK/blob/master/codemp/cgame/cg_marks.c#L131

**Comment by ensiform** [comment]
Seems more like an issue with the cgame since its giving the rotation to the engine.

**Comment by AlexCSilva** [comment]
a bit off topic but how does the sand look so detailed?

**Comment by ensiform** [comment]
The map is pande_jkg_spaceport with good textures I assume.  That probably is also rend2, I'm not sure.

**Comment by AlexCSilva** [comment]
Yeah I got that map but I don't remember it looking that good, I'll check it again lol

**Comment by ensiform** [comment]
Maybe your settings are lower quality who knows.

**Comment by thedt** [comment]
Hmm the footsteps seem to go in random directions at first. I put cg_shadows 2 and cg_footsteps 4 so I could see how the shadow and footsteps reacted to the origins. It seems `cent->pe.legs.yawAngle` is based on map and not the player or this part of the code is doing something really odd when getting the matrix `trap->G2API_GetBoltMatrix( cent->ghoul2, 0, footBolt, &boltMatrix, tempAngles, cent->lerpOrigin,cg.time, cgs.gameModels, cent->modelScale);.`

**Comment by xycaleth** [comment]
This seems to be a problem with cgame. Using the retail cgame dll doesn't reproduce the bug.

**Comment by ensiform** [comment]
Not fixed in SP!

**Comment by TwelveEyes** [comment]
This can be fixed in SP by changing the yawAngle in line 3832 in `code/cgame/cg_players.cpp` from `cent->pe.legs.yawAngle-90` to `cent->pe.legs.yawAngle`. No reason to rotate the footprint by 90 degrees now.
