### ISSUE TITLE
Action music not transitioning back to explore music once enemies are cleared

### ISSUE THREAD

**Issue by swagmaster360** [JACoders/OpenJK#834]
Ok, when any explore music track goes to action when encountering an enemy, music doesn't transit back to explore music when enemies are killed no matter what, unless i use the music <path of music. command

I have a Windows 7 Home Premium 32-bit pc

This is a single-player bug

Basic desc. any action music track NEVER goes back to explore unless using the music command, which resets the music, this is being caused by version 2015-11-23-d56be4fd-windows

**Comment by ensiform** [comment]
Looks related to @mrwonko changes with dms/fx/genericparser

**Comment by mrwonko** [comment]
Mea culpa, good catch.
