### ISSUE TITLE
Autoaiming is strapped from the source?

### ISSUE THREAD

**Issue by Fighter19** [JACoders/OpenJK#836]
**Operating system and version:**
Windows x86-64

**Is this for single player or multiplayer?**
Single Player

**Description of the bug (and if possible, steps to reproduce the bug):**
Autoaim completely removed from the source code.

**What did you expect to happen instead?**
In best case disabled by compiling flags.
Rends the game nearly unplayable with gamepad.

I might be wrong, but it looks like all relevant functions for autoaiming have been stubbed as a result of the unneccessary cleanup of console code.

Instead of simply doing a check or disabling them by compiler flags.

Those lines of code weren't too much "overhead", neither would they negatively influence the size of the binary.
It makes playing the game with controller nearly impossible.

**Comment by shinyquagsire23** [comment]
If I remember correctly, this was stripped because it was part of the XBOX code which they couldn't keep for legal reasons.

**Comment by Fighter19** [comment]
Well, it was part of the xbox code, but it didn't contain any XBOX sdk functions, so I believe that function still belongs to Raven Soft, on top of that that file was already licensed as GPL, so how can that be changed. Either way, I've created a patch to enable Autoaiming (needs only a little finetuning) and basically copies everything that was responsible for autoaiming in the Pandora version by ptitSeb.

**Comment by AlexCSilva** [comment]
I've tried using a controller beofore, was so hard

**Comment by leilei-** [comment]
methinks the xbox code issue is more or less a Vicarious Visions property issue than a Xbox SDK issue

**Comment by ensiform** [comment]
Auto aiming was never a feature for the PC version and it won't be included.
