### ISSUE TITLE
I'm seeing ^ and number in color

### ISSUE THREAD

**Issue by randir101** [JACoders/OpenJK#839]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**

Windows 10

**Is this for single player or multiplayer?**

I only do multiplayer.

**Description of the bug (and if possible, steps to reproduce the bug):**

Sorry if my English is not good. I'm trying OpenJK first time, and I have my problem when typing ^ to do color, like ^2 for green it still shows the ^2. So it's annoying to change my player-name with colors, because I'm seeing ^1 ^2 ^3 everywhere inside text. Also chats binds are really dumb to type, it's hard to see how a chat is going to look before.

**What did you expect to happen instead?**

Normal I see "Randir" with my colors but now is "^5R^7a^5n^7d^2i^7r" etc until I press enter

**Comment by ensiform** [comment]
Intended behavior.  Not a bug.

This change makes it possible to edit the full text without running into the issues with the cursor being messed up.

**Comment by deathsythe47** [comment]
Could you tell me where the code for this was changed? I'm actually also interested in removing this in my own fork. Tried to find it a while ago and gave up.

**Comment by ensiform** [comment]
It's in the cl_scrn.cpp mostly I think.
