### ISSUE TITLE
s_volume doesn't affect all sounds

### ISSUE THREAD

**Issue by aufau** [JACoders/OpenJK#841]
**Operating system and version:**
Fedora 23

**Is this for single player or multiplayer?**
Tested only in multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
Some sounds aren't affected by s_volume cvar. Set s_volume to 0 and try rolling or receiving damage. Grunting and yelling are still audible and their volume level doesn't depend on s_volume value.

**What did you expect to happen instead?**
s_volume should scale all sounds.

**Comment by ensiform** [comment]
Those are affected by s_voiceVolume.  No issue here.

**Comment by aufau** [comment]
I don't know how it worked in original ja client, but being unable to turn off or silence some sounds doesn't *sound* right to me. There is no s_voiceVolume cvar if this is what you meant.

**Comment by xycaleth** [comment]
Just a FYI, all the volume cvars can be controlled via the sound options menu :)
