### ISSUE TITLE
What script file handles the account saving?

### ISSUE THREAD

**Issue by AnesidoraCalling** [JACoders/OpenJK#842]
I'm looking into creating a mod with OpenJK and would like to know where the account stats are handled and saved at the end of a match? Help would be much appreciated, thanks!

**Comment by xycaleth** [comment]
What accounts, and what stats? OpenJK have neither of these!

**Comment by shinyquagsire23** [comment]
The only accounts I've dealt with in JKA have all been server-side.

**Comment by AnesidoraCalling** [comment]
Oh I must be thinking of something else, sorry! I thought OpenJK saved user stats in MP.

**Comment by ensiform** [comment]
All it has is ja_guid but its not used for anything by default.

**Comment by Yberion** [comment]
What type of stats do you want to be saved?
