### ISSUE TITLE
Adding to levels

### ISSUE THREAD

**Issue by mrwonko** [JACoders/OpenJK#85]
It would be nice if at least the entities of a level could be modified, like having any file in &lt;levelname&gt;/*.ent be added to it or something like that.

This would also allow for making changes to original levels (say, showcase a new feature) without getting asset redistribution problems.

**Comment by dionrhys** [comment]
Whoops, didn't see this issue. I've implemented this a while back in #674. :)

**Comment by mrwonko** [comment]
Cool. Should probably mention that in the changelog, which could also use some categories so it's easier to find e.g. new features vs. bug fixes vs. improvements etc.

**Comment by dionrhys** [comment]
I've added a line about .ent files in the meantime: f66681b
