### ISSUE TITLE
Where does "ri" come from?

### ISSUE THREAD

**Issue by AnesidoraCalling** [JACoders/OpenJK#853]
I'm looking into modding with OpenJK and I can see a lot of mentions of "ri".

I know this is also from Quake, but not in the original Jedi Academy source - can someone help me learn how to include "ri"? I've seen "refimport_t ri" used a lot but I don't understand how it works and where the function is coming from.

Thanks.

**Comment by ensiform** [comment]
This should be asked on the forums.

The functions come from the renderer that exports them.
