### ISSUE TITLE
Default sv_master1 to master.jkhub.org

### ISSUE THREAD

**Issue by Caelish** [JACoders/OpenJK#854]
So we all know the Ravensoft master server is hopelessly broken, and has been for years. Every now and then, it'll randomly start ignoring servers using it, and drop them off the server list for undetermined time. I've had to spend non-insignificant amounts of money buying non-significant numbers of affected customers new IPs when it happened to them, and my customers are far from the only people this has happened to.

By comparison, master.jkhub.org is:
- Managed by the community
- Open to fixing/debugging issues if servers have them
- Far less frequently offline, and thus far more reliable
- Not prone to dropping servers off the server list at random

At the moment, OpenJK queries the Ravensoft master server by default, and has an option to use master.jkhub.org instead if launched with fs_game OpenJK. I think we've reached a point where, at 163 servers on it (masterjk3.ravensoft.com has 197), master.jkhub.org has basically every active JKA server listed on it. I'd like to suggest switching the default master servers around, so master.jkhub.org is queried by default, with a fallback to masterjk3.ravensoft.com.

As said, almost every server on the Ravensoft list is also on the JKHub list, and other advantages would include:
- Fewer players having issues if the Ravensoft server ever goes down permanently (the majority of players don't launch their game with fs_game OpenJK in my experience)
- Reduced impact of Ravensoft master server randomly dropping servers off it
- Improved server list availability for the majority of players
-  Futureproofing

I strongly think this is a better option than keeping the Ravensoft master as default first option now that master.jkhub.org is so widely used and has proven to be very reliable.

Thoughts?

**Comment by ensiform** [comment]
No longer necessary with multiple masters being scanned at same time by default.

Still need to adjust UI for this though I believe.
