### ISSUE TITLE
Full health for duels

### ISSUE THREAD

**Issue by circa-one** [JACoders/OpenJK#865]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**

all - server side

**Is this for single player or multiplayer?**

MP

**Description of the bug (and if possible, steps to reproduce the bug):**

Could be argued as not a bug, but just how the game was made, but I think it's silly how when you enter dueling mode in FFA, you don't get full health. How is it fair to duel someone that may only have 9hp and you may have 100hp? I know this is fixed in most mods, but it seems like a silly bug that should be fixed in OpenJK.

**What did you expect to happen instead?**

Full health when duel is accepted. Maybe even give full health after the duel, to the winner, but that's not necessarily needed.

**Comment by AlexCSilva** [comment]
It's better to have commands that let you set the starting health and armor

**Comment by CircaCitadel** [comment]
True, that would be best. Some people might want 100/25 or 100/0 instead.

**Comment by ensiform** [comment]
Literally ever mod already implements this. :suspect:

**Comment by circa-one** [comment]
I don't want to use a mod though. It's fixed in every mod because it's a silly bug.

**Comment by shinyquagsire23** [comment]
You could argue that this behavior could possibly be undesirable for some servers, so even if it were implemented it would probably be best left as an optional thing.

**Comment by xycaleth** [comment]
I would argue against adding this because it changes the gameplay. Even if we add it but have it disabled by a cvar by default, it's a slippery slope from there as similar features get added, but behind cvars.

**Comment by circa-one** [comment]
-_- so be it. If it's a design decision it makes 0 sense. :P

**Comment by circa-one** [comment]
But if you add it as a cvar to toggle, I'll love you all forever. I'll send you cookies. <3

**Comment by ensiform** [comment]
I'm siding with @xycaleth on this one, sorry @circa-one .

**Comment by AlexCSilva** [comment]
It's easy to add to ur own openjk fork

**Comment by circa-one** [comment]
If you know what you're doing, sure. :P
