### ISSUE TITLE
Spectators shown when player is eaten by rancor

### ISSUE THREAD

**Issue by circa-one** [JACoders/OpenJK#875]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**

all, server-side

**Is this for single player or multiplayer?**

MP

**Description of the bug (and if possible, steps to reproduce the bug):**

If a player is being spectated, and then gets eaten by a rancor, all the playermodels for each person spectating is displayed in the root position with sabers on, in that position. This can also cause the rancor to be frozen in place where it occurs if the spectators continue to spectate. The only way to make it go away is to press the jump key to enter free spectate mode and then click to go back to spectating.

Video to show:

https://youtu.be/4x_rYU-vXUA

**What did you expect to happen instead?**

No bodies to show, except for the player that's being spectated.

**Comment by AlexCSilva** [comment]
Lol I remember this glitch, OpenJK hasn't fixed it yet?
