### ISSUE TITLE
Compilation errors when using bundled SDL2 on Linux64bits

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [JACoders/OpenJK#876]
The title seems quite clear to me…
I tried to compile jedi outcast single player with all librairies bundled, and sdl2 made the compilation failed.
Here is the backtrace : 
`[ 25%] Building CXX object code/CMakeFiles/openjo_sp.x86_64.dir/__/shared/sdl/sdl_window.cpp.o
In file included from /home/hoel/Documents/apps/openjk/shared/sdl/sdl_window.cpp:23:0:
/home/hoel/Documents/apps/openjk/lib/SDL2/include/SDL_syswm.h:58:21: erreur fatale : windows.h : Aucun fichier ou dossier de ce type
 #include <windows.h>
                     ^
compilation terminée.
make[2]: *** [code/CMakeFiles/openjo_sp.x86_64.dir/build.make:2007: code/CMakeFiles/openjo_sp.x86_64.dir/__/shared/sdl/sdl_window.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:309: code/CMakeFiles/openjo_sp.x86_64.dir/all] Error 2
make: *** [Makefile:150: all] Error 2`
Compiling without sdl2 bundled works perfectly fine.
I’m having latest commit (downloaded them yesterday).

**Comment by xycaleth** [comment]
The bundled SDL2 only works with Windows by the looks of it. We recommend not using the bundled SDL2 when compiling on Linux/macOS anyway :)
