### ISSUE TITLE
Using a JK2 map for art project

### ISSUE THREAD

**Issue by JoeriBultheel** [JACoders/OpenJK#877]
Hello everyone, 

I downloaded, converted and imported a JK2 map into Unity for my personal non-commercial project which I am planning to put online soon. I'm kind of messing around with the meshes and textures of the map. If I put my website online with the game based on JK2's assets, will I have any legal issues to worry about? 

I thought I'd ask it here, since this is an open Jedi Knight project... In other words are the assets of JK2 still protected or free to use?

Thnx !

**Comment by ensiform** [comment]
How is this at all relevant to openjk?

**Comment by JoeriBultheel** [comment]
Since this is a project involving JK I thought I would get some info here. And was planning to delete this issue if it would bother. Just now finding out one cannot delete issues on github T_T. I'm screwed.

**Comment by xycaleth** [comment]
Only the source code for the games are licensed under an open source license. Anyone can use it as long as they attribute their work back to Raven etc. For arty things such as textures, maps, sounds, icons etc,, these are still licensed under the terms in the game's end-user license agreement meaning you shouldn't distribute them, or create things based off of them.

**Comment by JoeriBultheel** [comment]
Shouldn't use them in any case... , also not for non-commercial use?
Thank you for the info!

**Comment by xycaleth** [comment]
Yeah, in any case. Unless it's stated otherwise, the same rules apply to commercial and non-commercial purposes. The point of not allowing anyone but the creators to use something isn't only to prevent people making money of their own brands, it's also to protect the 'image' of the brand.

**Comment by JoeriBultheel** [comment]
ok got it. 
thnx!
