### ISSUE TITLE
Electrobinoculars and 1st-person lightsaber/melee for JA from JK2 SP?

### ISSUE THREAD

**Issue by dusty22** [JACoders/OpenJK#88]
So the electro-binoculars view is messed up in JKA SP, works fine for everything except lightsabers/melee which have no 1st person view, so it forces it to stay in 3rd person. 

Any chance this could be fixed, and maybe the 1st person lightsaber view could be brought back from JK2? 

I heard JK2 used it's own special transparent model for 1st person sabers, but JA could just use some variation of the cg_thirdpersonalpha cvar to some extent, which doesn't work but I think is supposed to make the playermodel look transparent...

Also, I would love to see the screenshotted save games return from JK2...

**Comment by 77Mynameislol77** [comment]
Sorry for the necro, but why not just allow the cvar but strip out the part where you can see your player model? I'd personally be fine with a floating sword, especially if it's a hidden cvar in the console.
