### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by Jbeagle** [JACoders/OpenJK#880]
Hello,

Sorry if this is a really dumb question but I got OpenJK to work for Jedi Academy buy downloading the latest build from https://builds.openjk.org/ and extracting the files into the GameData folder, but when I tried to do the same for Jedi Outcast, it did not work.  I read in a forum that you need the openjo_sp.exe, but that was not in the latest build.  Where can I get this?

Thanks for the help!

**Comment by ensiform** [comment]
Do not post "dumb questions here". Ask on the forums.  And Jedi Outcast support says clearly that it is not included by default, you would need to compile and build a copy for yourself.
