### ISSUE TITLE
Windows Dedicated Server crashes upon CTRL+C or hitting the X

### ISSUE THREAD

**Issue by eezstreet** [JACoders/OpenJK#887]
It's not supposed to be a graceful kill, but it crashes while shutting down.

The problem seems to be happening because the signal handler for Windows runs on a separate thread from the main thread, and orders the game to terminate while it's in the middle of a gamecode frame.

**Comment by ensiform** [comment]
Test further upstream.

What did you do to verify its "crashing inappropriately" ?

**Comment by eezstreet** [comment]
All I did was close it via Ctrl+C and via X button and it crashed in both cases without further modifications.

**Comment by dionrhys** [comment]
OpenJK behaviour deviates from ioq3. ioq3 [uses the signal() functions on all platforms](https://github.com/ioquake/ioq3/blob/master/code/sys/sys_main.c#L718), whereas OpenJK uses [signal() for unix](https://github.com/JACoders/OpenJK/blob/master/shared/sys/sys_unix.cpp#L49) but [SetConsoleCtrlHandler for Windows](https://github.com/JACoders/OpenJK/blob/master/shared/sys/con_win32.cpp#L291).

signal() on Linux interrupts applications by [hijacking the "root" thread](https://stackoverflow.com/questions/11679568/signal-handling-with-multiple-threads-in-linux) (and I believe other threads can keep running?)

[Windows control handlers](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683242.aspx) spawn a new thread each time, so this is problematic when there's no synchronization in place. signal() interrupts processes on Windows like it does on Unix, [*except* if the signal is a Ctrl+C](https://msdn.microsoft.com/en-us/library/xdkz3x12.aspx)... (or is there some distinction here between GUI Win32 apps and console apps?)

Hopefully just using signal() everywhere like ioq3 does would work? Can imagine there still being synchronization issues though.

**Comment by ensiform** [comment]
ioquake3 still uses SetConsoleCtrlHandler, wtf you smokin.

https://github.com/ioquake/ioq3/blob/master/code/sys/con_win32.c#L294

**Comment by AlexCSilva** [comment]
Th

**Comment by AlexCSilva** [comment]
This was fixed wasnt it?

**Comment by ensiform** [comment]
Not really but it's not really an issue either.

**Comment by AlexCSilva** [comment]
Doesn't seem to happen anymore for me I think

**Comment by xycaleth** [comment]
I'll close this then if we don't think it's a problem anymore
