### ISSUE TITLE
Issues launching OpenJK on OSX El Capitan

### ISSUE THREAD

**Issue by IVXCVI** [JACoders/OpenJK#892]
**Operating system and version:**
OSX 10.11.6

**Is this for single player or multiplayer?**
Both?

**Description of the bug (and if possible, steps to reproduce the bug):**
Via Steam--after placing the three files into:
```
/Applications/Star Wars Jedi Knight: Jedi Academy.app/Contents/
```
I execute either binary and get the following error:

>openjk_sp.x86_64 cannot be opened because of a problem.

>Check with the developer to make sure openjk_sp.x86_64 works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

Vanilla game works without issue.

I downloaded multiple binaries from the build page, all the way back to January. All returned the same error.

**What did you expect to happen instead?**
I expected the binaries to launch the game.

**Comment by xycaleth** [comment]
Can you attach the error report that you get when trying to run OpenJK? I suspect you're missing SDL2 from your system and the error report should be able to confirm this :)

**Comment by IVXCVI** [comment]
Hi xycaleth,

Yes, I forgot to install sdl2. I realized my mistake and afterward OpenJK worked just fine!

Thanks!
