### ISSUE TITLE
Blaster Marks

### ISSUE THREAD

**Issue by danyul0w0** [JACoders/OpenJK#894]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:** Windows 10 64 Bit

**Is this for single player or multiplayer?**
Multiplayer and Singleplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
Blaster marks do not render correctly on wall surfaces and show interlacing issues.

http://images.akamai.steamusercontent.com/ugc/275095429952102111/CB386484EC647D83D5C1FE3593BD852259FF7083/

**What did you expect to happen instead?**
Solid blaster marks that do not change with movement nor disappear from certain angles.

**Comment by ensiform** [comment]
That's not fixable I'm afraid on the patch meshes.  Looks like you're using a mod like ja++ too?

**Comment by leilei-** [comment]
I'm assuming "interlacing" = z-fighting here.   All I can suggest is to change r_depthBits

**Comment by xycaleth** [comment]
Does it work in regular JKA? Do you have any weapon mods which might change the blaster mark shaders? I noticed the "Ultimate weapons" mod has z-fighting problems but this is an issue with the mod rather than OpenJK (I think).

**Comment by danyul0w0** [comment]
Works in regular JKA, there was the dynamic lights mod and I also had a more HD marks mod at one point to see if that would remedy it. JA++ is also present, but same with base.

**Comment by ensiform** [comment]
![20161126133529_1](https://cloud.githubusercontent.com/assets/997399/20642759/2d0df6be-b3dd-11e6-9e08-d517f8671a87.jpg)

Base OpenJK blaster marks looking okay here.

**Comment by leilei-** [comment]
perhaps the new marks shaders don't have polygonoffset defined.

**Comment by danyul0w0** [comment]
Tested on base with no new effects, same issue, interestingly the marks look different to the ones produced in ensiform's screenshot. A steam issue perhaps?

**Comment by danyul0w0** [comment]
Please disregard, I was silly enough to overlook files that I'd written myself and it seems one of those was the issue.
