### ISSUE TITLE
qboolean definition changed = lots compile fixes?

### ISSUE THREAD

**Issue by dusty22** [JACoders/OpenJK#900]
It seems to definition of qboolean has been changed. Before it basically acted like an all-in-one int and boolean with very weak type-checking, and now it's an enum {qfalse, qtrue} and can't convert between integer and boolean cleanly anymore, resulting in lots of code snippets needing to be edited.

Is there any particular reason for this change? It looks like it was changed in this commit: https://github.com/JACoders/OpenJK/commit/5c8a2d7ad9d53e5886436b50628c258a5b48bda5

The old definition was taken out of q_shared.h and the new definition was put into q_platform.h

EDIT: Probably unrelated, but the random() function in wp_saber.cpp seems to be an unknown identifier as well.

**Comment by ensiform** [comment]
Yes, because the qboolean declaration is now shared across sp<>mp.  And you cannot convert between enums and ints ever in C++.  There is no issue here.

This is the random function change that you apparently didn't see: https://github.com/JACoders/OpenJK/commit/2bcf85c2e5d0526205165521c88dfe0442e75f06

**Comment by dusty22** [comment]
Ok. I guess I just have to fix the code files in my mod that diverge from the master repo. And thanks for the info on the random() function.

Still though, is there any reason for changing qboolean to an enum? Why not just keep it as an int like before?

**Comment by ensiform** [comment]
It always was.  There was just an overriding `#define` forcing it.  I also said you can wait for xyc to explain the reasoning, as he was the one that went forward with it I believe.  TBH conformity with the MP codebase is the likeliest that I can come up with.  MP SDK and MP Engine always used enum.  Only SP deviated from that.

**Comment by dusty22** [comment]
@ensiform 

Now my compiler is complaining that q_math.cpp is missing. It's odd because it worked before when I was commenting, not sure what I messed up.  Any idea what's causing it?

**Comment by ensiform** [comment]
It's in the shared folder now.
