### ISSUE TITLE
Cannot get Dismemberment to work with OpenJK

### ISSUE THREAD

**Issue by MomokaChan** [JACoders/OpenJK#901]
-Windows10

Singleplayer

Dismemberment works with the normal Jedi Academy, as I put the commands into the config and such, but when I load OpenJK it does not have dismemberment anymore. I tried the patch /MyGames/OpenJK as well but I cannot get it to work.

**Comment by ensiform** [comment]
Dismemberment feature hasn't changed at all.  Some sites post invalid cvars that never worked so please give more information.

**Comment by MomokaChan** [comment]
What is used then? 

I used the guide - https://jkhub.org/tutorials/article/175-model-dismemberment-realistic-lightsaber-combat/

**Comment by ensiform** [comment]
Those ones all exist to my knowledge and nothing has changed regarding them or the code surrounding it.  But some random sites do have a few weird ones which I remember not existing at all.

**Comment by RoundDuckMann** [comment]
type "exec autoexec.cfg" in the command prompt once, if using the autoexec method.

**Comment by ensiform** [comment]
> type "exec autoexec.cfg" in the command prompt once, if using the autoexec method.

OpenJK SP uses autoexec_sp.cfg for SP to allow a separate startup settings between MP and SP.

**Comment by Razish** [comment]
Closing this to clean up issue tracker, dismemberment works in OpenJK and has not changed.
Feel free to re-open if you can provide a reproducible example of dismemberment not working with details on what you have tried.
