### ISSUE TITLE
NOT A BUG - Extend range for r_subdivisions down to 0.5

### ISSUE THREAD

**Issue by MoritzJT** [JACoders/OpenJK#903]
I'm not sure if this is the right place for this - however I'd like to be able to set r_subdivisions to 0.5 for smooth curves as it works for some ID3 engine games. Why has this been capped to 4 in OpenJK while it works in vanilla game?

Is there a specific reason behind this?

**Comment by ensiform** [comment]
Is there a specific reason to use that low of a value?

@Razish made the change here: https://github.com/JACoders/OpenJK/commit/dadd19f543079406f273f04de4b39810c70775f2 with little information.

Awaiting @Razish response.

**Comment by Razish** [comment]
Um, not sure why `r_subdivisions` has a lower limit of 4. Just checked the code, I must have thought I was looking at something else like `r_znear`.
There should be no lower limit. Or something sane like 0.001

**Comment by ensiform** [comment]
Corrected in https://github.com/JACoders/OpenJK/commit/82d82094e8c53657f9f57ba8740496c2cc5ba204 But you'll need to self compile for the time being.

**Comment by leilei-** [comment]
You'll probably not want that as it'll have the risk of running into the vertice per surface limit and likely not draw the curve properly.
