### ISSUE TITLE
Using the console as chat (without say)

### ISSUE THREAD

**Issue by srcanseco** [JACoders/OpenJK#909]
**Operating system and version:**
Win10.1607-B14393.693

**Is this for single player or multiplayer?**
Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
I suggest going to [this research](https://github.com/JACoders/OpenJK/issues/866#issuecomment-279525865) in order to understand better this issue, otherwise it's quite simple;

The fact that you can't use the console as chat (without the `say` command) is a little annoyance, its something that was possible in vanilla and a quality of life feature for chatting in-game while doing other things.

**What did you expect to happen instead?**
When you chat with the console, and the first word is not a command, send the output to the chat (as a `say` command).

**Comment by ensiform** [comment]
This was removed by design to prevent sending chat of commands that don't exist such as typing in a typo of rconPassword and sending your password to the server.
