### ISSUE TITLE
Rconaddress don't seem to work properly compared to on regular jamp

### ISSUE THREAD

**Issue by AlexCSilva** [JACoders/OpenJK#913]
Reporting a bug? Please make sure you've given the following information - thanks!

Windows 7 Ultimate

Multiplayer

Rconaddress doesn't seem to work, even with the right password it keeps saying "bad rconpassword."

It works normally on regular jamp however.

**Comment by AlexCSilva** [comment]
wait nvm think it works in menu

**Comment by ensiform** [comment]
It works fine regardless of being in menu or not.

**Comment by AlexCSilva** [comment]
Doesn't seem to work for me in game.. It is the right rconpassword though as I try it in main menu.

**Comment by ensiform** [comment]
It will only say bad password if the password is bad and not for any other reason, same as always.

**Comment by AlexCSilva** [comment]
It only works in menu for me I swear lol, i dont change it when i go in game and i check that it hasnt changed either too

**Comment by ensiform** [comment]
Is the password only using plain ascii characters ?

**Comment by AlexCSilva** [comment]
Yep

**Comment by ensiform** [comment]
Well IDK what to tell you. There is nothing special about rcon in menu vs game other than it uses server IP. Are you trying to run server and client at same time from menu?
