### ISSUE TITLE
Restore Xbox support

### ISSUE THREAD

**Issue by luke69420** [JACoders/OpenJK#914]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**

Xbox

**Is this for single player or multiplayer?**

Both

**Description of the bug (and if possible, steps to reproduce the bug):**

Game does not run on Xbox

**What did you expect to happen instead?**

Game to run on Xbox

This game was my favorite game to play on Xbox and I spent many hours of my childhood playing it. I still have my Xbox and original JA copy but I would love to get all the bugfixes and goodies of the OpenJK project on it. Maybe we could even get some console-friendly things like npc spawning menus.

**Comment by ensiform** [comment]
Is not going to happen ever.

**Comment by luke69420** [comment]
Are you that condescending to everyone who posts here? No need to flame me just because I play on consoles, dick.

**Comment by xycaleth** [comment]
Unfortunately he is always like that -.-

We don't have any plans to support or restore the Xbox code because a lot of it was proprietary and having that mixed in with GPL code is obviously not the best idea :) On top of that we don't (to my knowledge) have any way of compiling or running the code for Xbox (maybe not in terms of tools but in terms of hardware).

**Comment by luke69420** [comment]
Thank you for the thoughtful explanation.

**Comment by ensiform** [comment]
Asking you to use your brain is not attacking you for using consoles or flaming. It merely suggests use a little common sense and I offered to give more detail if you requested. Throwing out insults and ad homenims doesn't really help your case. So you sir, are the dick.

**Comment by ouned** [comment]
@ensiform: i read all the issues, answers etc. here and you always sound a bit too harsh to say the least :P
just because it's obvious for you doesn't mean it's for others, too

**Comment by ensiform** [comment]
Of course, because I say it how it is and don't pander to hurt feelings.  This particular question/discussion would have also been better off asked at say the forums too.

**Comment by leilei-** [comment]
Even a fresh clean-room Xbox reimplementation would be legally risky due to the required SDK dependency.  This is more of a task for a willing edge-crossing fork on some remote xbox forum to take rather than this tree for all the legal reasons alove
