### ISSUE TITLE
SP combat music slow to transition back to exploration music.

### ISSUE THREAD

**Issue by JokerOmega1** [JACoders/OpenJK#915]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Windows 10, openjk-2016-08-22-cdfdb5ad-windows

**Is this for single player or multiplayer?**
Single player

**Description of the bug (and if possible, steps to reproduce the bug):**
Combat music is very slow to transition back to exploration music after defeating enemies, some times not transitioning at all.

**What did you expect to happen instead?**
Music to transition as it should.

**Comment by ensiform** [comment]
Are you able to build from source to see if it is still the same? The buildbot building releases as evidenced by 8-22 is moderately old now.

**Comment by JokerOmega1** [comment]
I am not exactly sure how "build from source", is it a download option I am missing perhaps?

**Comment by Razish** [comment]
Just to confirm, are you slowing the transition is slower than it was in vanilla JKA, making this a bug? Or is this a feature request?

**Comment by JokerOmega1** [comment]
I am reporting this as a bug,

"Description of the bug (and if possible, steps to reproduce the bug):
Combat music is very slow to transition back to exploration music after defeating enemies, some times not transitioning at all."

**Comment by Razish** [comment]
Okay thanks, just wanted to confirm before we go chasing down behavior changes we may not have made :P
I think Ensi is on the right track regarding the parser rewrite FWIW

**Comment by ensiform** [comment]
I also noticed on a level in jk2 there is some sort of warning about useboss and no boss text defined.  I forgot what level it was on though. Could be related to issues in parser too.

**Comment by JokerOmega1** [comment]
Hope you can locate the cause to this issue, holding off on another JKJA SP playthrough until this has been fixed, hopefully you'll release another windows build when that happens.

**Comment by Bucky21659** [comment]
> I also noticed on a level in jk2 there is some sort of warning about useboss and no boss text defined. I forgot what level it was on though. Could be related to issues in parser too.

Seeing this when loading a savegame on artus_detention, console outputs:
`Error parsing music data (in "ext_data/dms.dat"):
'useboss' "1" has no "boss" entry!`

**Comment by ensiform** [comment]
Paging @mrwonko ^

**Comment by mrwonko** [comment]
I'll take a look later.

**Comment by JokerOmega1** [comment]
Yay progress!

**Comment by mrwonko** [comment]
There's a chance my commit b11d6dd caused this with its changes to `snd_music.cpp`, I'll take a closer look at the weekend when I'm not exhausted from 8h of work.

**Comment by mrwonko** [comment]
Huh, that was simple enough... Thanks for including the `'useboss' "1" has no "boss" entry!` error, that helped a lot. Fix coming momentarily, and it was indeed my fault.

**Comment by mrwonko** [comment]
I'm not completely sure this also fixes the slow transition issue, please reopen if that is still an issue.

**Comment by mrwonko** [comment]
Here's a binary for you to test with if you're on Windows.
[openjk_sp.x86.exe.zip](https://github.com/JACoders/OpenJK/files/987760/openjk_sp.x86.exe.zip)

**Comment by JokerOmega1** [comment]
My game doesn't start when I attempt to use that binary, I have attached the crash log, if it helps.
[crashlog-2017-05-12_18-16-10.txt](https://github.com/JACoders/OpenJK/files/997345/crashlog-2017-05-12_18-16-10.txt)

**Comment by mrwonko** [comment]
Ugh... Looks like you have an outdated renderer. I'm not sure if there have been any binary releases of a compatible version. Maybe there are - otherwise I'll need to build that and probably jagamex86.dll once I get around to it. (Currently on my Mac...)

**Comment by JokerOmega1** [comment]
Well I am using the latest windows release "bot" build (openjk-2016-08-22-cdfdb5ad-windows), so if you manage to put together up to date files for this than that would be swell, would love to get back to my playthrough without the annoying music issue.

**Comment by ensiform** [comment]
That version isn't compatible with later versions of the code since then.  @mrwonko just was being lazy and only sent you the exe by itself without knowing the renderer and gamecode should have been included.

**Comment by mrwonko** [comment]
Right, sorry about that, this one should hopefully include everything you need: [OpenJK-Windows-x86-JKASP.zip](https://github.com/JACoders/OpenJK/files/999363/OpenJK-Windows-x86-JKASP.zip)
Potentially also of interest: [OpenJK-Windows-x86-JKAMP.zip](https://github.com/JACoders/OpenJK/files/999364/OpenJK-Windows-x86-JKAMP.zip)

**Comment by JokerOmega1** [comment]
So far so good, the slow music transition seems to be gone, thanks for fix mrwonko!
