### ISSUE TITLE
Frontal flipkick doesn't work on jump2 (Multiplayer)

### ISSUE THREAD

**Issue by Mr5quid** [JACoders/OpenJK#919]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:** Debian 8.7 64-bits (Linux 3.16.0-4-amd64 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux)

**Is this for single player or multiplayer?** Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):** When using jump force power level 2 instead of the default level 3 in multiplayer, frontal flipkicking doesn't work. There's no animation nor any effect on the target. It works for others who don't use OpenJK. Howerver sideway flipkicking still works.

**What did you expect to happen instead?** I expected to be able to do frontal flipkicks on jump2.

**Comment by ensiform** [comment]
Using the OpenJK engine won't affect the mod like this.

Are you absolutely certain you aren't using a different mod? Flipkicking isn't even enabled in basejka.

**Comment by Mr5quid** [comment]
I'm using JA++ with OpenJK and I play on a JA+ server. I can't be absolutely certain this is an OpenJK bug but like I said, the other players can do frontal flipkicks on jump2, so it felt like a reasonable explanation. I didn't know however that flipkicking is a JA+ feature so in that case, my issue could be a ja++ bug and not an OpenJK one.

**Comment by ensiform** [comment]
Then it is related to JA++, not OpenJK.
