### ISSUE TITLE
Jedi Academy gets stuck after completing Echo  Base

### ISSUE THREAD

**Issue by rsantellan** [JACoders/OpenJK#923]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Ubuntu 14.04 64 bits

**Is this for single player or multiplayer?**
Single player

**Description of the bug (and if possible, steps to reproduce the bug):**

Using build: openjk_sp.x86_64 
OpenJK: v1.0.1.1 linux-x86_64 Jan 21 2017

After finishing Echo base going back to the academy all three stare at each other and I no keyboard key can get out of the scene.

![screenshot_2017-05-16_12-55-46](https://cloud.githubusercontent.com/assets/1820598/26116077/408fe382-3a38-11e7-8f72-3020cd9b5eda.png)

**What did you expect to happen instead?**
To finish the scene.

**Comment by ensiform** [comment]
Use a newer build and try again.

**Comment by rsantellan** [comment]
Using OpenJK: v1.0.1.1 linux-x86_64 May 13 2017 is fixed.
Thanks!
