### ISSUE TITLE
Switch the new colors

### ISSUE THREAD

**Issue by circa-one** [JACoders/OpenJK#932]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
all

**Is this for single player or multiplayer?**
MP

**Description of the bug (and if possible, steps to reproduce the bug):**
Not a bug, just a request. Right now the new colors for console/chat are set to be 8 as orange and 9 as grey. But when anyone that isn't using OpenJK sees them, they just see black instead of orange and red instead of grey.

I think they should be swapped, so they are more similar to their vanilla counterpart. That way if someone DOES use those colors, its a bit closer to what they have to those using vanilla, compared to what they are now. 

Its a picky request, but I figured I'd ask for it before or if you guys ever decide on a 1.0 release. I think this should be the standard for OpenJK from here on out. Though unfortunately some people are already accustomed to the current numbers, it wouldn't take long to adjust if it was the new standard.

**Comment by ensiform** [comment]
They're matching of the color codes with games that implement more colors so I vote no.

**Comment by ensiform** [comment]
Can this be closed?

I vote no on the change.

**Comment by Razish** [comment]
Voting no also because of familiarity. Willing to hear more opinions before closing.

**Comment by ensiform** [comment]
Also because they technically only worked in a wrapped sense in base due to a bug, and was never fully functional in every place colors were accepted or stripped.

**Comment by dionrhys** [comment]
The gavel struck thrice!
