### ISSUE TITLE
Couldn't load default.cfg

### ISSUE THREAD

**Issue by raz0rknaif** [JACoders/OpenJK#936]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
WINDOWS 10

**Is this for single player or multiplayer?**
Single Player

**Description of the bug (and if possible, steps to reproduce the bug):**
I copied all the files to the right places. Then i try to start single player, and i get this error:
OpenJK: v1.0.1.1 win_msvc-x86 Jul 31 2017
Initialising zone memory .....
----- FS_Startup -----
Current search path:
C:\Users\Owner\Documents\My Games\OpenJK\base
C:\GOG Games\Star Wars Jedi Knight II - Jedi Outcast\base

----------------------
0 files in pk3 files
Couldn't load default.cfg

**What did you expect to happen instead?**
i expected to play.

**Comment by raz0rknaif** [comment]
Maybe something happened during install. It complained about something, and I told the GOG installer to ignore it. I get this error message when I try to start the regular launcher:

JK2: v1.03 win-x86 May  3 2002
Initialising zone memory .....
----- FS_Startup -----
Current search path:
C:\GOG Games\Star Wars Jedi Knight II - Jedi Outcast\GameData\base\assets5.pk3 (4 files)
C:\GOG Games\Star Wars Jedi Knight II - Jedi Outcast\GameData\base\assets2.pk3 (289 files)
C:\GOG Games\Star Wars Jedi Knight II - Jedi Outcast\GameData\base\assets1.pk3 (8011 files)
C:\GOG Games\Star Wars Jedi Knight II - Jedi Outcast\GameData/base

----------------------
8304 files in pk3 files

Running in restricted demo mode.

----- FS_Startup -----
Current search path:
C:\GOG Games\Star Wars Jedi Knight II - Jedi Outcast\GameData/demo

----------------------
8304 files in pk3 files
Couldn't load default.cfg

**Comment by ensiform** [comment]
OpenJK does not support JK2 in the available builds.  And the demo versions are not supported either.

Any versions of either game must be fully upgraded.
