### ISSUE TITLE
Allow players to pick their gender pronouns

### ISSUE THREAD

**Issue by roxxxy333** [JACoders/OpenJK#940]
We should be able to choose which pronouns we want the other players to see when our character dies. The default setting (if the user doesn't manually specify) should be the non-binary/genderqueer messages, such as SUICIDE_GENERICDEATH_GENDERLESS ("killed itself") and SUICIDE_EXPLOSIVES_GENDERLESS ("blew itself up").

**Comment by ensiform** [comment]
this is not relevant to OpenJK at all. please make yourself a mod that adds the feature you request.
