### ISSUE TITLE
Build keeps failing with Visual Studio Express 2013

### ISSUE THREAD

**Issue by RecklessJames** [JACoders/OpenJK#949]
Hey there, so I'm new to this and decided to try some modding experiments with OpenJK. First I managed to figure out how to setup a project using CMake and then open it using Visual Studio. Since I was only testing the waters, I had made zero changes to the content and then decided to build it... and then it gave me these 4 errors (along with many warnings) and says the "build failed" once it finishes.
![2ed7fbd57a239496dae02307f555d77e](https://user-images.githubusercontent.com/12752293/34396630-7e99ab72-eb3b-11e7-8b36-4a4997e81269.png)
It seems most of the issue relates to line 68 as seen above, but sadly I don't know what the error actually _is_ because like I said I'm new to this haha... so I was hoping someone here has an idea of what might be wrong? Like I said I made zero changes.

I'm using Windows 7 with Visual Studio Express 2013. Also used CMake version 3.10.1.
![6f4195cbd8ae13a0d1abd882e6deb435](https://user-images.githubusercontent.com/12752293/34396677-14b7a01e-eb3c-11e7-94bc-4ec3fd19b918.png)
This is what I generated for Visual Studio, in case that info helps too.

**Comment by ensiform** [comment]
Uninstall express and install community edition instead. And make sure you have the Visual C++ component installed.

GitHub Issues is not really a place to put build problems for future reference.

**Comment by RecklessJames** [comment]
Alright then I'll look into that, thank you very much for the info!

**Comment by RecklessJames** [comment]
The reason I went with Express in the first place was due to the guide I was following here: https://jkhub.org/tutorials/article/145-compiling-openjk-win32-must-read-for-new-coders/

As for other versions I can't really find them available anywhere online... but thank you very much for the information regardless!

**Comment by ensiform** [comment]
That tutorial should not be followed

**Comment by RecklessJames** [comment]
I'm sorry for posting in this area even if it may not seem to be the best place to ask, but your responses have definitely helped! That being said, I followed what you said and everything built smoothly! Thanks alot, I think I'm good now!
