### ISSUE TITLE
General Comprehension of your aims

### ISSUE THREAD

**Issue by X4RK** [JACoders/OpenJK#953]
Hi,

I have searched in the topics and didn't find anything answering to my questions : 

- What is the aim of improving the code of a 20 y o game? Do you focus on improving only JK or do you do the same job on other game?
- Did some of you developed the game or did you all came to improve it after its creation ? Have you ever contacted any JK developer?
- Why are you not using this knowledge and the "open sourceness" of the code to make a whole new game? (I have only seen mods that look like JK with few modifications)

I know these aren't technical issues, but your answer could fill great blanks around some project I am working on since a while (some kind of JK4, I don't understand why it hasn't been done before...).

Thank you for your attention.

Regards,

XARK

**Comment by eezstreet** [comment]
This isn't really a place for discussion. It's meant to be a bug tracker.
If you want to talk to the developers, best to head onto IRC or Discord.

**Comment by Razish** [comment]
> What is the aim of improving the code of a 20 y o game?

I like it. It's a fun hobby.

> Do you focus on improving only JK or do you do the same job on other game?

Almost entirely just JKA and its mods.

> Did some of you developed the game or did you all came to improve it after its creation?

None of us have worked for Ravensoft

> Have you ever contacted any JK developer?

Yeah, they've been very friendly and historically helpful.

> Why are you not using this knowledge and the "open sourceness" of the code to make a whole new game? (I have only seen mods that look like JK with few modifications)

>(some kind of JK4, I don't understand why it hasn't been done before...)

There have been countless "JK4" attempts in the past 10 years. Every single one has failed, been abandoned, C&Ded, etc. The flavour of the month is an Unreal-based "melee combat simulator" / OpenSaberProject.
The main reasons it hasn't happened are:
* Not wanting to have my professional and personal life ruined by Disney's lawyers.
* Vastly differing opinions on how "JK4" should be done
* Lack of significant contributors / it's a major undertaking for people in their free time

I have put in leading efforts for several projects including a competitive/esport-focused JKA, ioq3-based game, and working on an engine from scratch.
Those 3 points have proven themselves time and time again in the many years I've been involved in JK's community. I also don't trust any AAA studio to do the JK series justice - I'm kind of glad its legacy hasn't been ruined entirely.

15 _years_ later, we seem to be doing alright. Maybe we don't _need_ a JK4 :^)

**Comment by X4RK** [comment]
First thing first, thank you very much for all these detailed responses !

I'll continue my searches on IRC or discord 👍 

By the way I am a fan and have lot of respect for what you do here, I have played JA 1.00 12 years... Never been good but I love this game :)

Just if you have time (for plurality of sources & because you seem to know quite a bit on this) :

If you have ever asked to someone that knew more about how it was going on the project... 
I really would like to know how it was during the project, the difficulties encountered and things like why it hasn't been over-mediatized like kotor, ... 
It seems to me that the game's creator didn't believe on jedi outcast potential and finished the saga fastly with jedi academy.

Maybe it was just our point of view from 1.00 but it seems to me that lugor mods, and most of 1.01 where fan made... 

So I understand perfectly that I am not in the right place but I am really curious about all this and so thank you again for your help and have fun ! :)

XARK
