### ISSUE TITLE
Missing 1920x1080 resolution option

### ISSUE THREAD

**Issue by coreybruce** [JACoders/OpenJK#958]
Hi I am not able to select 1920x1080 resolution in the options, only 640x480,800x600,1024x768,1152x864,1280x1024,1600x1200,2048x1536 and 2400x600 (surround)

**Comment by ensiform** [comment]
What platform? If not Mac, we won't be adding any more options to the actual menu in this project at this time.

Use r_mode -2 in your config/in the console to have the game choose your desktop resolution which I'm assuming is 1920x1080.

**Comment by coreybruce** [comment]
Linux Xubuntu 16.04.3 LTS

**Comment by ensiform** [comment]
Yes or manually set it with r_mode -1 and r_customWidth 1920 and r_customHeight 1080 as has always worked.

**Comment by coreybruce** [comment]
Thank you for the help, that solved my issue.
