### ISSUE TITLE
Add GitHub authentication to buildbot

### ISSUE THREAD

**Issue by deepy** [JACoders/OpenJK#960]
http://docs.buildbot.net/latest/manual/cfg-www.html#buildbot.www.oauth2.GitHubAuth

http://docs.buildbot.net/latest/developer/secrets.html

**Comment by deepy** [comment]
github authentication in place, currently everyone who is me is an admin.

**Comment by deepy** [comment]
github authentication in place, openjk-maintainers can access it.

**Comment by xycaleth** [comment]
Uh, I guess this means this can be closed then :)
