### ISSUE TITLE
Can't launch singleplayer anymore

### ISSUE THREAD

**Issue by Pickles256** [JACoders/OpenJK#968]
This is windows 10 and latest version for all, I ran openjk.cfg in game and when I try to open singleplayer again I get https://pastebin.com/Ntpn5dwU

**Comment by ensiform** [comment]
openjk.cfg is for Multi Player, openjk_sp.cfg is for single player. You should not have loaded openjk.cfg for single player, as you have now instructed the game to attempt to load the multiplayer renderer, among other things.

Delete your openjk_sp.cfg and start a new.

For future reference, do not post issues that are resulting or likely resulting from user error.  That is for discussion on the forums.
