### ISSUE TITLE
A couple issues in single player and 1 with multiplayer.

### ISSUE THREAD

**Issue by K0RP53** [JACoders/OpenJK#970]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Windows Vista sp2

**Is this for single player or multiplayer?**
Single & Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
In single player, the main menu text is missing. In console it says "can't find map maps/yavin1.bsp" when i manage to fumble around and try to start game. This is the GOG version of Jedi Outcast. There is no maps folder in the installation directory that I can find. The multiplayer crashes upon attempting to run.

**What did you expect to happen instead?**
Play

**Comment by xycaleth** [comment]
The files provided by our build servers don’t support Jedi Outcast as we don’t consider the code to be stable. You will need to compile the code yourself to produce the Jedi Outcast executable files.

**Comment by ouned** [comment]
https://github.com/xLAva/JediOutcastLinux

**Comment by ensiform** [comment]
https://jk2mv.org for Jedi Outcast multiplayer
