### ISSUE TITLE
Single Player Triggers Randomly Fail

### ISSUE THREAD

**Issue by ctralie** [JACoders/OpenJK#973]
**Operating system and version:**
Ubuntu 16.04.
v1.0.1.1 linux-x86_64

**Is this for single player or multiplayer?**
Single player

**Description of the bug (and if possible, steps to reproduce the bug):**
First of all, thank you for your great work.  I was able to make it through the entire single player, and it was a lot of fun

One of the bugs I noticed in the game was that triggers randomly fail.  Sometimes, this happens at cutscenes, and the results are hilarious (image attached).  But more often, it happens in small ways.  Like elevators won't get called.  Or in the merchant rescue mission, the player will pick up one of the pieces, but it doesn't register, and so (s)he doesn't get credit for it.  I did find that if I saved the game, exited the program, restarted, and loaded, that would always fix the elevator problem, and it would usually fix the other problems.  And as I said, I was able to get through the entire game without too much trouble, once I figured this out

![screenshot from 2018-03-16 22-53-00](https://user-images.githubusercontent.com/1270246/39598033-48b7f60e-4ee5-11e8-8314-7511a49bb7df.png)

**Comment by ensiform** [comment]
This has been posted before. Please check before making new.

**Comment by ctralie** [comment]
My apologies, I did check but I didn't see it.  Was it ever fixed?

**Comment by ctralie** [comment]
I did see the academy / cutscene part posted, but not the elevators, etc

**Comment by ctralie** [comment]
Good to know, thanks for the quick response!
