### ISSUE TITLE
Builds for OSX and Linux

### ISSUE THREAD

**Issue by gort818** [JACoders/OpenJK#980]
I just noticed It seems there hasn't been new builds for OSX and Linux here https://builds.openjk.org/ for around four months .. are those build servers down? or is it some other issue?

**Comment by ensiform** [comment]
For future, github issues list is not intended for questions.

As far as I know the mac and linux builders are offline or in some state of flux and the owners are not really active to fixing the situation.

**Comment by gort818** [comment]
Oops should have gone on the forums, sorry about that.

Thanks for the answer.
