### ISSUE TITLE
[Bug] GPU Not detected, constantly GDI renderer

### ISSUE THREAD

**Issue by Nightshades1** [JACoders/OpenJK#982]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Windows 10

**Is this for single player or multiplayer?**
Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
I took the latest source of openJK compiled it with Visual Studio 2017 (MP renderer) because i want better stuff when playing the online mod "Movie Battle 2" and the GPU is NOT DETECTED at all it constantly use GDI !

**What did you expect to happen instead?**
Movie Battle 2 has their own version of OpenJK and it work fine, my GPU is detected as it should (Intel HD Graphics 2000) I even wrote a quick C# APP (OpenGL) using OpenTK library and my GPU was detected fine as all the rendering stuff was correctly renderer on my sample app... which mean there is an issue with OpenJK.

Take note that i have also used OpenGL Extension viewer (5.1.4) it detect it properly, and it say i have OpenGL version 3.1.

Seem that there is an issue but i can't tell as i just had a look today so maybe the people in charge of the updates could fix it or if it's a "Legacy Issue" you are welcome to make it like before which mean don't only support newer GPU but older too, thanks.

**Comment by ensiform** [comment]
Not an issue with OpenJK, seek information for your vendor.

**Comment by ensiform** [comment]
Nothing has changed on this end.  And mb2 isn't using a different version where such things could have changed

**Comment by Nightshades1** [comment]
"Nothing has changed on this end. And mb2 isn't using a different version where such things could have changed"

When i use the version of mbii it work and correctly list intel hd graphics 2000 but when i use openJK (this version compiled with latest sdl2).

The driver constantly fallback to GDI, how could this happen ?
It's support openGL 3.1 max (this gpu).

Could it be an issue with the depth pixels or something, because it's weird and it s hard to know why it list the wrong GL_VENDOR ...

Im not the only person having this issue with intel hd graphics on the web and openGL team is like go buy a graphic card, avoiding the issue is a no go.

**Comment by Nightshades1** [comment]
Is OpenJK (mbii) uploaded somewhere ? Because they clearly ignored me ...

**Comment by Nightshades1** [comment]
Might be a bug with that gpu though, i'll try later to run openJK with windows 8.1 compatibility.

I will keep you updated on that.

**Comment by ensiform** [comment]
Showing the console log from both when it works and it doesn't would help narrow down the issue.

**Comment by Nightshades1** [comment]
Hello here is when i use the fresh compiled (Debug OpenJK) i changed the REF_API_VERSION to 9 so it work with mbii.
[openjk.txt](https://github.com/JACoders/OpenJK/files/2245108/openjk.txt)

And that one is from mbii (their openJK build) which work fine.
[mbii.txt](https://github.com/JACoders/OpenJK/files/2245111/mbii.txt)

**Comment by Nightshades1** [comment]
And i think i found the issue, it seem to try to load rd-vanilla_x86.dll instead of rd-vanilla-mbii_x86 i'm checking...

**Comment by Nightshades1** [comment]
ok i deleted OpenJK folder that has all .cfg so it does a full regen of the .cfg
downloaded openJK and compiled with debug, game started it correctly load rd-vanilla_x86.dll but i always have:

![image](https://user-images.githubusercontent.com/19496833/43457915-7c9303dc-94c8-11e8-90b3-7fdb0736e51b.png) which is not normal lol.

**Comment by ensiform** [comment]
Yeah, it's not able to find a real opengl driver. And there's not a whole lot we can do there.

**Comment by Nightshades1** [comment]
I dont get it, even the base jamp detect it fine lol.

**Comment by Nightshades1** [comment]
Its probably the selection of the pixel format/detection that is screwed, base jka (jamp) works fine but when i use openJK its a fail.

Its hard to track this kind of issue, obviously it would return the wrong gl vendor/renderer if this *try* to select stuff that is not compatible with this shitty gpu.

I appreciate your help but we didn't progress so far on the issue ;P

**Comment by ensiform** [comment]
Can't really compare to jamp here, the SDL code is handling most of the management of window creation.

What values do you have for r_depthbits, r_colorbits, and r_texturebits?

**Comment by Nightshades1** [comment]
@ensiform Hello, just wanted to tell that i reformated my pc from windows 10 to windows 8.1, reinstalled all my software ... (A good day from external HDD -> My Pc) i compiled OpenJK and it worked perfectly.

It appear that this GPU (intel hd graphics 2000) have 100% compatibility from windows 7 up to windows 8.1, it didn't work at all under windows 10 because lack of support, driver not made for win10 even though i was in 1920x1080 and microsoft throwed legacy compatibility in the april 2018 update of windows 10...

So the issue is resolved and it was mostly an issue from that driver because intel love to throw support of compatibility for 5+ years old product...

Well the case is now solved, thank you for trying to help into fixing this issue and this can now be CLOSED !

:smiling_imp:
