### ISSUE TITLE
modern computer resolution choice in JK2 sp

### ISSUE THREAD

**Issue by legluondunet** [JACoders/OpenJK#988]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Ubuntu 18.04 84 bits
**Is this for single player or multiplayer?**
JK2 sp
**Description of the bug (and if possible, steps to reproduce the bug):**
I can not choose my resolution in JK2 sp 1920x1080 16/9
**What did you expect to happen instead?**
We need a better way to set resolution in the JK2 sp menu for modern configuration.

**Comment by ensiform** [comment]
Use console as always.

**Comment by legluondunet** [comment]
I think this great piece of game worth better than a tweak the resolution in a console or edit the config file. It's a pity you didn't polish the jk2 sp code part.

**Comment by ensiform** [comment]
Its not about that.  This project doesn't edit the game assets, which changing the menu in the correct way requires altering the assets.

**Comment by legluondunet** [comment]
I'm curious to know why you don't want to modify the assets?

**Comment by PotatoMaster** [comment]
Because OpenJK is about improving the code of the game, not the assets. Mods do that.

**Comment by legluondunet** [comment]
Just a last question: are there mods that actually do that?

**Comment by ensiform** [comment]
Not sure for jk2, but we didn't really have the focus to be able to work on both games.  It was too much

**Comment by legluondunet** [comment]
thank you for your answers.
