### ISSUE TITLE
CMake Error. include could not find load file: CPackNSIS

### ISSUE THREAD

**Issue by 3dots** [JACoders/OpenJK#995]
Hello, I am trying to compile jka from source and ran into this during the Configure step of using CMake:

>CMake Error at CMakeModules/InstallConfig.cmake:70 (include): 
include could not find load file:
    CPackNSIS
Call Stack (most recent call first):
  CMakeLists.txt:180 (include)

Googling netted me [this](https://www.sofa-framework.org/community/forum/topic/cmake-could-not-find-cpacknsis/), which tells me to just comment that line out:
>include(CPackNSIS)

Should I be doing that?

**Operating system and version:**
OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763

**Is this for single player or multiplayer?**
Yes.

**Description of the bug (and if possible, steps to reproduce the bug):**
Fresh install of CMake 3.13.2, doing the Configure.

**What did you expect to happen instead?**
No errors.

**Comment by ensiform** [comment]
Downgrade cmake install, bug on their release candidate.

**Comment by 3dots** [comment]
Thanks. 3.12.4 worked.
