### ISSUE TITLE
Jedi Outcast - Opens Half Screen with no clickable icons

### ISSUE THREAD

**Issue by ZASMan** [JACoders/OpenJK#996]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**

Windows 10

**Is this for single player or multiplayer?**

Single Player

**Description of the bug (and if possible, steps to reproduce the bug):**

1. Go to the gamedata folder of Jedi Outcast
2. Open the .exe file for single player.

**What did you expect to happen instead?**
Opens Jedi Outcast Half Screen and with icons not visible

![jedi-outcast-screenshot](https://user-images.githubusercontent.com/13513340/50551529-d6f76d00-0c4f-11e9-9261-64c40fbdb5ed.png)

**Comment by ensiform** [comment]
Jedi outcast isn't supported by "OpenJK" as you are running it. We do not ship outcast builds.

**Comment by ZASMan** [comment]
I'm not asking for an outcast build, I have the game bought on steam. I just was under the impression this will fix compatibility issues.

**Comment by ensiform** [comment]
If you have any experience working with code and cmake you can turn on building your own copy of the outcast compatible version, but it's not maintained anymore so there's no guarantee that it'll work out of the box.
