### ISSUE TITLE
Can't find save folder

### ISSUE THREAD

**Issue by Spoghettios** [JACoders/OpenJK#999]
OS: Windows 10 pro

Can the save cap be increased with open jk? if not, then is there a the folder for open jk sp saves? I have saves on open jk sp I wanted to put into safe keeping, as I've hit the maximum amount of saves available. The only saves folder I can find contains saves just from the vanilla game.

**Comment by Razish** [comment]
Assuming you've found the answer but for others' reference the writable directory is controlled by `fs_homepath` cvar. On Windows this is something like `%USERDIR%\Documents\My Games\OpenJK` (slightly different on some Windows versions)

**Comment by Spoghettios** [comment]
This issue actually came up again, can't thank you enough for the help.
